project:
  type: book
  output-dir: docs
  resources:
    - ads.txt 

adsense:
  publisher-id: ca-pub-9088403291464012
  filters:
    - adsense

book:
  title: "Constituição Federal de 1988"
  date: "03/30/2025"
  chapters:
    - index.qmd
    - titulo-i.qmd
    - titulo-ii.qmd
    - titulo-iii.qmd
    - titulo-iv.qmd
    - titulo-v.qmd
    - titulo-vi.qmd
    - titulo-vii.qmd
    - titulo-viii.qmd
    - titulo-ix.qmd
  google-analytics: "G-BEK5NBT916"

lang: pt

format:
  html:
    theme:
      light: Sandstone
      dark: cyborg
    number-depth: 3
    number-sections: false
    css: "style.css"
    include-in-header:
      - text: |
          <script src="nav-arrows.js"></script>
          <meta name="google-adsense-account" content="ca-pub-9088403291464012">
          <meta name="google-site-verification" content="vQKRrhqpcuhlTa1rrUy72i4HSEt_V7Fb4bbxJJwNwrg">
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9088403291464012" crossorigin="anonymous"></script>



