# TÍTULO V - Da Defesa do Estado e Das Instituições Democráticas

<span class="caret"></span><ul class="nested">
## CAPÍTULO I - DO ESTADO DE DEFESA E DO ESTADO DE SÍTIO

<span class="caret"></span><ul class="nested">
### SEÇÃO I - DO ESTADO DE DEFESA

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 136**. O Presidente da República pode, ouvidos o Conselho da República e o Conselho de Defesa Nacional, decretar estado de defesa para preservar ou prontamente restabelecer, em locais restritos e determinados, a ordem pública ou a paz social ameaçadas por grave e iminente instabilidade institucional ou atingidas por calamidades de grandes proporções na natureza.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O decreto que instituir o estado de defesa determinará o tempo de sua duração, especificará as áreas a serem abrangidas e indicará, nos termos e limites da lei, as medidas coercitivas a vigorarem, dentre as seguintes:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **restrições aos direitos de:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 90px;" class="level-8">**a)** reunião, ainda que exercida no seio das associações;</span>

<span style="display: block; margin-left: 90px;" class="level-8">**b)** sigilo de correspondência;</span>

<span style="display: block; margin-left: 90px;" class="level-8">**c)** sigilo de comunicação telegráfica e telefônica;</span>

</ul>
<span style="display: block; margin-left: 60px;" class="level-7">**II - **ocupação e uso temporário de bens e serviços públicos, na hipótese de calamidade pública, respondendo a União pelos danos e custos decorrentes.</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º O tempo de duração do estado de defesa não será superior a trinta dias, podendo ser prorrogado uma vez, por igual período, se persistirem as razões que justificaram a sua decretação.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Na vigência do estado de defesa:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **a prisão por crime contra o Estado, determinada pelo executor da medida, será por este comunicada imediatamente ao juiz competente, que a relaxará, se não for legal, facultado ao preso requerer exame de corpo de delito à autoridade policial;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **a comunicação será acompanhada de declaração, pela autoridade, do estado físico e mental do detido no momento de sua autuação;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **a prisão ou detenção de qualquer pessoa não poderá ser superior a dez dias, salvo quando autorizada pelo Poder Judiciário;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **é vedada a incomunicabilidade do preso.</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Decretado o estado de defesa ou sua prorrogação, o Presidente da República, dentro de vinte e quatro horas, submeterá o ato com a respectiva justificação ao Congresso Nacional, que decidirá por maioria absoluta.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Se o Congresso Nacional estiver em recesso, será convocado, extraordinariamente, no prazo de cinco dias.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º O Congresso Nacional apreciará o decreto dentro de dez dias contados de seu recebimento, devendo continuar funcionando enquanto vigorar o estado de defesa.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º Rejeitado o decreto, cessa imediatamente o estado de defesa.</span>

</ul>
</ul>
### SEÇÃO II - DO ESTADO DE SÍTIO

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 137**. O Presidente da República pode, ouvidos o Conselho da República e o Conselho de Defesa Nacional, solicitar ao Congresso Nacional autorização para decretar o estado de sítio nos casos de:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **comoção grave de repercussão nacional ou ocorrência de fatos que comprovem a ineficácia de medida tomada durante o estado de defesa;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **declaração de estado de guerra ou resposta a agressão armada estrangeira.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. O Presidente da República, ao solicitar autorização para decretar o estado de sítio ou sua prorrogação, relatará os motivos determinantes do pedido, devendo o Congresso Nacional decidir por maioria absoluta.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 138**. O decreto do estado de sítio indicará sua duração, as normas necessárias a sua execução e as garantias constitucionais que ficarão suspensas, e, depois de publicado, o Presidente da República designará o executor das medidas específicas e as áreas abrangidas.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º - O estado de sítio, no caso do art. 137, I, não poderá ser decretado por mais de trinta dias, nem prorrogado, de cada vez, por prazo superior; no do inciso II, poderá ser decretado por todo o tempo que perdurar a guerra ou a agressão armada estrangeira.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º - Solicitada autorização para decretar o estado de sítio durante o recesso parlamentar, o Presidente do Senado Federal, de imediato, convocará extraordinariamente o Congresso Nacional para se reunir dentro de cinco dias, a fim de apreciar o ato.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º - O Congresso Nacional permanecerá em funcionamento até o término das medidas coercitivas.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 139**. Na vigência do estado de sítio decretado com fundamento no art. 137, I, só poderão ser tomadas contra as pessoas as seguintes medidas:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **obrigação de permanência em localidade determinada;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **detenção em edifício não destinado a acusados ou condenados por crimes comuns;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **restrições relativas à inviolabilidade da correspondência, ao sigilo das comunicações, à prestação de informações e à liberdade de imprensa, radiodifusão e televisão, na forma da lei;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **suspensão da liberdade de reunião;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **busca e apreensão em domicílio;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **intervenção nas empresas de serviços públicos;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VII - **requisição de bens.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. Não se inclui nas restrições do inciso III a difusão de pronunciamentos de parlamentares efetuados em suas Casas Legislativas, desde que liberada pela respectiva Mesa.</span>

</ul>
</ul>
### SEÇÃO III - DISPOSIÇÕES GERAIS

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 140**. A Mesa do Congresso Nacional, ouvidos os líderes partidários, designará Comissão composta de cinco de seus membros para acompanhar e fiscalizar a execução das medidas referentes ao estado de defesa e ao estado de sítio.</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 141**. Cessado o estado de defesa ou o estado de sítio, cessarão também seus efeitos, sem prejuízo da responsabilidade pelos ilícitos cometidos por seus executores ou agentes.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. Logo que cesse o estado de defesa ou o estado de sítio, as medidas aplicadas em sua vigência serão relatadas pelo Presidente da República, em mensagem ao Congresso Nacional, com especificação e justificação das providências adotadas, com relação nominal dos atingidos e indicação das restrições aplicadas.</span>

</ul>
</ul>
</ul>
## CAPÍTULO II - DAS FORÇAS ARMADAS

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 142**. As Forças Armadas, constituídas pela Marinha, pelo Exército e pela Aeronáutica, são instituições nacionais permanentes e regulares, organizadas com base na hierarquia e na disciplina, sob a autoridade suprema do Presidente da República, e destinam-se à defesa da Pátria, à garantia dos poderes constitucionais e, por iniciativa de qualquer destes, da lei e da ordem.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Lei complementar estabelecerá as normas gerais a serem adotadas na organização, no preparo e no emprego das Forças Armadas.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Não caberá habeas corpus em relação a punições disciplinares militares.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Os membros das Forças Armadas são denominados militares, aplicando-se-lhes, além das que vierem a ser fixadas em lei, as seguintes disposições: (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **as patentes, com prerrogativas, direitos e deveres a elas inerentes, são conferidas pelo Presidente da República e asseguradas em plenitude aos oficiais da ativa, da reserva ou reformados, sendo-lhes privativos os títulos e postos militares e, juntamente com os demais membros, o uso dos uniformes das Forças Armadas; (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **o militar em atividade que tomar posse em cargo ou emprego público civil permanente, ressalvada a hipótese prevista no art. 37, inciso XVI, alínea "c", será transferido para a reserva, nos termos da lei; (Redação dada pela Emenda Constitucional nº 77, de 2014)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **o militar da ativa que, de acordo com a lei, tomar posse em cargo, emprego ou função pública civil temporária, não eletiva, ainda que da administração indireta, ressalvada a hipótese prevista no art. 37, inciso XVI, alínea "c", ficará agregado ao respectivo quadro e somente poderá, enquanto permanecer nessa situação, ser promovido por antiguidade, contando-se-lhe o tempo de serviço apenas para aquela promoção e transferência para a reserva, sendo depois de dois anos de afastamento, contínuos ou não, transferido para a reserva, nos termos da lei; (Redação dada pela Emenda Constitucional nº 77, de 2014)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **ao militar são proibidas a sindicalização e a greve; (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**V - **o militar, enquanto em serviço ativo, não pode estar filiado a partidos políticos; (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VI - **o oficial só perderá o posto e a patente se for julgado indigno do oficialato ou com ele incompatível, por decisão de tribunal militar de caráter permanente, em tempo de paz, ou de tribunal especial, em tempo de guerra; (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VII - **o oficial condenado na justiça comum ou militar a pena privativa de liberdade superior a dois anos, por sentença transitada em julgado, será submetido ao julgamento previsto no inciso anterior; (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VIII - **aplica-se aos militares o disposto no art. 7º, incisos VIII, XII, XVII, XVIII, XIX e XXV, e no art. 37, incisos XI, XIII, XIV e XV, bem como, na forma da lei e com prevalência da atividade militar, no art. 37, inciso XVI, alínea "c"; (Redação dada pela Emenda Constitucional nº 77, de 2014)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IX - **(Revogado pela Emenda Constitucional nº 41, de 19.12.2003)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**X - **a lei disporá sobre o ingresso nas Forças Armadas, os limites de idade, a estabilidade e outras condições de transferência do militar para a inatividade, os direitos, os deveres, a remuneração, as prerrogativas e outras situações especiais dos militares, consideradas as peculiaridades de suas atividades, inclusive aquelas cumpridas por força de compromissos internacionais e de guerra. (Incluído pela Emenda Constitucional nº 18, de 1998)</span>

</ul>
</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 143**. O serviço militar é obrigatório nos termos da lei.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Às Forças Armadas compete, na forma da lei, atribuir serviço alternativo aos que, em tempo de paz, após alistados, alegarem imperativo de consciência, entendendo-se como tal o decorrente de crença religiosa e de convicção filosófica ou política, para se eximirem de atividades de caráter essencialmente militar. (Regulamento)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º As mulheres e os eclesiásticos ficam isentos do serviço militar obrigatório em tempo de paz, sujeitos, porém, a outros encargos que a lei lhes atribuir. (Regulamento)</span>

</ul>
</ul>
## CAPÍTULO III - DA SEGURANÇA PÚBLICA

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 144**. A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio, através dos seguintes órgãos:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **polícia federal;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **polícia rodoviária federal;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **polícia ferroviária federal;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **polícias civis;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **polícias militares e corpos de bombeiros militares.</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **polícias penais federal, estaduais e distrital. (Redação dada pela Emenda Constitucional nº 104, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º A polícia federal, instituída por lei como órgão permanente, organizado e mantido pela União e estruturado em carreira, destina-se a:" (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **apurar infrações penais contra a ordem política e social ou em detrimento de bens, serviços e interesses da União ou de suas entidades autárquicas e empresas públicas, assim como outras infrações cuja prática tenha repercussão interestadual ou internacional e exija repressão uniforme, segundo se dispuser em lei;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **prevenir e reprimir o tráfico ilícito de entorpecentes e drogas afins, o contrabando e o descaminho, sem prejuízo da ação fazendária e de outros órgãos públicos nas respectivas áreas de competência;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **exercer as funções de polícia marítima, aeroportuária e de fronteiras; (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **exercer, com exclusividade, as funções de polícia judiciária da União.</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A polícia rodoviária federal, órgão permanente, organizado e mantido pela União e estruturado em carreira, destina-se, na forma da lei, ao patrulhamento ostensivo das rodovias federais. (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º A polícia ferroviária federal, órgão permanente, organizado e mantido pela União e estruturado em carreira, destina-se, na forma da lei, ao patrulhamento ostensivo das ferrovias federais. (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Às polícias civis, dirigidas por delegados de polícia de carreira, incumbem, ressalvada a competência da União, as funções de polícia judiciária e a apuração de infrações penais, exceto as militares.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Às polícias militares cabem a polícia ostensiva e a preservação da ordem pública; aos corpos de bombeiros militares, além das atribuições definidas em lei, incumbe a execução de atividades de defesa civil.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º-A. Às polícias penais, vinculadas ao órgão administrador do sistema penal da unidade federativa a que pertencem, cabe a segurança dos estabelecimentos penais. (Redação dada pela Emenda Constitucional nº 104, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º As polícias militares e os corpos de bombeiros militares, forças auxiliares e reserva do Exército subordinam-se, juntamente com as polícias civis e as polícias penais estaduais e distrital, aos Governadores dos Estados, do Distrito Federal e dos Territórios. (Redação dada pela Emenda Constitucional nº 104, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º A lei disciplinará a organização e o funcionamento dos órgãos responsáveis pela segurança pública, de maneira a garantir a eficiência de suas atividades. (Vide Lei nº 13.675, de 2018) Vigência</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º Os Municípios poderão constituir guardas municipais destinadas à proteção de seus bens, serviços e instalações, conforme dispuser a lei. (Vide Lei nº 13.022, de 2014)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 9**º A remuneração dos servidores policiais integrantes dos órgãos relacionados neste artigo será fixada na forma do § 4º do art. 39. (Incluído pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 10**. A segurança viária, exercida para a preservação da ordem pública e da incolumidade das pessoas e do seu patrimônio nas vias públicas: (Incluído pela Emenda Constitucional nº 82, de 2014)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **compreende a educação, engenharia e fiscalização de trânsito, além de outras atividades previstas em lei, que assegurem ao cidadão o direito à mobilidade urbana eficiente; e (Incluído pela Emenda Constitucional nº 82, de 2014)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **compete, no âmbito dos Estados, do Distrito Federal e dos Municípios, aos respectivos órgãos ou entidades executivos e seus agentes de trânsito, estruturados em Carreira, na forma da lei. (Incluído pela Emenda Constitucional nº 82, de 2014)</span>

</ul>
</ul>
</ul>
</ul>
