# TÍTULO IV - Da Organização dos Poderes

## CAPÍTULO I - DO PODER LEGISLATIVO

### SEÇÃO I - DO CONGRESSO NACIONAL

<details open style="margin-left: 0px;">
<summary>**Art. 44**. O Poder Legislativo é exercido pelo Congresso Nacional, que se compõe da Câmara dos Deputados e do Senado Federal.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Cada legislatura terá a duração de quatro anos.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 45**. A Câmara dos Deputados compõe-se de representantes do povo, eleitos, pelo sistema proporcional, em cada Estado, em cada Território e no Distrito Federal.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º O número total de Deputados, bem como a representação por Estado e pelo Distrito Federal, será estabelecido por lei complementar, proporcionalmente à população, procedendo-se aos ajustes necessários, no ano anterior às eleições, para que nenhuma daquelas unidades da Federação tenha menos de oito ou mais de setenta Deputados. (Vide Lei Complementar nº 78, de 1993)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Cada Território elegerá quatro Deputados.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 46**. O Senado Federal compõe-se de representantes dos Estados e do Distrito Federal, eleitos segundo o princípio majoritário.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Cada Estado e o Distrito Federal elegerão três Senadores, com mandato de oito anos.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º A representação de cada Estado e do Distrito Federal será renovada de quatro em quatro anos, alternadamente, por um e dois terços.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Cada Senador será eleito com dois suplentes.</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 47**. Salvo disposição constitucional em contrário, as deliberações de cada Casa e de suas Comissões serão tomadas por maioria dos votos, presente a maioria absoluta de seus membros.</span>

### SEÇÃO II - DAS ATRIBUIÇÕES DO CONGRESSO NACIONAL

<details open style="margin-left: 0px;">
<summary>**Art. 48**. Cabe ao Congresso Nacional, com a sanção do Presidente da República, não exigida esta para o especificado nos arts. 49, 51 e 52, dispor sobre todas as matérias de competência da União, especialmente sobre:</summary>
<span style="display: block; margin-left: 30px;">**I - **sistema tributário, arrecadação e distribuição de rendas;</span>

<span style="display: block; margin-left: 30px;">**II - **plano plurianual, diretrizes orçamentárias, orçamento anual, operações de crédito, dívida pública e emissões de curso forçado;</span>

<span style="display: block; margin-left: 30px;">**III - **fixação e modificação do efetivo das Forças Armadas;</span>

<span style="display: block; margin-left: 30px;">**IV - **planos e programas nacionais, regionais e setoriais de desenvolvimento;</span>

<span style="display: block; margin-left: 30px;">**V - **limites do território nacional, espaço aéreo e marítimo e bens do domínio da União;</span>

<span style="display: block; margin-left: 30px;">**VI - **incorporação, subdivisão ou desmembramento de áreas de Territórios ou Estados, ouvidas as respectivas Assembléias Legislativas;</span>

<span style="display: block; margin-left: 30px;">**VII - **transferência temporária da sede do Governo Federal;</span>

<span style="display: block; margin-left: 30px;">**VIII - **concessão de anistia;</span>

<span style="display: block; margin-left: 30px;">**IX - **organização administrativa, judiciária, do Ministério Público e da Defensoria Pública da União e dos Territórios e organização judiciária e do Ministério Público do Distrito Federal; (Redação dada pela Emenda Constitucional nº 69, de 2012) (Produção de efeito)</span>

<span style="display: block; margin-left: 30px;">**XII - **telecomunicações e radiodifusão;</span>

<span style="display: block; margin-left: 30px;">**XIII - **matéria financeira, cambial e monetária, instituições financeiras e suas operações;</span>

<span style="display: block; margin-left: 30px;">**XIV - **moeda, seus limites de emissão, e montante da dívida mobiliária federal.</span>

<span style="display: block; margin-left: 30px;">**XV - **fixação do subsídio dos Ministros do Supremo Tribunal Federal, observado o que dispõem os arts. 39, § 4º; 150, II; 153, III; e 153, § 2º, I. (Redação dada pela Emenda Constitucional nº 41, 19.12.2003)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 49**. É da competência exclusiva do Congresso Nacional:</summary>
<span style="display: block; margin-left: 30px;">**I - **resolver definitivamente sobre tratados, acordos ou atos internacionais que acarretem encargos ou compromissos gravosos ao patrimônio nacional;</span>

<span style="display: block; margin-left: 30px;">**II - **autorizar o Presidente da República a declarar guerra, a celebrar a paz, a permitir que forças estrangeiras transitem pelo território nacional ou nele permaneçam temporariamente, ressalvados os casos previstos em lei complementar;</span>

<span style="display: block; margin-left: 30px;">**III - **autorizar o Presidente e o Vice-Presidente da República a se ausentarem do País, quando a ausência exceder a quinze dias;</span>

<span style="display: block; margin-left: 30px;">**IV - **aprovar o estado de defesa e a intervenção federal, autorizar o estado de sítio, ou suspender qualquer uma dessas medidas;</span>

<span style="display: block; margin-left: 30px;">**V - **sustar os atos normativos do Poder Executivo que exorbitem do poder regulamentar ou dos limites de delegação legislativa;</span>

<span style="display: block; margin-left: 30px;">**VI - **mudar temporariamente sua sede;</span>

<span style="display: block; margin-left: 30px;">**VII - **fixar idêntico subsídio para os Deputados Federais e os Senadores, observado o que dispõem os arts. 37, XI, 39, § 4º, 150, II, 153, III, e 153, § 2º, I; (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;">**VIII - **fixar os subsídios do Presidente e do Vice-Presidente da República e dos Ministros de Estado, observado o que dispõem os arts. 37, XI, 39, § 4º, 150, II, 153, III, e 153, § 2º, I; (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;">**IX - **julgar anualmente as contas prestadas pelo Presidente da República e apreciar os relatórios sobre a execução dos planos de governo;</span>

<span style="display: block; margin-left: 30px;">**X - **fiscalizar e controlar, diretamente, ou por qualquer de suas Casas, os atos do Poder Executivo, incluídos os da administração indireta;</span>

<span style="display: block; margin-left: 30px;">**XI - **zelar pela preservação de sua competência legislativa em face da atribuição normativa dos outros Poderes;</span>

<span style="display: block; margin-left: 30px;">**XII - **apreciar os atos de concessão e renovação de concessão de emissoras de rádio e televisão;</span>

<span style="display: block; margin-left: 30px;">**XIII - **escolher dois terços dos membros do Tribunal de Contas da União;</span>

<span style="display: block; margin-left: 30px;">**XIV - **aprovar iniciativas do Poder Executivo referentes a atividades nucleares;</span>

<span style="display: block; margin-left: 30px;">**XV - **autorizar referendo e convocar plebiscito;</span>

<span style="display: block; margin-left: 30px;">**XVI - **autorizar, em terras indígenas, a exploração e o aproveitamento de recursos hídricos e a pesquisa e lavra de riquezas minerais;</span>

<span style="display: block; margin-left: 30px;">**XVII - **aprovar, previamente, a alienação ou concessão de terras públicas com área superior a dois mil e quinhentos hectares.</span>

<span style="display: block; margin-left: 30px;">**XVIII - **decretar o estado de calamidade pública de âmbito nacional previsto nos arts. 167-B, 167-C, 167-D, 167-E, 167-F e 167-G desta Constituição. (Incluído pela Emenda Constitucional nº 109, de 2021)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 50**. A Câmara dos Deputados e o Senado Federal, ou qualquer de suas Comissões, poderão convocar Ministro de Estado, quaisquer titulares de órgãos diretamente subordinados à Presidência da República ou o Presidente do Comitê Gestor do Imposto sobre Bens e Serviços para prestarem, pessoalmente, informações sobre assunto previamente determinado, importando crime de responsabilidade a ausência sem justificação adequada. (Redação dada pela Emenda Constitucional nº 132, de 2023)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os Ministros de Estado poderão comparecer ao Senado Federal, à Câmara dos Deputados, ou a qualquer de suas Comissões, por sua iniciativa e mediante entendimentos com a Mesa respectiva, para expor assunto de relevância de seu Ministério.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º As Mesas da Câmara dos Deputados e do Senado Federal poderão encaminhar pedidos escritos de informações a Ministros de Estado ou a qualquer das pessoas referidas no caput deste artigo, importando em crime de responsabilidade a recusa, ou o não - atendimento, no prazo de trinta dias, bem como a prestação de informações falsas. (Redação dada pela Emenda Constitucional de Revisão nº 2, de 1994)</span>

</details>

### SEÇÃO III - DA CÂMARA DOS DEPUTADOS

<details open style="margin-left: 0px;">
<summary>**Art. 51**. Compete privativamente à Câmara dos Deputados:</summary>
<span style="display: block; margin-left: 30px;">**I - **autorizar, por dois terços de seus membros, a instauração de processo contra o Presidente e o Vice-Presidente da República e os Ministros de Estado;</span>

<span style="display: block; margin-left: 30px;">**II - **proceder à tomada de contas do Presidente da República, quando não apresentadas ao Congresso Nacional dentro de sessenta dias após a abertura da sessão legislativa;</span>

<span style="display: block; margin-left: 30px;">**III - **elaborar seu regimento interno;</span>

<span style="display: block; margin-left: 30px;">**V - **eleger membros do Conselho da República, nos termos do art. 89, VII.</span>

</details>

### SEÇÃO IV - DO SENADO FEDERAL

<details open style="margin-left: 0px;">
<summary>**Art. 52**. Compete privativamente ao Senado Federal:</summary>
<span style="display: block; margin-left: 30px;">**I - **processar e julgar o Presidente e o Vice-Presidente da República nos crimes de responsabilidade, bem como os Ministros de Estado e os Comandantes da Marinha, do Exército e da Aeronáutica nos crimes da mesma natureza conexos com aqueles; (Redação dada pela Emenda Constitucional nº 23, de 1999)</span>

<details open style="margin-left: 30px;">
<summary>**III - **aprovar previamente, por voto secreto, após argüição pública, a escolha de:</summary>
<span style="display: block; margin-left: 60px;">**a)** Magistrados, nos casos estabelecidos nesta Constituição;</span>

<span style="display: block; margin-left: 60px;">**b)** Ministros do Tribunal de Contas da União indicados pelo Presidente da República;</span>

<span style="display: block; margin-left: 60px;">**c)** Governador de Território;</span>

<span style="display: block; margin-left: 60px;">**d)** Presidente e diretores do banco central;</span>

<span style="display: block; margin-left: 60px;">**e)** Procurador-Geral da República;</span>

<span style="display: block; margin-left: 60px;">**f)** titulares de outros cargos que a lei determinar;</span>

</details>

<span style="display: block; margin-left: 30px;">**IV - **aprovar previamente, por voto secreto, após argüição em sessão secreta, a escolha dos chefes de missão diplomática de caráter permanente;</span>

<span style="display: block; margin-left: 30px;">**V - **autorizar operações externas de natureza financeira, de interesse da União, dos Estados, do Distrito Federal, dos Territórios e dos Municípios;</span>

<span style="display: block; margin-left: 30px;">**VI - **fixar, por proposta do Presidente da República, limites globais para o montante da dívida consolidada da União, dos Estados, do Distrito Federal e dos Municípios;</span>

<span style="display: block; margin-left: 30px;">**VII - **dispor sobre limites globais e condições para as operações de crédito externo e interno da União, dos Estados, do Distrito Federal e dos Municípios, de suas autarquias e demais entidades controladas pelo Poder Público federal;</span>

<span style="display: block; margin-left: 30px;">**VIII - **dispor sobre limites e condições para a concessão de garantia da União em operações de crédito externo e interno;</span>

<span style="display: block; margin-left: 30px;">**IX - **estabelecer limites globais e condições para o montante da dívida mobiliária dos Estados, do Distrito Federal e dos Municípios;</span>

<span style="display: block; margin-left: 30px;">**X - **suspender a execução, no todo ou em parte, de lei declarada inconstitucional por decisão definitiva do Supremo Tribunal Federal;</span>

<span style="display: block; margin-left: 30px;">**XI - **aprovar, por maioria absoluta e por voto secreto, a exoneração, de ofício, do Procurador-Geral da República antes do término de seu mandato;</span>

<span style="display: block; margin-left: 30px;">**XII - **elaborar seu regimento interno;</span>

<span style="display: block; margin-left: 30px;">**XIII - **dispor sobre sua organização, funcionamento, polícia, criação, transformação ou extinção dos cargos, empregos e funções de seus serviços, e a iniciativa de lei para fixação da respectiva remuneração, observados os parâmetros estabelecidos na lei de diretrizes orçamentárias; (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;">**XIV - **eleger membros do Conselho da República, nos termos do art. 89, VII.</span>

<span style="display: block; margin-left: 30px;">**XV - **avaliar periodicamente a funcionalidade do Sistema Tributário Nacional, em sua estrutura e seus componentes, e o desempenho das administrações tributárias da União, dos Estados e do Distrito Federal e dos Municípios. (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span style="display: block; margin-left: 30px;">**Parágrafo único**. Nos casos previstos nos incisos I e II, funcionará como Presidente o do Supremo Tribunal Federal, limitando-se a condenação, que somente será proferida por dois terços dos votos do Senado Federal, à perda do cargo, com inabilitação, por oito anos, para o exercício de função pública, sem prejuízo das demais sanções judiciais cabíveis.</span>

</details>

### SEÇÃO V - DOS DEPUTADOS E DOS SENADORES

<details open style="margin-left: 0px;">
<summary>**Art. 53**. Os Deputados e Senadores são invioláveis, civil e penalmente, por quaisquer de suas opiniões, palavras e votos. (Redação dada pela Emenda Constitucional nº 35, de 2001)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os Deputados e Senadores, desde a expedição do diploma, serão submetidos a julgamento perante o Supremo Tribunal Federal. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Desde a expedição do diploma, os membros do Congresso Nacional não poderão ser presos, salvo em flagrante de crime inafiançável. Nesse caso, os autos serão remetidos dentro de vinte e quatro horas à Casa respectiva, para que, pelo voto da maioria de seus membros, resolva sobre a prisão. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Recebida a denúncia contra o Senador ou Deputado, por crime ocorrido após a diplomação, o Supremo Tribunal Federal dará ciência à Casa respectiva, que, por iniciativa de partido político nela representado e pelo voto da maioria de seus membros, poderá, até a decisão final, sustar o andamento da ação. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O pedido de sustação será apreciado pela Casa respectiva no prazo improrrogável de quarenta e cinco dias do seu recebimento pela Mesa Diretora. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º A sustação do processo suspende a prescrição, enquanto durar o mandato. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 6**º Os Deputados e Senadores não serão obrigados a testemunhar sobre informações recebidas ou prestadas em razão do exercício do mandato, nem sobre as pessoas que lhes confiaram ou deles receberam informações. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 7**º A incorporação às Forças Armadas de Deputados e Senadores, embora militares e ainda que em tempo de guerra, dependerá de prévia licença da Casa respectiva. (Redação dada pela Emenda Constitucional nº 35, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 8**º As imunidades de Deputados ou Senadores subsistirão durante o estado de sítio, só podendo ser suspensas mediante o voto de dois terços dos membros da Casa respectiva, nos casos de atos praticados fora do recinto do Congresso Nacional, que sejam incompatíveis com a execução da medida. (Incluído pela Emenda Constitucional nº 35, de 2001)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 54**. Os Deputados e Senadores não poderão:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **desde a expedição do diploma:</summary>
<span style="display: block; margin-left: 60px;">**a)** firmar ou manter contrato com pessoa jurídica de direito público, autarquia, empresa pública, sociedade de economia mista ou empresa concessionária de serviço público, salvo quando o contrato obedecer a cláusulas uniformes;</span>

<span style="display: block; margin-left: 60px;">**b)** aceitar ou exercer cargo, função ou emprego remunerado, inclusive os de que sejam demissíveis "ad nutum", nas entidades constantes da alínea anterior;</span>

</details>

<details open style="margin-left: 30px;">
<summary>**II - **desde a posse:</summary>
<span style="display: block; margin-left: 60px;">**a)** ser proprietários, controladores ou diretores de empresa que goze de favor decorrente de contrato com pessoa jurídica de direito público, ou nela exercer função remunerada;</span>

<span style="display: block; margin-left: 60px;">**b)** ocupar cargo ou função de que sejam demissíveis "ad nutum", nas entidades referidas no inciso I, "a";</span>

<span style="display: block; margin-left: 60px;">**c)** patrocinar causa em que seja interessada qualquer das entidades a que se refere o inciso I, "a";</span>

<span style="display: block; margin-left: 60px;">**d)** ser titulares de mais de um cargo ou mandato público eletivo.</span>

</details>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 55**. Perderá o mandato o Deputado ou Senador:</summary>
<span style="display: block; margin-left: 30px;">**I - **que infringir qualquer das proibições estabelecidas no artigo anterior;</span>

<span style="display: block; margin-left: 30px;">**II - **cujo procedimento for declarado incompatível com o decoro parlamentar;</span>

<span style="display: block; margin-left: 30px;">**III - **que deixar de comparecer, em cada sessão legislativa, à terça parte das sessões ordinárias da Casa a que pertencer, salvo licença ou missão por esta autorizada;</span>

<span style="display: block; margin-left: 30px;">**IV - **que perder ou tiver suspensos os direitos políticos;</span>

<span style="display: block; margin-left: 30px;">**V - **quando o decretar a Justiça Eleitoral, nos casos previstos nesta Constituição;</span>

<span style="display: block; margin-left: 30px;">**VI - **que sofrer condenação criminal em sentença transitada em julgado.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º - É incompatível com o decoro parlamentar, além dos casos definidos no regimento interno, o abuso das prerrogativas asseguradas a membro do Congresso Nacional ou a percepção de vantagens indevidas.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Nos casos dos incisos I, II e VI, a perda do mandato será decidida pela Câmara dos Deputados ou pelo Senado Federal, por maioria absoluta, mediante provocação da respectiva Mesa ou de partido político representado no Congresso Nacional, assegurada ampla defesa. (Redação dada pela Emenda Constitucional nº 76, de 2013)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º - Nos casos previstos nos incisos III a V, a perda será declarada pela Mesa da Casa respectiva, de ofício ou mediante provocação de qualquer de seus membros, ou de partido político representado no Congresso Nacional, assegurada ampla defesa.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º A renúncia de parlamentar submetido a processo que vise ou possa levar à perda do mandato, nos termos deste artigo, terá seus efeitos suspensos até as deliberações finais de que tratam os §§ 2º e 3º. (Incluído pela Emenda Constitucional de Revisão nº 6, de 1994)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 56**. Não perderá o mandato o Deputado ou Senador:</summary>
<span style="display: block; margin-left: 30px;">**I - **investido no cargo de Ministro de Estado, Governador de Território, Secretário de Estado, do Distrito Federal, de Território, de Prefeitura de Capital ou chefe de missão diplomática temporária;</span>

<span style="display: block; margin-left: 30px;">**II - **licenciado pela respectiva Casa por motivo de doença, ou para tratar, sem remuneração, de interesse particular, desde que, neste caso, o afastamento não ultrapasse cento e vinte dias por sessão legislativa.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º O suplente será convocado nos casos de vaga, de investidura em funções previstas neste artigo ou de licença superior a cento e vinte dias.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Ocorrendo vaga e não havendo suplente, far-se-á eleição para preenchê-la se faltarem mais de quinze meses para o término do mandato.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Na hipótese do inciso I, o Deputado ou Senador poderá optar pela remuneração do mandato.</span>

</details>

### SEÇÃO VI - DAS REUNIÕES

<details open style="margin-left: 0px;">
<summary>**Art. 57**. O Congresso Nacional reunir-se-á, anualmente, na Capital Federal, de 2 de fevereiro a 17 de julho e de 1º de agosto a 22 de dezembro. (Redação dada pela Emenda Constitucional nº 50, de 2006)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º As reuniões marcadas para essas datas serão transferidas para o primeiro dia útil subseqüente, quando recaírem em sábados, domingos ou feriados.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º A sessão legislativa não será interrompida sem a aprovação do projeto de lei de diretrizes orçamentárias.</span>

<details open style="margin-left: 30px;">
<summary>**§ 3**º Além de outros casos previstos nesta Constituição, a Câmara dos Deputados e o Senado Federal reunir-se-ão em sessão conjunta para:</summary>
<span style="display: block; margin-left: 60px;">**I - **inaugurar a sessão legislativa;</span>

<span style="display: block; margin-left: 60px;">**II - **elaborar o regimento comum e regular a criação de serviços comuns às duas Casas;</span>

<span style="display: block; margin-left: 60px;">**III - **receber o compromisso do Presidente e do Vice-Presidente da República;</span>

<span style="display: block; margin-left: 60px;">**IV - **conhecer do veto e sobre ele deliberar.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 4**º Cada uma das Casas reunir-se-á em sessões preparatórias, a partir de 1º de fevereiro, no primeiro ano da legislatura, para a posse de seus membros e eleição das respectivas Mesas, para mandato de 2 (dois) anos, vedada a recondução para o mesmo cargo na eleição imediatamente subseqüente. (Redação dada pela Emenda Constitucional nº 50, de 2006)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º A Mesa do Congresso Nacional será presidida pelo Presidente do Senado Federal, e os demais cargos serão exercidos, alternadamente, pelos ocupantes de cargos equivalentes na Câmara dos Deputados e no Senado Federal.</span>

<details open style="margin-left: 30px;">
<summary>**§ 6**º A convocação extraordinária do Congresso Nacional far-se-á: (Redação dada pela Emenda Constitucional nº 50, de 2006)</summary>
<span style="display: block; margin-left: 60px;">**I - **pelo Presidente do Senado Federal, em caso de decretação de estado de defesa ou de intervenção federal, de pedido de autorização para a decretação de estado de sítio e para o compromisso e a posse do Presidente e do Vice-Presidente da República;</span>

<span style="display: block; margin-left: 60px;">**II - **pelo Presidente da República, pelos Presidentes da Câmara dos Deputados e do Senado Federal ou a requerimento da maioria dos membros de ambas as Casas, em caso de urgência ou interesse público relevante, em todas as hipóteses deste inciso com a aprovação da maioria absoluta de cada uma das Casas do Congresso Nacional. (Redação dada pela Emenda Constitucional nº 50, de 2006)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 7**º Na sessão legislativa extraordinária, o Congresso Nacional somente deliberará sobre a matéria para a qual foi convocado, ressalvada a hipótese do § 8º deste artigo, vedado o pagamento de parcela indenizatória, em razão da convocação. (Redação dada pela Emenda Constitucional nº 50, de 2006)</span>

<span style="display: block; margin-left: 30px;">**§ 8**º Havendo medidas provisórias em vigor na data de convocação extraordinária do Congresso Nacional, serão elas automaticamente incluídas na pauta da convocação. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

</details>

### SEÇÃO VII - DAS COMISSÕES

<details open style="margin-left: 0px;">
<summary>**Art. 58**. O Congresso Nacional e suas Casas terão comissões permanentes e temporárias, constituídas na forma e com as atribuições previstas no respectivo regimento ou no ato de que resultar sua criação.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Na constituição das Mesas e de cada Comissão, é assegurada, tanto quanto possível, a representação proporcional dos partidos ou dos blocos parlamentares que participam da respectiva Casa.</span>

<details open style="margin-left: 30px;">
<summary>**§ 2**º Às comissões, em razão da matéria de sua competência, cabe:</summary>
<span style="display: block; margin-left: 60px;">**I - **discutir e votar projeto de lei que dispensar, na forma do regimento, a competência do Plenário, salvo se houver recurso de um décimo dos membros da Casa;</span>

<span style="display: block; margin-left: 60px;">**II - **realizar audiências públicas com entidades da sociedade civil;</span>

<span style="display: block; margin-left: 60px;">**III - **convocar Ministros de Estado para prestar informações sobre assuntos inerentes a suas atribuições;</span>

<span style="display: block; margin-left: 60px;">**IV - **receber petições, reclamações, representações ou queixas de qualquer pessoa contra atos ou omissões das autoridades ou entidades públicas;</span>

<span style="display: block; margin-left: 60px;">**V - **solicitar depoimento de qualquer autoridade ou cidadão;</span>

<span style="display: block; margin-left: 60px;">**VI - **apreciar programas de obras, planos nacionais, regionais e setoriais de desenvolvimento e sobre eles emitir parecer.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 3**º As comissões parlamentares de inquérito, que terão poderes de investigação próprios das autoridades judiciais, além de outros previstos nos regimentos das respectivas Casas, serão criadas pela Câmara dos Deputados e pelo Senado Federal, em conjunto ou separadamente, mediante requerimento de um terço de seus membros, para a apuração de fato determinado e por prazo certo, sendo suas conclusões, se for o caso, encaminhadas ao Ministério Público, para que promova a responsabilidade civil ou criminal dos infratores.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Durante o recesso, haverá uma Comissão representativa do Congresso Nacional, eleita por suas Casas na última sessão ordinária do período legislativo, com atribuições definidas no regimento comum, cuja composição reproduzirá, quanto possível, a proporcionalidade da representação partidária.</span>

</details>

### SEÇÃO VIII - DO PROCESSO LEGISLATIVO

#### SUBSEÇÃO I - Disposição Geral

<details open style="margin-left: 0px;">
<summary>**Art. 59**. O processo legislativo compreende a elaboração de:</summary>
<span style="display: block; margin-left: 30px;">**I - **emendas à Constituição;</span>

<span style="display: block; margin-left: 30px;">**II - **leis complementares;</span>

<span style="display: block; margin-left: 30px;">**III - **leis ordinárias;</span>

<span style="display: block; margin-left: 30px;">**IV - **leis delegadas;</span>

<span style="display: block; margin-left: 30px;">**V - **medidas provisórias;</span>

<span style="display: block; margin-left: 30px;">**VI - **decretos legislativos;</span>

<span style="display: block; margin-left: 30px;">**VII - **resoluções.</span>

<span style="display: block; margin-left: 30px;">**Parágrafo único**. Lei complementar disporá sobre a elaboração, redação, alteração e consolidação das leis.</span>

</details>

#### SUBSEÇÃO II - Da Emenda à Constituição

<details open style="margin-left: 0px;">
<summary>**Art. 60**. A Constituição poderá ser emendada mediante proposta:</summary>
<span style="display: block; margin-left: 30px;">**I - **de um terço, no mínimo, dos membros da Câmara dos Deputados ou do Senado Federal;</span>

<span style="display: block; margin-left: 30px;">**II - **do Presidente da República;</span>

<span style="display: block; margin-left: 30px;">**III - **de mais da metade das Assembléias Legislativas das unidades da Federação, manifestando-se, cada uma delas, pela maioria relativa de seus membros.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º A Constituição não poderá ser emendada na vigência de intervenção federal, de estado de defesa ou de estado de sítio.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º A proposta será discutida e votada em cada Casa do Congresso Nacional, em dois turnos, considerando-se aprovada se obtiver, em ambos, três quintos dos votos dos respectivos membros.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º A emenda à Constituição será promulgada pelas Mesas da Câmara dos Deputados e do Senado Federal, com o respectivo número de ordem.</span>

<details open style="margin-left: 30px;">
<summary>**§ 4**º Não será objeto de deliberação a proposta de emenda tendente a abolir:</summary>
<span style="display: block; margin-left: 60px;">**I - **a forma federativa de Estado;</span>

<span style="display: block; margin-left: 60px;">**II - **o voto direto, secreto, universal e periódico;</span>

<span style="display: block; margin-left: 60px;">**III - **a separação dos Poderes;</span>

<span style="display: block; margin-left: 60px;">**IV - **os direitos e garantias individuais.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 5**º A matéria constante de proposta de emenda rejeitada ou havida por prejudicada não pode ser objeto de nova proposta na mesma sessão legislativa.</span>

</details>

#### SUBSEÇÃO III - Das Leis

<details open style="margin-left: 0px;">
<summary>**Art. 61**. A iniciativa das leis complementares e ordinárias cabe a qualquer membro ou Comissão da Câmara dos Deputados, do Senado Federal ou do Congresso Nacional, ao Presidente da República, ao Supremo Tribunal Federal, aos Tribunais Superiores, ao Procurador-Geral da República e aos cidadãos, na forma e nos casos previstos nesta Constituição.</summary>
<details open style="margin-left: 30px;">
<summary>**§ 1**º São de iniciativa privativa do Presidente da República as leis que:</summary>
<span style="display: block; margin-left: 60px;">**I - **fixem ou modifiquem os efetivos das Forças Armadas;</span>

<details open style="margin-left: 60px;">
<summary>**II - **disponham sobre:</summary>
<span style="display: block; margin-left: 90px;">**a)** criação de cargos, funções ou empregos públicos na administração direta e autárquica ou aumento de sua remuneração;</span>

<span style="display: block; margin-left: 90px;">**b)** organização administrativa e judiciária, matéria tributária e orçamentária, serviços públicos e pessoal da administração dos Territórios;</span>

<span style="display: block; margin-left: 90px;">**c)** servidores públicos da União e Territórios, seu regime jurídico, provimento de cargos, estabilidade e aposentadoria; (Redação dada pela Emenda Constitucional nº 18, de 1998)</span>

<span style="display: block; margin-left: 90px;">**d)** organização do Ministério Público e da Defensoria Pública da União, bem como normas gerais para a organização do Ministério Público e da Defensoria Pública dos Estados, do Distrito Federal e dos Territórios;</span>

<span style="display: block; margin-left: 90px;">**e)** criação e extinção de Ministérios e órgãos da administração pública, observado o disposto no art. 84, VI; (Redação dada pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 90px;">**f)** militares das Forças Armadas, seu regime jurídico, provimento de cargos, promoções, estabilidade, remuneração, reforma e transferência para a reserva. (Incluída pela Emenda Constitucional nº 18, de 1998)</span>

</details>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º A iniciativa popular pode ser exercida pela apresentação à Câmara dos Deputados de projeto de lei subscrito por, no mínimo, um por cento do eleitorado nacional, distribuído pelo menos por cinco Estados, com não menos de três décimos por cento dos eleitores de cada um deles.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 62**. Em caso de relevância e urgência, o Presidente da República poderá adotar medidas provisórias, com força de lei, devendo submetê-las de imediato ao Congresso Nacional. (Redação dada pela Emenda Constitucional nº 32, de 2001)</summary>
<details open style="margin-left: 30px;">
<summary>**§ 1**º É vedada a edição de medidas provisórias sobre matéria: (Incluído pela Emenda Constitucional nº 32, de 2001)</summary>
<span style="display: block; margin-left: 60px;">**a)** nacionalidade, cidadania, direitos políticos, partidos políticos e direito eleitoral; (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 60px;">**b)** direito penal, processual penal e processual civil; (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 60px;">**c)** organização do Poder Judiciário e do Ministério Público, a carreira e a garantia de seus membros; (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 60px;">**d)** planos plurianuais, diretrizes orçamentárias, orçamento e créditos adicionais e suplementares, ressalvado o previsto no art. 167, § 3º; (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º Medida provisória que implique instituição ou majoração de impostos, exceto os previstos nos arts. 153, I, II, IV, V, e 154, II, só produzirá efeitos no exercício financeiro seguinte se houver sido convertida em lei até o último dia daquele em que foi editada. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º As medidas provisórias, ressalvado o disposto nos §§ 11 e 12 perderão eficácia, desde a edição, se não forem convertidas em lei no prazo de sessenta dias, prorrogável, nos termos do § 7º, uma vez por igual período, devendo o Congresso Nacional disciplinar, por decreto legislativo, as relações jurídicas delas decorrentes. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O prazo a que se refere o § 3º contar-se-á da publicação da medida provisória, suspendendo-se durante os períodos de recesso do Congresso Nacional. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º A deliberação de cada uma das Casas do Congresso Nacional sobre o mérito das medidas provisórias dependerá de juízo prévio sobre o atendimento de seus pressupostos constitucionais. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 6**º Se a medida provisória não for apreciada em até quarenta e cinco dias contados de sua publicação, entrará em regime de urgência, subseqüentemente, em cada uma das Casas do Congresso Nacional, ficando sobrestadas, até que se ultime a votação, todas as demais deliberações legislativas da Casa em que estiver tramitando. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 7**º Prorrogar-se-á uma única vez por igual período a vigência de medida provisória que, no prazo de sessenta dias, contado de sua publicação, não tiver a sua votação encerrada nas duas Casas do Congresso Nacional. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 8**º As medidas provisórias terão sua votação iniciada na Câmara dos Deputados. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 9**º Caberá à comissão mista de Deputados e Senadores examinar as medidas provisórias e sobre elas emitir parecer, antes de serem apreciadas, em sessão separada, pelo plenário de cada uma das Casas do Congresso Nacional. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 10**. É vedada a reedição, na mesma sessão legislativa, de medida provisória que tenha sido rejeitada ou que tenha perdido sua eficácia por decurso de prazo. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 11**. Não editado o decreto legislativo a que se refere o § 3º até sessenta dias após a rejeição ou perda de eficácia de medida provisória, as relações jurídicas constituídas e decorrentes de atos praticados durante sua vigência conservar-se-ão por ela regidas. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 12**. Aprovado projeto de lei de conversão alterando o texto original da medida provisória, esta manter-se-á integralmente em vigor até que seja sancionado ou vetado o projeto. (Incluído pela Emenda Constitucional nº 32, de 2001)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 63**. Não será admitido aumento da despesa prevista:</summary>
<span style="display: block; margin-left: 30px;">**I - **nos projetos de iniciativa exclusiva do Presidente da República, ressalvado o disposto no art. 166, § 3º e § 4º;</span>

<span style="display: block; margin-left: 30px;">**II - **nos projetos sobre organização dos serviços administrativos da Câmara dos Deputados, do Senado Federal, dos Tribunais Federais e do Ministério Público.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 64**. A discussão e votação dos projetos de lei de iniciativa do Presidente da República, do Supremo Tribunal Federal e dos Tribunais Superiores terão início na Câmara dos Deputados.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º O Presidente da República poderá solicitar urgência para apreciação de projetos de sua iniciativa.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Se, no caso do § 1º, a Câmara dos Deputados e o Senado Federal não se manifestarem sobre a proposição, cada qual sucessivamente, em até quarenta e cinco dias, sobrestar-se-ão todas as demais deliberações legislativas da respectiva Casa, com exceção das que tenham prazo constitucional determinado, até que se ultime a votação. (Redação dada pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º A apreciação das emendas do Senado Federal pela Câmara dos Deputados far-se-á no prazo de dez dias, observado quanto ao mais o disposto no parágrafo anterior.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Os prazos do § 2º não correm nos períodos de recesso do Congresso Nacional, nem se aplicam aos projetos de código.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 65**. O projeto de lei aprovado por uma Casa será revisto pela outra, em um só turno de discussão e votação, e enviado à sanção ou promulgação, se a Casa revisora o aprovar, ou arquivado, se o rejeitar.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Sendo o projeto emendado, voltará à Casa iniciadora.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 66**. A Casa na qual tenha sido concluída a votação enviará o projeto de lei ao Presidente da República, que, aquiescendo, o sancionará.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º - Se o Presidente da República considerar o projeto, no todo ou em parte, inconstitucional ou contrário ao interesse público, vetá-lo-á total ou parcialmente, no prazo de quinze dias úteis, contados da data do recebimento, e comunicará, dentro de quarenta e oito horas, ao Presidente do Senado Federal os motivos do veto.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º O veto parcial somente abrangerá texto integral de artigo, de parágrafo, de inciso ou de alínea.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Decorrido o prazo de quinze dias, o silêncio do Presidente da República importará sanção.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O veto será apreciado em sessão conjunta, dentro de trinta dias a contar de seu recebimento, só podendo ser rejeitado pelo voto da maioria absoluta dos Deputados e Senadores. (Redação dada pela Emenda Constitucional nº 76, de 2013)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Se o veto não for mantido, será o projeto enviado, para promulgação, ao Presidente da República.</span>

<span style="display: block; margin-left: 30px;">**§ 6**º Esgotado sem deliberação o prazo estabelecido no § 4º, o veto será colocado na ordem do dia da sessão imediata, sobrestadas as demais proposições, até sua votação final. (Redação dada pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 30px;">**§ 7**º Se a lei não for promulgada dentro de quarenta e oito horas pelo Presidente da República, nos casos dos § 3º e § 5º, o Presidente do Senado a promulgará, e, se este não o fizer em igual prazo, caberá ao Vice-Presidente do Senado fazê-lo.</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 67**. A matéria constante de projeto de lei rejeitado somente poderá constituir objeto de novo projeto, na mesma sessão legislativa, mediante proposta da maioria absoluta dos membros de qualquer das Casas do Congresso Nacional.</span>

<details open style="margin-left: 0px;">
<summary>**Art. 68**. As leis delegadas serão elaboradas pelo Presidente da República, que deverá solicitar a delegação ao Congresso Nacional.</summary>
<details open style="margin-left: 30px;">
<summary>**§ 1**º Não serão objeto de delegação os atos de competência exclusiva do Congresso Nacional, os de competência privativa da Câmara dos Deputados ou do Senado Federal, a matéria reservada à lei complementar, nem a legislação sobre:</summary>
<span style="display: block; margin-left: 60px;">**I - **organização do Poder Judiciário e do Ministério Público, a carreira e a garantia de seus membros;</span>

<span style="display: block; margin-left: 60px;">**II - **nacionalidade, cidadania, direitos individuais, políticos e eleitorais;</span>

<span style="display: block; margin-left: 60px;">**III - **planos plurianuais, diretrizes orçamentárias e orçamentos.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º A delegação ao Presidente da República terá a forma de resolução do Congresso Nacional, que especificará seu conteúdo e os termos de seu exercício.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Se a resolução determinar a apreciação do projeto pelo Congresso Nacional, este a fará em votação única, vedada qualquer emenda.</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 69**. As leis complementares serão aprovadas por maioria absoluta.</span>

### SEÇÃO IX - DA FISCALIZAÇÃO CONTÁBIL, FINANCEIRA E ORÇAMENTÁRIA

<details open style="margin-left: 0px;">
<summary>**Art. 70**. A fiscalização contábil, financeira, orçamentária, operacional e patrimonial da União e das entidades da administração direta e indireta, quanto à legalidade, legitimidade, economicidade, aplicação das subvenções e renúncia de receitas, será exercida pelo Congresso Nacional, mediante controle externo, e pelo sistema de controle interno de cada Poder.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Prestará contas qualquer pessoa física ou jurídica, pública ou privada, que utilize, arrecade, guarde, gerencie ou administre dinheiros, bens e valores públicos ou pelos quais a União responda, ou que, em nome desta, assuma obrigações de natureza pecuniária. (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 71**. O controle externo, a cargo do Congresso Nacional, será exercido com o auxílio do Tribunal de Contas da União, ao qual compete:</summary>
<span style="display: block; margin-left: 30px;">**I - **apreciar as contas prestadas anualmente pelo Presidente da República, mediante parecer prévio que deverá ser elaborado em sessenta dias a contar de seu recebimento;</span>

<span style="display: block; margin-left: 30px;">**II - **julgar as contas dos administradores e demais responsáveis por dinheiros, bens e valores públicos da administração direta e indireta, incluídas as fundações e sociedades instituídas e mantidas pelo Poder Público federal, e as contas daqueles que derem causa a perda, extravio ou outra irregularidade de que resulte prejuízo ao erário público;</span>

<span style="display: block; margin-left: 30px;">**III - **apreciar, para fins de registro, a legalidade dos atos de admissão de pessoal, a qualquer título, na administração direta e indireta, incluídas as fundações instituídas e mantidas pelo Poder Público, excetuadas as nomeações para cargo de provimento em comissão, bem como a das concessões de aposentadorias, reformas e pensões, ressalvadas as melhorias posteriores que não alterem o fundamento legal do ato concessório;</span>

<span style="display: block; margin-left: 30px;">**IV - **realizar, por iniciativa própria, da Câmara dos Deputados, do Senado Federal, de Comissão técnica ou de inquérito, inspeções e auditorias de natureza contábil, financeira, orçamentária, operacional e patrimonial, nas unidades administrativas dos Poderes Legislativo, Executivo e Judiciário, e demais entidades referidas no inciso II;</span>

<span style="display: block; margin-left: 30px;">**V - **fiscalizar as contas nacionais das empresas supranacionais de cujo capital social a União participe, de forma direta ou indireta, nos termos do tratado constitutivo;</span>

<span style="display: block; margin-left: 30px;">**VI - **fiscalizar a aplicação de quaisquer recursos repassados pela União mediante convênio, acordo, ajuste ou outros instrumentos congêneres, a Estado, ao Distrito Federal ou a Município;</span>

<span style="display: block; margin-left: 30px;">**VII - **prestar as informações solicitadas pelo Congresso Nacional, por qualquer de suas Casas, ou por qualquer das respectivas Comissões, sobre a fiscalização contábil, financeira, orçamentária, operacional e patrimonial e sobre resultados de auditorias e inspeções realizadas;</span>

<span style="display: block; margin-left: 30px;">**VIII - **aplicar aos responsáveis, em caso de ilegalidade de despesa ou irregularidade de contas, as sanções previstas em lei, que estabelecerá, entre outras cominações, multa proporcional ao dano causado ao erário;</span>

<span style="display: block; margin-left: 30px;">**IX - **assinar prazo para que o órgão ou entidade adote as providências necessárias ao exato cumprimento da lei, se verificada ilegalidade;</span>

<span style="display: block; margin-left: 30px;">**X - **sustar, se não atendido, a execução do ato impugnado, comunicando a decisão à Câmara dos Deputados e ao Senado Federal;</span>

<span style="display: block; margin-left: 30px;">**XI - **representar ao Poder competente sobre irregularidades ou abusos apurados.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º No caso de contrato, o ato de sustação será adotado diretamente pelo Congresso Nacional, que solicitará, de imediato, ao Poder Executivo as medidas cabíveis.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Se o Congresso Nacional ou o Poder Executivo, no prazo de noventa dias, não efetivar as medidas previstas no parágrafo anterior, o Tribunal decidirá a respeito.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º As decisões do Tribunal de que resulte imputação de débito ou multa terão eficácia de título executivo.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O Tribunal encaminhará ao Congresso Nacional, trimestral e anualmente, relatório de suas atividades.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 72**. A Comissão mista permanente a que se refere o art. 166, §1º, diante de indícios de despesas não autorizadas, ainda que sob a forma de investimentos não programados ou de subsídios não aprovados, poderá solicitar à autoridade governamental responsável que, no prazo de cinco dias, preste os esclarecimentos necessários.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Não prestados os esclarecimentos, ou considerados estes insuficientes, a Comissão solicitará ao Tribunal pronunciamento conclusivo sobre a matéria, no prazo de trinta dias.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Entendendo o Tribunal irregular a despesa, a Comissão, se julgar que o gasto possa causar dano irreparável ou grave lesão à economia pública, proporá ao Congresso Nacional sua sustação.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 73**. O Tribunal de Contas da União, integrado por nove Ministros, tem sede no Distrito Federal, quadro próprio de pessoal e jurisdição em todo o território nacional, exercendo, no que couber, as atribuições previstas no art. 96. .</summary>
<details open style="margin-left: 30px;">
<summary>**§ 1**º Os Ministros do Tribunal de Contas da União serão nomeados dentre brasileiros que satisfaçam os seguintes requisitos:</summary>
<span style="display: block; margin-left: 60px;">**I - **mais de trinta e cinco e menos de setenta anos de idade; (Redação dada pela Emenda Constitucional nº 122, de 2022)</span>

<span style="display: block; margin-left: 60px;">**II - **idoneidade moral e reputação ilibada;</span>

<span style="display: block; margin-left: 60px;">**III - **notórios conhecimentos jurídicos, contábeis, econômicos e financeiros ou de administração pública;</span>

<span style="display: block; margin-left: 60px;">**IV - **mais de dez anos de exercício de função ou de efetiva atividade profissional que exija os conhecimentos mencionados no inciso anterior.</span>

</details>

<details open style="margin-left: 30px;">
<summary>**§ 2**º Os Ministros do Tribunal de Contas da União serão escolhidos:</summary>
<span style="display: block; margin-left: 60px;">**I - **um terço pelo Presidente da República, com aprovação do Senado Federal, sendo dois alternadamente dentre auditores e membros do Ministério Público junto ao Tribunal, indicados em lista tríplice pelo Tribunal, segundo os critérios de antigüidade e merecimento;</span>

<span style="display: block; margin-left: 60px;">**II - **dois terços pelo Congresso Nacional.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 3**° Os Ministros do Tribunal de Contas da União terão as mesmas garantias, prerrogativas, impedimentos, vencimentos e vantagens dos Ministros do Superior Tribunal de Justiça, aplicando-se-lhes, quanto à aposentadoria e pensão, as normas constantes do art. 40. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O auditor, quando em substituição a Ministro, terá as mesmas garantias e impedimentos do titular e, quando no exercício das demais atribuições da judicatura, as de juiz de Tribunal Regional Federal.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 74**. Os Poderes Legislativo, Executivo e Judiciário manterão, de forma integrada, sistema de controle interno com a finalidade de:</summary>
<span style="display: block; margin-left: 30px;">**I - **avaliar o cumprimento das metas previstas no plano plurianual, a execução dos programas de governo e dos orçamentos da União;</span>

<span style="display: block; margin-left: 30px;">**II - **comprovar a legalidade e avaliar os resultados, quanto à eficácia e eficiência, da gestão orçamentária, financeira e patrimonial nos órgãos e entidades da administração federal, bem como da aplicação de recursos públicos por entidades de direito privado;</span>

<span style="display: block; margin-left: 30px;">**III - **exercer o controle das operações de crédito, avais e garantias, bem como dos direitos e haveres da União;</span>

<span style="display: block; margin-left: 30px;">**IV - **apoiar o controle externo no exercício de sua missão institucional.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º Os responsáveis pelo controle interno, ao tomarem conhecimento de qualquer irregularidade ou ilegalidade, dela darão ciência ao Tribunal de Contas da União, sob pena de responsabilidade solidária.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Qualquer cidadão, partido político, associação ou sindicato é parte legítima para, na forma da lei, denunciar irregularidades ou ilegalidades perante o Tribunal de Contas da União.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 75**. As normas estabelecidas nesta seção aplicam-se, no que couber, à organização, composição e fiscalização dos Tribunais de Contas dos Estados e do Distrito Federal, bem como dos Tribunais e Conselhos de Contas dos Municípios.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. As Constituições estaduais disporão sobre os Tribunais de Contas respectivos, que serão integrados por sete Conselheiros.</span>

</details>

## CAPÍTULO II - DO PODER EXECUTIVO

### SEÇÃO I - DO PRESIDENTE E DO VICE-PRESIDENTE DA REPÚBLICA

<span style="display: block; margin-left: 0px;">**Art. 76**. O Poder Executivo é exercido pelo Presidente da República, auxiliado pelos Ministros de Estado.</span>

<details open style="margin-left: 0px;">
<summary>**Art. 77**. A eleição do Presidente e do Vice-Presidente da República realizar-se-á, simultaneamente, no primeiro domingo de outubro, em primeiro turno, e no último domingo de outubro, em segundo turno, se houver, do ano anterior ao do término do mandato presidencial vigente. (Redação dada pela Emenda Constitucional nº 16, de 1997)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º A eleição do Presidente da República importará a do Vice-Presidente com ele registrado.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Será considerado eleito Presidente o candidato que, registrado por partido político, obtiver a maioria absoluta de votos, não computados os em branco e os nulos.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Se nenhum candidato alcançar maioria absoluta na primeira votação, far-se-á nova eleição em até vinte dias após a proclamação do resultado, concorrendo os dois candidatos mais votados e considerando-se eleito aquele que obtiver a maioria dos votos válidos.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Se, antes de realizado o segundo turno, ocorrer morte, desistência ou impedimento legal de candidato, convocar-se-á, dentre os remanescentes, o de maior votação.</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Se, na hipótese dos parágrafos anteriores, remanescer, em segundo lugar, mais de um candidato com a mesma votação, qualificar-se-á o mais idoso.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 78**. O Presidente e o Vice-Presidente da República tomarão posse em sessão do Congresso Nacional, prestando o compromisso de manter, defender e cumprir a Constituição, observar as leis, promover o bem geral do povo brasileiro, sustentar a união, a integridade e a independência do Brasil.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Se, decorridos dez dias da data fixada para a posse, o Presidente ou o Vice-Presidente, salvo motivo de força maior, não tiver assumido o cargo, este será declarado vago.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 79**. Substituirá o Presidente, no caso de impedimento, e suceder- lhe-á, no de vaga, o Vice-Presidente.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. O Vice-Presidente da República, além de outras atribuições que lhe forem conferidas por lei complementar, auxiliará o Presidente, sempre que por ele convocado para missões especiais.</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 80**. Em caso de impedimento do Presidente e do Vice-Presidente, ou vacância dos respectivos cargos, serão sucessivamente chamados ao exercício da Presidência o Presidente da Câmara dos Deputados, o do Senado Federal e o do Supremo Tribunal Federal.</span>

<details open style="margin-left: 0px;">
<summary>**Art. 81**. Vagando os cargos de Presidente e Vice-Presidente da República, far-se-á eleição noventa dias depois de aberta a última vaga.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º - Ocorrendo a vacância nos últimos dois anos do período presidencial, a eleição para ambos os cargos será feita trinta dias depois da última vaga, pelo Congresso Nacional, na forma da lei.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º - Em qualquer dos casos, os eleitos deverão completar o período de seus antecessores.</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 82**. O mandato do Presidente da República é de 4 (quatro) anos e terá início em 5 de janeiro do ano seguinte ao de sua eleição. (Redação dada pela Emenda Constitucional nº 111, de 2021)</span>

<span style="display: block; margin-left: 0px;">**Art. 83**. O Presidente e o Vice-Presidente da República não poderão, sem licença do Congresso Nacional, ausentar-se do País por período superior a quinze dias, sob pena de perda do cargo.</span>

### SEÇÃO II - Das Atribuições do Presidente da República

<details open style="margin-left: 0px;">
<summary>**Art. 84**. Compete privativamente ao Presidente da República:</summary>
<span style="display: block; margin-left: 30px;">**I - **nomear e exonerar os Ministros de Estado;</span>

<span style="display: block; margin-left: 30px;">**II - **exercer, com o auxílio dos Ministros de Estado, a direção superior da administração federal;</span>

<span style="display: block; margin-left: 30px;">**III - **iniciar o processo legislativo, na forma e nos casos previstos nesta Constituição;</span>

<span style="display: block; margin-left: 30px;">**IV - **sancionar, promulgar e fazer publicar as leis, bem como expedir decretos e regulamentos para sua fiel execução;</span>

<details open style="margin-left: 30px;">
<summary>**V - **vetar projetos de lei, total ou parcialmente;</summary>
<span style="display: block; margin-left: 60px;">**a)** organização e funcionamento da administração federal, quando não implicar aumento de despesa nem criação ou extinção de órgãos públicos; (Incluída pela Emenda Constitucional nº 32, de 2001)</span>

<span style="display: block; margin-left: 60px;">**b)** extinção de funções ou cargos públicos, quando vagos; (Incluída pela Emenda Constitucional nº 32, de 2001)</span>

</details>

<span style="display: block; margin-left: 30px;">**VII - **manter relações com Estados estrangeiros e acreditar seus representantes diplomáticos;</span>

<span style="display: block; margin-left: 30px;">**VIII - **celebrar tratados, convenções e atos internacionais, sujeitos a referendo do Congresso Nacional;</span>

<span style="display: block; margin-left: 30px;">**IX - **decretar o estado de defesa e o estado de sítio;</span>

<span style="display: block; margin-left: 30px;">**X - **decretar e executar a intervenção federal;</span>

<span style="display: block; margin-left: 30px;">**XI - **remeter mensagem e plano de governo ao Congresso Nacional por ocasião da abertura da sessão legislativa, expondo a situação do País e solicitando as providências que julgar necessárias;</span>

<span style="display: block; margin-left: 30px;">**XII - **conceder indulto e comutar penas, com audiência, se necessário, dos órgãos instituídos em lei;</span>

<span style="display: block; margin-left: 30px;">**XIII - **exercer o comando supremo das Forças Armadas, nomear os Comandantes da Marinha, do Exército e da Aeronáutica, promover seus oficiais-generais e nomeá-los para os cargos que lhes são privativos; (Redação dada pela Emenda Constitucional nº 23, de 1999)</span>

<span style="display: block; margin-left: 30px;">**XIV - **nomear, após aprovação pelo Senado Federal, os Ministros do Supremo Tribunal Federal e dos Tribunais Superiores, os Governadores de Territórios, o Procurador-Geral da República, o presidente e os diretores do banco central e outros servidores, quando determinado em lei;</span>

<span style="display: block; margin-left: 30px;">**XV - **nomear, observado o disposto no art. 73, os Ministros do Tribunal de Contas da União;</span>

<span style="display: block; margin-left: 30px;">**XVI - **nomear os magistrados, nos casos previstos nesta Constituição, e o Advogado-Geral da União;</span>

<span style="display: block; margin-left: 30px;">**XVII - **nomear membros do Conselho da República, nos termos do art. 89, VII;</span>

<span style="display: block; margin-left: 30px;">**XVIII - **convocar e presidir o Conselho da República e o Conselho de Defesa Nacional;</span>

<span style="display: block; margin-left: 30px;">**XIX - **declarar guerra, no caso de agressão estrangeira, autorizado pelo Congresso Nacional ou referendado por ele, quando ocorrida no intervalo das sessões legislativas, e, nas mesmas condições, decretar, total ou parcialmente, a mobilização nacional;</span>

<span style="display: block; margin-left: 30px;">**XX - **celebrar a paz, autorizado ou com o referendo do Congresso Nacional;</span>

<span style="display: block; margin-left: 30px;">**XXI - **conferir condecorações e distinções honoríficas;</span>

<span style="display: block; margin-left: 30px;">**XXII - **permitir, nos casos previstos em lei complementar, que forças estrangeiras transitem pelo território nacional ou nele permaneçam temporariamente;</span>

<span style="display: block; margin-left: 30px;">**XXIII - **enviar ao Congresso Nacional o plano plurianual, o projeto de lei de diretrizes orçamentárias e as propostas de orçamento previstos nesta Constituição;</span>

<span style="display: block; margin-left: 30px;">**XXIV - **prestar, anualmente, ao Congresso Nacional, dentro de sessenta dias após a abertura da sessão legislativa, as contas referentes ao exercício anterior;</span>

<span style="display: block; margin-left: 30px;">**XXV - **prover e extinguir os cargos públicos federais, na forma da lei;</span>

<span style="display: block; margin-left: 30px;">**XXVI - **editar medidas provisórias com força de lei, nos termos do art. 62;</span>

<span style="display: block; margin-left: 30px;">**XXVII - **exercer outras atribuições previstas nesta Constituição.</span>

<span style="display: block; margin-left: 30px;">**XXVIII - **propor ao Congresso Nacional a decretação do estado de calamidade pública de âmbito nacional previsto nos arts. 167-B, 167-C, 167-D, 167-E, 167-F e 167-G desta Constituição. (Incluído pela Emenda Constitucional nº 109, de 2021)</span>

<span style="display: block; margin-left: 30px;">**Parágrafo único**. O Presidente da República poderá delegar as atribuições mencionadas nos incisos VI, XII e XXV, primeira parte, aos Ministros de Estado, ao Procurador-Geral da República ou ao Advogado-Geral da União, que observarão os limites traçados nas respectivas delegações.</span>

</details>

### SEÇÃO III - Da Responsabilidade do Presidente da República

<details open style="margin-left: 0px;">
<summary>**Art. 85**. São crimes de responsabilidade os atos do Presidente da República que atentem contra a Constituição Federal e, especialmente, contra:</summary>
<span style="display: block; margin-left: 30px;">**I - **a existência da União;</span>

<span style="display: block; margin-left: 30px;">**II - **o livre exercício do Poder Legislativo, do Poder Judiciário, do Ministério Público e dos Poderes constitucionais das unidades da Federação;</span>

<span style="display: block; margin-left: 30px;">**III - **o exercício dos direitos políticos, individuais e sociais;</span>

<span style="display: block; margin-left: 30px;">**IV - **a segurança interna do País;</span>

<span style="display: block; margin-left: 30px;">**V - **a probidade na administração;</span>

<span style="display: block; margin-left: 30px;">**VI - **a lei orçamentária;</span>

<span style="display: block; margin-left: 30px;">**VII - **o cumprimento das leis e das decisões judiciais.</span>

<span style="display: block; margin-left: 30px;">**Parágrafo único**. Esses crimes serão definidos em lei especial, que estabelecerá as normas de processo e julgamento.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 86**. Admitida a acusação contra o Presidente da República, por dois terços da Câmara dos Deputados, será ele submetido a julgamento perante o Supremo Tribunal Federal, nas infrações penais comuns, ou perante o Senado Federal, nos crimes de responsabilidade.</summary>
<details open style="margin-left: 30px;">
<summary>**§ 1**º O Presidente ficará suspenso de suas funções:</summary>
<span style="display: block; margin-left: 60px;">**I - **nas infrações penais comuns, se recebida a denúncia ou queixa-crime pelo Supremo Tribunal Federal;</span>

<span style="display: block; margin-left: 60px;">**II - **nos crimes de responsabilidade, após a instauração do processo pelo Senado Federal.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º Se, decorrido o prazo de cento e oitenta dias, o julgamento não estiver concluído, cessará o afastamento do Presidente, sem prejuízo do regular prosseguimento do processo.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Enquanto não sobrevier sentença condenatória, nas infrações comuns, o Presidente da República não estará sujeito a prisão.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O Presidente da República, na vigência de seu mandato, não pode ser responsabilizado por atos estranhos ao exercício de suas funções.</span>

</details>

### SEÇÃO IV - DOS MINISTROS DE ESTADO

<details open style="margin-left: 0px;">
<summary>**Art. 87**. Os Ministros de Estado serão escolhidos dentre brasileiros maiores de vinte e um anos e no exercício dos direitos políticos.</summary>
<details open style="margin-left: 30px;">
<summary>**Parágrafo único**. Compete ao Ministro de Estado, além de outras atribuições estabelecidas nesta Constituição e na lei:</summary>
<span style="display: block; margin-left: 60px;">**I - **exercer a orientação, coordenação e supervisão dos órgãos e entidades da administração federal na área de sua competência e referendar os atos e decretos assinados pelo Presidente da República;</span>

<span style="display: block; margin-left: 60px;">**II - **expedir instruções para a execução das leis, decretos e regulamentos;</span>

<span style="display: block; margin-left: 60px;">**III - **apresentar ao Presidente da República relatório anual de sua gestão no Ministério;</span>

<span style="display: block; margin-left: 60px;">**IV - **praticar os atos pertinentes às atribuições que lhe forem outorgadas ou delegadas pelo Presidente da República.</span>

</details>

</details>

<span style="display: block; margin-left: 0px;">**Art. 88**. A lei disporá sobre a criação e extinção de Ministérios e órgãos da administração pública. (Redação dada pela Emenda Constitucional nº 32, de 2001)</span>

### SEÇÃO V - DO CONSELHO DA REPÚBLICA E DO CONSELHO DE DEFESA NACIONAL

#### SUBSEÇÃO I - Do Conselho da República

<details open style="margin-left: 0px;">
<summary>**Art. 89**. O Conselho da República é órgão superior de consulta do Presidente da República, e dele participam:</summary>
<span style="display: block; margin-left: 30px;">**I - **o Vice-Presidente da República;</span>

<span style="display: block; margin-left: 30px;">**II - **o Presidente da Câmara dos Deputados;</span>

<span style="display: block; margin-left: 30px;">**III - **o Presidente do Senado Federal;</span>

<span style="display: block; margin-left: 30px;">**IV - **os líderes da maioria e da minoria na Câmara dos Deputados;</span>

<span style="display: block; margin-left: 30px;">**V - **os líderes da maioria e da minoria no Senado Federal;</span>

<span style="display: block; margin-left: 30px;">**VI - **o Ministro da Justiça;</span>

<span style="display: block; margin-left: 30px;">**VII - **seis cidadãos brasileiros natos, com mais de trinta e cinco anos de idade, sendo dois nomeados pelo Presidente da República, dois eleitos pelo Senado Federal e dois eleitos pela Câmara dos Deputados, todos com mandato de três anos, vedada a recondução.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 90**. Compete ao Conselho da República pronunciar-se sobre:</summary>
<span style="display: block; margin-left: 30px;">**I - **intervenção federal, estado de defesa e estado de sítio;</span>

<span style="display: block; margin-left: 30px;">**II - **as questões relevantes para a estabilidade das instituições democráticas.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º O Presidente da República poderá convocar Ministro de Estado para participar da reunião do Conselho, quando constar da pauta questão relacionada com o respectivo Ministério.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º A lei regulará a organização e o funcionamento do Conselho da República. (Vide Lei nº 8.041, de 1990)</span>

</details>

#### SUBSEÇÃO II - Do Conselho de Defesa Nacional

<details open style="margin-left: 0px;">
<summary>**Art. 91**. O Conselho de Defesa Nacional é órgão de consulta do Presidente da República nos assuntos relacionados com a soberania nacional e a defesa do Estado democrático, e dele participam como membros natos:</summary>
<span style="display: block; margin-left: 30px;">**I - **o Vice-Presidente da República;</span>

<span style="display: block; margin-left: 30px;">**II - **o Presidente da Câmara dos Deputados;</span>

<span style="display: block; margin-left: 30px;">**III - **o Presidente do Senado Federal;</span>

<span style="display: block; margin-left: 30px;">**IV - **o Ministro da Justiça;</span>

<span style="display: block; margin-left: 30px;">**V - **o Ministro de Estado da Defesa; (Redação dada pela Emenda Constitucional nº 23, de 1999)</span>

<span style="display: block; margin-left: 30px;">**VI - **o Ministro das Relações Exteriores;</span>

<span style="display: block; margin-left: 30px;">**VII - **o Ministro do Planejamento.</span>

<span style="display: block; margin-left: 30px;">**VIII - **os Comandantes da Marinha, do Exército e da Aeronáutica. (Incluído pela Emenda Constitucional nº 23, de 1999)</span>

<details open style="margin-left: 30px;">
<summary>**§ 1**º Compete ao Conselho de Defesa Nacional:</summary>
<span style="display: block; margin-left: 60px;">**I - **opinar nas hipóteses de declaração de guerra e de celebração da paz, nos termos desta Constituição;</span>

<span style="display: block; margin-left: 60px;">**II - **opinar sobre a decretação do estado de defesa, do estado de sítio e da intervenção federal;</span>

<span style="display: block; margin-left: 60px;">**III - **propor os critérios e condições de utilização de áreas indispensáveis à segurança do território nacional e opinar sobre seu efetivo uso, especialmente na faixa de fronteira e nas relacionadas com a preservação e a exploração dos recursos naturais de qualquer tipo;</span>

<span style="display: block; margin-left: 60px;">**IV - **estudar, propor e acompanhar o desenvolvimento de iniciativas necessárias a garantir a independência nacional e a defesa do Estado democrático.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º A lei regulará a organização e o funcionamento do Conselho de Defesa Nacional. (Vide Lei nº 8.183, de 1991)</span>

</details>

## CAPÍTULO III - DO PODER JUDICIÁRIO

### SEÇÃO I - DISPOSIÇÕES GERAIS

<details open style="margin-left: 0px;">
<summary>**Art. 92**. São órgãos do Poder Judiciário:</summary>
<span style="display: block; margin-left: 30px;">**I - **o Supremo Tribunal Federal;</span>

<span style="display: block; margin-left: 30px;">**II - **o Superior Tribunal de Justiça;</span>

<span style="display: block; margin-left: 30px;">**III - **os Tribunais Regionais Federais e Juízes Federais;</span>

<span style="display: block; margin-left: 30px;">**IV - **os Tribunais e Juízes do Trabalho;</span>

<span style="display: block; margin-left: 30px;">**V - **os Tribunais e Juízes Eleitorais;</span>

<span style="display: block; margin-left: 30px;">**VI - **os Tribunais e Juízes Militares;</span>

<span style="display: block; margin-left: 30px;">**VII - **os Tribunais e Juízes dos Estados e do Distrito Federal e Territórios.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º O Supremo Tribunal Federal, o Conselho Nacional de Justiça e os Tribunais Superiores têm sede na Capital Federal. (Incluído pela Emenda Constitucional nº 45, de 2004) (Vide ADIN 3392)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º O Supremo Tribunal Federal e os Tribunais Superiores têm jurisdição em todo o território nacional. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 93**. Lei complementar, de iniciativa do Supremo Tribunal Federal, disporá sobre o Estatuto da Magistratura, observados os seguintes princípios:</summary>
<span style="display: block; margin-left: 30px;">**I - **ingresso na carreira, cujo cargo inicial será o de juiz substituto, mediante concurso público de provas e títulos, com a participação da Ordem dos Advogados do Brasil em todas as fases, exigindo-se do bacharel em direito, no mínimo, três anos de atividade jurídica e obedecendo-se, nas nomeações, à ordem de classificação; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<details open style="margin-left: 30px;">
<summary>**II - **promoção de entrância para entrância, alternadamente, por antigüidade e merecimento, atendidas as seguintes normas:</summary>
<span style="display: block; margin-left: 60px;">**a)** é obrigatória a promoção do juiz que figure por três vezes consecutivas ou cinco alternadas em lista de merecimento;</span>

<span style="display: block; margin-left: 60px;">**b)** a promoção por merecimento pressupõe dois anos de exercício na respectiva entrância e integrar o juiz a primeira quinta parte da lista de antigüidade desta, salvo se não houver com tais requisitos quem aceite o lugar vago;</span>

<span style="display: block; margin-left: 60px;">**c)** aferição do merecimento conforme o desempenho e pelos critérios objetivos de produtividade e presteza no exercício da jurisdição e pela freqüência e aproveitamento em cursos oficiais ou reconhecidos de aperfeiçoamento; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**d)** na apuração de antigüidade, o tribunal somente poderá recusar o juiz mais antigo pelo voto fundamentado de dois terços de seus membros, conforme procedimento próprio, e assegurada ampla defesa, repetindo-se a votação até fixar-se a indicação; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**e)** não será promovido o juiz que, injustificadamente, retiver autos em seu poder além do prazo legal, não podendo devolvê-los ao cartório sem o devido despacho ou decisão; (Incluída pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<span style="display: block; margin-left: 30px;">**V - **o subsídio dos Ministros dos Tribunais Superiores corresponderá a noventa e cinco por cento do subsídio mensal fixado para os Ministros do Supremo Tribunal Federal e os subsídios dos demais magistrados serão fixados em lei e escalonados, em nível federal e estadual, conforme as respectivas categorias da estrutura judiciária nacional, não podendo a diferença entre uma e outra ser superior a dez por cento ou inferior a cinco por cento, nem exceder a noventa e cinco por cento do subsídio mensal dos Ministros dos Tribunais Superiores, obedecido, em qualquer caso, o disposto nos arts. 37, XI, e 39, § 4º; (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;">**VI - **a aposentadoria dos magistrados e a pensão de seus dependentes observarão o disposto no art. 40; (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;">**VIII - **o ato de remoção ou de disponibilidade do magistrado, por interesse público, fundar-se-á em decisão por voto da maioria absoluta do respectivo tribunal ou do Conselho Nacional de Justiça, assegurada ampla defesa; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 94**. Um quinto dos lugares dos Tribunais Regionais Federais, dos Tribunais dos Estados, e do Distrito Federal e Territórios será composto de membros, do Ministério Público, com mais de dez anos de carreira, e de advogados de notório saber jurídico e de reputação ilibada, com mais de dez anos de efetiva atividade profissional, indicados em lista sêxtupla pelos órgãos de representação das respectivas classes.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Recebidas as indicações, o tribunal formará lista tríplice, enviando-a ao Poder Executivo, que, nos vinte dias subseqüentes, escolherá um de seus integrantes para nomeação.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 95**. Os juízes gozam das seguintes garantias:</summary>
<span style="display: block; margin-left: 30px;">**I - **vitaliciedade, que, no primeiro grau, só será adquirida após dois anos de exercício, dependendo a perda do cargo, nesse período, de deliberação do tribunal a que o juiz estiver vinculado, e, nos demais casos, de sentença judicial transitada em julgado;</span>

<span style="display: block; margin-left: 30px;">**II - **inamovibilidade, salvo por motivo de interesse público, na forma do art. 93, VIII;</span>

<span style="display: block; margin-left: 30px;">**III - **irredutibilidade de subsídio, ressalvado o disposto nos arts. 37, X e XI, 39, § 4º, 150, II, 153, III, e 153, § 2º, I. (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<details open style="margin-left: 30px;">
<summary>**Parágrafo único**. Aos juízes é vedado:</summary>
<span style="display: block; margin-left: 60px;">**I - **exercer, ainda que em disponibilidade, outro cargo ou função, salvo uma de magistério;</span>

<span style="display: block; margin-left: 60px;">**II - **receber, a qualquer título ou pretexto, custas ou participação em processo;</span>

<span style="display: block; margin-left: 60px;">**III - **dedicar-se à atividade político-partidária.</span>

</details>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 96**. Compete privativamente:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **aos tribunais:</summary>
<span style="display: block; margin-left: 60px;">**a)** eleger seus órgãos diretivos e elaborar seus regimentos internos, com observância das normas de processo e das garantias processuais das partes, dispondo sobre a competência e o funcionamento dos respectivos órgãos jurisdicionais e administrativos;</span>

<span style="display: block; margin-left: 60px;">**b)** organizar suas secretarias e serviços auxiliares e os dos juízos que lhes forem vinculados, velando pelo exercício da atividade correicional respectiva;</span>

<span style="display: block; margin-left: 60px;">**c)** prover, na forma prevista nesta Constituição, os cargos de juiz de carreira da respectiva jurisdição;</span>

<span style="display: block; margin-left: 60px;">**d)** propor a criação de novas varas judiciárias;</span>

<span style="display: block; margin-left: 60px;">**e)** prover, por concurso público de provas, ou de provas e títulos, obedecido o disposto no art. 169, parágrafo único, os cargos necessários à administração da Justiça, exceto os de confiança assim definidos em lei;</span>

<span style="display: block; margin-left: 60px;">**f)** conceder licença, férias e outros afastamentos a seus membros e aos juízes e servidores que lhes forem imediatamente vinculados;</span>

</details>

<details open style="margin-left: 30px;">
<summary>**II - **ao Supremo Tribunal Federal, aos Tribunais Superiores e aos Tribunais de Justiça propor ao Poder Legislativo respectivo, observado o disposto no art. 169:</summary>
<span style="display: block; margin-left: 60px;">**a)** a alteração do número de membros dos tribunais inferiores;</span>

<span style="display: block; margin-left: 60px;">**b)** a criação e a extinção de cargos e a remuneração dos seus serviços auxiliares e dos juízos que lhes forem vinculados, bem como a fixação do subsídio de seus membros e dos juízes, inclusive dos tribunais inferiores, onde houver; (Redação dada pela Emenda Constitucional nº 41, 19.12.2003)</span>

<span style="display: block; margin-left: 60px;">**c)** a criação ou extinção dos tribunais inferiores;</span>

<span style="display: block; margin-left: 60px;">**d)** a alteração da organização e da divisão judiciárias;</span>

</details>

<span style="display: block; margin-left: 30px;">**III - **aos Tribunais de Justiça julgar os juízes estaduais e do Distrito Federal e Territórios, bem como os membros do Ministério Público, nos crimes comuns e de responsabilidade, ressalvada a competência da Justiça Eleitoral.</span>

<span style="display: block; margin-left: 30px;">**Parágrafo único**. Nos Tribunais de Justiça compostos de mais de 170 (cento e setenta) desembargadores em efetivo exercício, a eleição para os cargos diretivos, de que trata a alínea "a" do inciso I docaputdeste artigo, será realizada entre os membros do tribunal pleno, por maioria absoluta e por voto direto e secreto, para um mandato de 2 (dois) anos, vedada mais de 1 (uma) recondução sucessiva. (Incluído pela Emenda Constitucional nº 134, de 2024)</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 97**. Somente pelo voto da maioria absoluta de seus membros ou dos membros do respectivo órgão especial poderão os tribunais declarar a inconstitucionalidade de lei ou ato normativo do Poder Público. (Vide Lei nº 13.105, de 2015) (Vigência)</span>

<details open style="margin-left: 0px;">
<summary>**Art. 98**. A União, no Distrito Federal e nos Territórios, e os Estados criarão:</summary>
<span style="display: block; margin-left: 30px;">**I - **juizados especiais, providos por juízes togados, ou togados e leigos, competentes para a conciliação, o julgamento e a execução de causas cíveis de menor complexidade e infrações penais de menor potencial ofensivo, mediante os procedimentos oral e sumaríssimo, permitidos, nas hipóteses previstas em lei, a transação e o julgamento de recursos por turmas de juízes de primeiro grau;</span>

<span style="display: block; margin-left: 30px;">**II - **justiça de paz, remunerada, composta de cidadãos eleitos pelo voto direto, universal e secreto, com mandato de quatro anos e competência para, na forma da lei, celebrar casamentos, verificar, de ofício ou em face de impugnação apresentada, o processo de habilitação e exercer atribuições conciliatórias, sem caráter jurisdicional, além de outras previstas na legislação.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º Lei federal disporá sobre a criação de juizados especiais no âmbito da Justiça Federal. (Renumerado pela Emenda Constitucional nº 45, de 2004) (Vide ADIN 3392)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º As custas e emolumentos serão destinados exclusivamente ao custeio dos serviços afetos às atividades específicas da Justiça. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 99**. Ao Poder Judiciário é assegurada autonomia administrativa e financeira.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os tribunais elaborarão suas propostas orçamentárias dentro dos limites estipulados conjuntamente com os demais Poderes na lei de diretrizes orçamentárias.</span>

<details open style="margin-left: 30px;">
<summary>**§ 2**º O encaminhamento da proposta, ouvidos os outros tribunais interessados, compete:</summary>
<span style="display: block; margin-left: 60px;">**I - **no âmbito da União, aos Presidentes do Supremo Tribunal Federal e dos Tribunais Superiores, com a aprovação dos respectivos tribunais;</span>

<span style="display: block; margin-left: 60px;">**II - **no âmbito dos Estados e no do Distrito Federal e Territórios, aos Presidentes dos Tribunais de Justiça, com a aprovação dos respectivos tribunais.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 3**º Se os órgãos referidos no § 2º não encaminharem as respectivas propostas orçamentárias dentro do prazo estabelecido na lei de diretrizes orçamentárias, o Poder Executivo considerará, para fins de consolidação da proposta orçamentária anual, os valores aprovados na lei orçamentária vigente, ajustados de acordo com os limites estipulados na forma do § 1º deste artigo. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Se as propostas orçamentárias de que trata este artigo forem encaminhadas em desacordo com os limites estipulados na forma do § 1º, o Poder Executivo procederá aos ajustes necessários para fins de consolidação da proposta orçamentária anual. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Durante a execução orçamentária do exercício, não poderá haver a realização de despesas ou a assunção de obrigações que extrapolem os limites estabelecidos na lei de diretrizes orçamentárias, exceto se previamente autorizadas, mediante a abertura de créditos suplementares ou especiais. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 100**. Os pagamentos devidos pelas Fazendas Públicas Federal, Estaduais, Distrital e Municipais, em virtude de sentença judiciária, far-se-ão exclusivamente na ordem cronológica de apresentação dos precatórios e à conta dos créditos respectivos, proibida a designação de casos ou de pessoas nas dotações orçamentárias e nos créditos adicionais abertos para este fim. (Redação dada pela Emenda Constitucional nº 62, de 2009). (Vide Emenda Constitucional nº 62, de 2009) (Vide ADI 4425)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os débitos de natureza alimentícia compreendem aqueles decorrentes de salários, vencimentos, proventos, pensões e suas complementações, benefícios previdenciários e indenizações por morte ou por invalidez, fundadas em responsabilidade civil, em virtude de sentença judicial transitada em julgado, e serão pagos com preferência sobre todos os demais débitos, exceto sobre aqueles referidos no § 2º deste artigo. (Redação dada pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Os débitos de natureza alimentícia cujos titulares, originários ou por sucessão hereditária, tenham 60 (sessenta) anos de idade, ou sejam portadores de doença grave, ou pessoas com deficiência, assim definidos na forma da lei, serão pagos com preferência sobre todos os demais débitos, até o valor equivalente ao triplo fixado em lei para os fins do disposto no § 3º deste artigo, admitido o fracionamento para essa finalidade, sendo que o restante será pago na ordem cronológica de apresentação do precatório. (Redação dada pela Emenda Constitucional nº 94, de 2016)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º O disposto no caput deste artigo relativamente à expedição de precatórios não se aplica aos pagamentos de obrigações definidas em leis como de pequeno valor que as Fazendas referidas devam fazer em virtude de sentença judicial transitada em julgado. (Redação dada pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Para os fins do disposto no § 3º, poderão ser fixados, por leis próprias, valores distintos às entidades de direito público, segundo as diferentes capacidades econômicas, sendo o mínimo igual ao valor do maior benefício do regime geral de previdência social. (Redação dada pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 5**º É obrigatória a inclusão no orçamento das entidades de direito público de verba necessária ao pagamento de seus débitos oriundos de sentenças transitadas em julgado constantes de precatórios judiciários apresentados até 2 de abril, fazendo-se o pagamento até o final do exercício seguinte, quando terão seus valores atualizados monetariamente. (Redação dada pela Emenda Constitucional nº 114, de 2021) (Vigência)</span>

<span style="display: block; margin-left: 30px;">**§ 6**º As dotações orçamentárias e os créditos abertos serão consignados diretamente ao Poder Judiciário, cabendo ao Presidente do Tribunal que proferir a decisão exequenda determinar o pagamento integral e autorizar, a requerimento do credor e exclusivamente para os casos de preterimento de seu direito de precedência ou de não alocação orçamentária do valor necessário à satisfação do seu débito, o sequestro da quantia respectiva. (Redação dada pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 7**º O Presidente do Tribunal competente que, por ato comissivo ou omissivo, retardar ou tentar frustrar a liquidação regular de precatórios incorrerá em crime de responsabilidade e responderá, também, perante o Conselho Nacional de Justiça. (Incluído pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 8**º É vedada a expedição de precatórios complementares ou suplementares de valor pago, bem como o fracionamento, repartição ou quebra do valor da execução para fins de enquadramento de parcela do total ao que dispõe o § 3º deste artigo. (Incluído pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 9**º Sem que haja interrupção no pagamento do precatório e mediante comunicação da Fazenda Pública ao Tribunal, o valor correspondente aos eventuais débitos inscritos em dívida ativa contra o credor do requisitório e seus substituídos deverá ser depositado à conta do juízo responsável pela ação de cobrança, que decidirá pelo seu destino definitivo. (Redação dada pela Emenda Constitucional nº 113, de 2021) (Vide ADI 7047) (Vide ADI 7064)</span>

<span style="display: block; margin-left: 30px;">**§ 10**. Antes da expedição dos precatórios, o Tribunal solicitará à Fazenda Pública devedora, para resposta em até 30 (trinta) dias, sob pena de perda do direito de abatimento, informação sobre os débitos que preencham as condições estabelecidas no § 9º, para os fins nele previstos. (Incluído pela Emenda Constitucional nº 62, de 2009). (Vide ADI 4425)</span>

<details open style="margin-left: 30px;">
<summary>**§ 11**. É facultada ao credor, conforme estabelecido em lei do ente federativo devedor, com auto aplicabilidade para a União, a oferta de créditos líquidos e certos que originalmente lhe são próprios ou adquiridos de terceiros reconhecidos pelo ente federativo ou por decisão judicial transitada em julgado para: (Redação dada pela Emenda Constitucional nº 113, de 2021) (Vide ADI 7047) (Vide ADI 7064)</summary>
<span style="display: block; margin-left: 60px;">**I - **quitação de débitos parcelados ou débitos inscritos em dívida ativa do ente federativo devedor, inclusive em transação resolutiva de litígio, e, subsidiariamente, débitos com a administração autárquica e fundacional do mesmo ente; (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**II - **compra de imóveis públicos de propriedade do mesmo ente disponibilizados para venda; (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**III - **pagamento de outorga de delegações de serviços públicos e demais espécies de concessão negocial promovidas pelo mesmo ente; (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**IV - **aquisição, inclusive minoritária, de participação societária, disponibilizada para venda, do respectivo ente federativo; ou (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**V - **compra de direitos, disponibilizados para cessão, do respectivo ente federativo, inclusive, no caso da União, da antecipação de valores a serem recebidos a título do excedente em óleo em contratos de partilha de petróleo. (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 12**. A partir da promulgação desta Emenda Constitucional, a atualização de valores de requisitórios, após sua expedição, até o efetivo pagamento, independentemente de sua natureza, será feita pelo índice oficial de remuneração básica da caderneta de poupança, e, para fins de compensação da mora, incidirão juros simples no mesmo percentual de juros incidentes sobre a caderneta de poupança, ficando excluída a incidência de juros compensatórios. (Incluído pela Emenda Constitucional nº 62, de 2009). (Vide ADI 4425)</span>

<span style="display: block; margin-left: 30px;">**§ 13**. O credor poderá ceder, total ou parcialmente, seus créditos em precatórios a terceiros, independentemente da concordância do devedor, não se aplicando ao cessionário o disposto nos §§ 2º e 3º. (Incluído pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 14**. A cessão de precatórios, observado o disposto no § 9º deste artigo, somente produzirá efeitos após comunicação, por meio de petição protocolizada, ao Tribunal de origem e ao ente federativo devedor. (Redação dada pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 30px;">**§ 15**. Sem prejuízo do disposto neste artigo, lei complementar a esta Constituição Federal poderá estabelecer regime especial para pagamento de crédito de precatórios de Estados, Distrito Federal e Municípios, dispondo sobre vinculações à receita corrente líquida e forma e prazo de liquidação. (Incluído pela Emenda Constitucional nº 62, de 2009).</span>

<span style="display: block; margin-left: 30px;">**§ 16**. A seu critério exclusivo e na forma de lei, a União poderá assumir débitos, oriundos de precatórios, de Estados, Distrito Federal e Municípios, refinanciando-os diretamente. (Incluído pela Emenda Constitucional nº 62, de 2009)</span>

<span style="display: block; margin-left: 30px;">**§ 17**. A União, os Estados, o Distrito Federal e os Municípios aferirão mensalmente, em base anual, o comprometimento de suas respectivas receitas correntes líquidas com o pagamento de precatórios e obrigações de pequeno valor. (Incluído pela Emenda Constitucional nº 94, de 2016)</span>

<details open style="margin-left: 30px;">
<summary>**§ 18**. Entende-se como receita corrente líquida, para os fins de que trata o § 17, o somatório das receitas tributárias, patrimoniais, industriais, agropecuárias, de contribuições e de serviços, de transferências correntes e outras receitas correntes, incluindo as oriundas do § 1º do art. 20 da Constituição Federal, verificado no período compreendido pelo segundo mês imediatamente anterior ao de referência e os 11 (onze) meses precedentes, excluídas as duplicidades, e deduzidas: (Incluído pela Emenda Constitucional nº 94, de 2016)</summary>
<span style="display: block; margin-left: 60px;">**I - **na União, as parcelas entregues aos Estados, ao Distrito Federal e aos Municípios por determinação constitucional; (Incluído pela Emenda Constitucional nº 94, de 2016)</span>

<span style="display: block; margin-left: 60px;">**II - **nos Estados, as parcelas entregues aos Municípios por determinação constitucional; (Incluído pela Emenda Constitucional nº 94, de 2016)</span>

<span style="display: block; margin-left: 60px;">**III - **na União, nos Estados, no Distrito Federal e nos Municípios, a contribuição dos servidores para custeio de seu sistema de previdência e assistência social e as receitas provenientes da compensação financeira referida no § 9º do art. 201 da Constituição Federal. (Incluído pela Emenda Constitucional nº 94, de 2016)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 19**. Caso o montante total de débitos decorrentes de condenações judiciais em precatórios e obrigações de pequeno valor, em período de 12 (doze) meses, ultrapasse a média do comprometimento percentual da receita corrente líquida nos 5 (cinco) anos imediatamente anteriores, a parcela que exceder esse percentual poderá ser financiada, excetuada dos limites de endividamento de que tratam os incisos VI e VII do art. 52 da Constituição Federal e de quaisquer outros limites de endividamento previstos, não se aplicando a esse financiamento a vedação de vinculação de receita prevista no inciso IV do art. 167 da Constituição Federal. (Incluído pela Emenda Constitucional nº 94, de 2016)</span>

<span style="display: block; margin-left: 30px;">**§ 20**. Caso haja precatório com valor superior a 15% (quinze por cento) do montante dos precatórios apresentados nos termos do § 5º deste artigo, 15% (quinze por cento) do valor deste precatório serão pagos até o final do exercício seguinte e o restante em parcelas iguais nos cinco exercícios subsequentes, acrescidas de juros de mora e correção monetária, ou mediante acordos diretos, perante Juízos Auxiliares de Conciliação de Precatórios, com redução máxima de 40% (quarenta por cento) do valor do crédito atualizado, desde que em relação ao crédito não penda recurso ou defesa judicial e que sejam observados os requisitos definidos na regulamentação editada pelo ente federado. (Incluído pela Emenda Constitucional nº 94, de 2016)</span>

<details open style="margin-left: 30px;">
<summary>**§ 21**. Ficam a União e os demais entes federativos, nos montantes que lhes são próprios, desde que aceito por ambas as partes, autorizados a utilizar valores objeto de sentenças transitadas em julgado devidos a pessoa jurídica de direito público para amortizar dívidas, vencidas ou vincendas: (Incluído pela Emenda Constitucional nº 113, de 2021)</summary>
<span style="display: block; margin-left: 60px;">**I - **nos contratos de refinanciamento cujos créditos sejam detidos pelo ente federativo que figure como devedor na sentença de que trata o caput deste artigo; (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**II - **nos contratos em que houve prestação de garantia a outro ente federativo; (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**III - **nos parcelamentos de tributos ou de contribuições sociais; e (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**IV - **nas obrigações decorrentes do descumprimento de prestação de contas ou de desvio de recursos. (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

</details>

<details open style="margin-left: 30px;">
<summary>**§ 22**. A amortização de que trata o § 21 deste artigo: (Incluído pela Emenda Constitucional nº 113, de 2021)</summary>
<span style="display: block; margin-left: 60px;">**I - **nas obrigações vencidas, será imputada primeiramente às parcelas mais antigas; (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

<span style="display: block; margin-left: 60px;">**II - **nas obrigações vincendas, reduzirá uniformemente o valor de cada parcela devida, mantida a duração original do respectivo contrato ou parcelamento. (Incluído pela Emenda Constitucional nº 113, de 2021)</span>

</details>

</details>

### SEÇÃO II - DO SUPREMO TRIBUNAL FEDERAL

<details open style="margin-left: 0px;">
<summary>**Art. 101**. O Supremo Tribunal Federal compõe-se de onze Ministros, escolhidos dentre cidadãos com mais de trinta e cinco e menos de setenta anos de idade, de notável saber jurídico e reputação ilibada. (Redação dada pela Emenda Constitucional nº 122, de 2022)</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Os Ministros do Supremo Tribunal Federal serão nomeados pelo Presidente da República, depois de aprovada a escolha pela maioria absoluta do Senado Federal.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 102**. Compete ao Supremo Tribunal Federal, precipuamente, a guarda da Constituição, cabendo-lhe:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **processar e julgar, originariamente:</summary>
<span style="display: block; margin-left: 60px;">**a)** a ação direta de inconstitucionalidade de lei ou ato normativo federal ou estadual e a ação declaratória de constitucionalidade de lei ou ato normativo federal; (Redação dada pela Emenda Constitucional nº 3, de 1993)</span>

<span style="display: block; margin-left: 60px;">**b)** nas infrações penais comuns, o Presidente da República, o Vice-Presidente, os membros do Congresso Nacional, seus próprios Ministros e o Procurador-Geral da República;</span>

<span style="display: block; margin-left: 60px;">**c)** nas infrações penais comuns e nos crimes de responsabilidade, os Ministros de Estado e os Comandantes da Marinha, do Exército e da Aeronáutica, ressalvado o disposto no art. 52, I, os membros dos Tribunais Superiores, os do Tribunal de Contas da União e os chefes de missão diplomática de caráter permanente; (Redação dada pela Emenda Constitucional nº 23, de 1999)</span>

<span style="display: block; margin-left: 60px;">**d)** o habeas corpus, sendo paciente qualquer das pessoas referidas nas alíneas anteriores; o mandado de segurança e o habeas data contra atos do Presidente da República, das Mesas da Câmara dos Deputados e do Senado Federal, do Tribunal de Contas da União, do Procurador-Geral da República e do próprio Supremo Tribunal Federal;</span>

<span style="display: block; margin-left: 60px;">**e)** o litígio entre Estado estrangeiro ou organismo internacional e a União, o Estado, o Distrito Federal ou o Território;</span>

<span style="display: block; margin-left: 60px;">**f)** as causas e os conflitos entre a União e os Estados, a União e o Distrito Federal, ou entre uns e outros, inclusive as respectivas entidades da administração indireta;</span>

<span style="display: block; margin-left: 60px;">**g)** a extradição solicitada por Estado estrangeiro;</span>

<span style="display: block; margin-left: 60px;">**h)** (Revogado pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**i)** o habeas corpus, quando o coator for Tribunal Superior ou quando o coator ou o paciente for autoridade ou funcionário cujos atos estejam sujeitos diretamente à jurisdição do Supremo Tribunal Federal, ou se trate de crime sujeito à mesma jurisdição em uma única instância; (Redação dada pela Emenda Constitucional nº 22, de 1999)</span>

<span style="display: block; margin-left: 60px;">**j)** a revisão criminal e a ação rescisória de seus julgados;</span>

<span style="display: block; margin-left: 60px;">**l)** a reclamação para a preservação de sua competência e garantia da autoridade de suas decisões;</span>

<span style="display: block; margin-left: 60px;">**m)** a execução de sentença nas causas de sua competência originária, facultada a delegação de atribuições para a prática de atos processuais;</span>

<span style="display: block; margin-left: 60px;">**n)** a ação em que todos os membros da magistratura sejam direta ou indiretamente interessados, e aquela em que mais da metade dos membros do tribunal de origem estejam impedidos ou sejam direta ou indiretamente interessados;</span>

<span style="display: block; margin-left: 60px;">**o)** os conflitos de competência entre o Superior Tribunal de Justiça e quaisquer tribunais, entre Tribunais Superiores, ou entre estes e qualquer outro tribunal;</span>

<span style="display: block; margin-left: 60px;">**p)** o pedido de medida cautelar das ações diretas de inconstitucionalidade;</span>

<span style="display: block; margin-left: 60px;">**q)** o mandado de injunção, quando a elaboração da norma regulamentadora for atribuição do Presidente da República, do Congresso Nacional, da Câmara dos Deputados, do Senado Federal, das Mesas de uma dessas Casas Legislativas, do Tribunal de Contas da União, de um dos Tribunais Superiores, ou do próprio Supremo Tribunal Federal;</span>

<span style="display: block; margin-left: 60px;">**r)** as ações contra o Conselho Nacional de Justiça e contra o Conselho Nacional do Ministério Público; (Incluída pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 30px;">
<summary>**II - **julgar, em recurso ordinário:</summary>
<span style="display: block; margin-left: 60px;">**a)** o habeas corpus, o mandado de segurança, o habeas data e o mandado de injunção decididos em única instância pelos Tribunais Superiores, se denegatória a decisão;</span>

<span style="display: block; margin-left: 60px;">**b)** o crime político;</span>

</details>

<details open style="margin-left: 30px;">
<summary>**III - **julgar, mediante recurso extraordinário, as causas decididas em única ou última instância, quando a decisão recorrida:</summary>
<span style="display: block; margin-left: 60px;">**a)** contrariar dispositivo desta Constituição;</span>

<span style="display: block; margin-left: 60px;">**b)** declarar a inconstitucionalidade de tratado ou lei federal;</span>

<span style="display: block; margin-left: 60px;">**c)** julgar válida lei ou ato de governo local contestado em face desta Constituição.</span>

<span style="display: block; margin-left: 60px;">**d)** julgar válida lei local contestada em face de lei federal. (Incluída pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 1**.º A argüição de descumprimento de preceito fundamental, decorrente desta Constituição, será apreciada pelo Supremo Tribunal Federal, na forma da lei. (Transformado do parágrafo único em § 1º pela Emenda Constitucional nº 3, de 17/03/93)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º As decisões definitivas de mérito, proferidas pelo Supremo Tribunal Federal, nas ações diretas de inconstitucionalidade e nas ações declaratórias de constitucionalidade produzirão eficácia contra todos e efeito vinculante, relativamente aos demais órgãos do Poder Judiciário e à administração pública direta e indireta, nas esferas federal, estadual e municipal. (Redação dada pela Emenda Constitucional nº 45, de 2004) (Vide ADIN 3392)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º No recurso extraordinário o recorrente deverá demonstrar a repercussão geral das questões constitucionais discutidas no caso, nos termos da lei, a fim de que o Tribunal examine a admissão do recurso, somente podendo recusá-lo pela manifestação de dois terços de seus membros. (Incluída pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 103**. Podem propor a ação direta de inconstitucionalidade e a ação declaratória de constitucionalidade: (Redação dada pela Emenda Constitucional nº 45, de 2004) (Vide Lei nº 13.105, de 2015) (Vigência)</summary>
<span style="display: block; margin-left: 30px;">**I - **o Presidente da República;</span>

<span style="display: block; margin-left: 30px;">**II - **a Mesa do Senado Federal;</span>

<span style="display: block; margin-left: 30px;">**III - **a Mesa da Câmara dos Deputados;</span>

<span style="display: block; margin-left: 30px;">**IV - **a Mesa de Assembléia Legislativa ou da Câmara Legislativa do Distrito Federal; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**V - **o Governador de Estado ou do Distrito Federal; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**VI - **o Procurador-Geral da República;</span>

<span style="display: block; margin-left: 30px;">**VII - **o Conselho Federal da Ordem dos Advogados do Brasil;</span>

<span style="display: block; margin-left: 30px;">**VIII - **partido político com representação no Congresso Nacional;</span>

<span style="display: block; margin-left: 30px;">**IX - **confederação sindical ou entidade de classe de âmbito nacional.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º O Procurador-Geral da República deverá ser previamente ouvido nas ações de inconstitucionalidade e em todos os processos de competência do Supremo Tribunal Federal.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Declarada a inconstitucionalidade por omissão de medida para tornar efetiva norma constitucional, será dada ciência ao Poder competente para a adoção das providências necessárias e, em se tratando de órgão administrativo, para fazê-lo em trinta dias.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Quando o Supremo Tribunal Federal apreciar a inconstitucionalidade, em tese, de norma legal ou ato normativo, citará, previamente, o Advogado-Geral da União, que defenderá o ato ou texto impugnado.</span>

<span style="display: block; margin-left: 30px;">**§ 4**.º (Revogado pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 103**-A. O Supremo Tribunal Federal poderá, de ofício ou por provocação, mediante decisão de dois terços dos seus membros, após reiteradas decisões sobre matéria constitucional, aprovar súmula que, a partir de sua publicação na imprensa oficial, terá efeito vinculante em relação aos demais órgãos do Poder Judiciário e à administração pública direta e indireta, nas esferas federal, estadual e municipal, bem como proceder à sua revisão ou cancelamento, na forma estabelecida em lei. (Incluído pela Emenda Constitucional nº 45, de 2004) (Vide Lei nº 11.417, de 2006).</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º A súmula terá por objetivo a validade, a interpretação e a eficácia de normas determinadas, acerca das quais haja controvérsia atual entre órgãos judiciários ou entre esses e a administração pública que acarrete grave insegurança jurídica e relevante multiplicação de processos sobre questão idêntica. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Sem prejuízo do que vier a ser estabelecido em lei, a aprovação, revisão ou cancelamento de súmula poderá ser provocada por aqueles que podem propor a ação direta de inconstitucionalidade. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Do ato administrativo ou decisão judicial que contrariar a súmula aplicável ou que indevidamente a aplicar, caberá reclamação ao Supremo Tribunal Federal que, julgando-a procedente, anulará o ato administrativo ou cassará a decisão judicial reclamada, e determinará que outra seja proferida com ou sem a aplicação da súmula, conforme o caso. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 103**-B. O Conselho Nacional de Justiça compõe-se de 15 (quinze) membros com mandato de 2 (dois) anos, admitida 1 (uma) recondução, sendo: (Redação dada pela Emenda Constitucional nº 61, de 2009)</summary>
<span style="display: block; margin-left: 30px;">**I - **o Presidente do Supremo Tribunal Federal; (Redação dada pela Emenda Constitucional nº 61, de 2009)</span>

<span style="display: block; margin-left: 30px;">**§ 1**º O Conselho será presidido pelo Presidente do Supremo Tribunal Federal e, nas suas ausências e impedimentos, pelo Vice-Presidente do Supremo Tribunal Federal. (Redação dada pela Emenda Constitucional nº 61, de 2009)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Os demais membros do Conselho serão nomeados pelo Presidente da República, depois de aprovada a escolha pela maioria absoluta do Senado Federal. (Redação dada pela Emenda Constitucional nº 61, de 2009)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Não efetuadas, no prazo legal, as indicações previstas neste artigo, caberá a escolha ao Supremo Tribunal Federal. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<details open style="margin-left: 30px;">
<summary>**§ 4**º Compete ao Conselho o controle da atuação administrativa e financeira do Poder Judiciário e do cumprimento dos deveres funcionais dos juízes, cabendo-lhe, além de outras atribuições que lhe forem conferidas pelo Estatuto da Magistratura: (Incluído pela Emenda Constitucional nº 45, de 2004)</summary>
<span style="display: block; margin-left: 60px;">**I - **zelar pela autonomia do Poder Judiciário e pelo cumprimento do Estatuto da Magistratura, podendo expedir atos regulamentares, no âmbito de sua competência, ou recomendar providências; (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**II - **zelar pela observância do art. 37 e apreciar, de ofício ou mediante provocação, a legalidade dos atos administrativos praticados por membros ou órgãos do Poder Judiciário, podendo desconstituí-los, revê-los ou fixar prazo para que se adotem as providências necessárias ao exato cumprimento da lei, sem prejuízo da competência do Tribunal de Contas da União; (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**III - **receber e conhecer das reclamações contra membros ou órgãos do Poder Judiciário, inclusive contra seus serviços auxiliares, serventias e órgãos prestadores de serviços notariais e de registro que atuem por delegação do poder público ou oficializados, sem prejuízo da competência disciplinar e correicional dos tribunais, podendo avocar processos disciplinares em curso, determinar a remoção ou a disponibilidade e aplicar outras sanções administrativas, assegurada ampla defesa; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 5**º O Ministro do Superior Tribunal de Justiça exercerá a função de Ministro-Corregedor e ficará excluído da distribuição de processos no Tribunal, competindo-lhe, além das atribuições que lhe forem conferidas pelo Estatuto da Magistratura, as seguintes: (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 6**º Junto ao Conselho oficiarão o Procurador-Geral da República e o Presidente do Conselho Federal da Ordem dos Advogados do Brasil. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 7**º A União, inclusive no Distrito Federal e nos Territórios, criará ouvidorias de justiça, competentes para receber reclamações e denúncias de qualquer interessado contra membros ou órgãos do Poder Judiciário, ou contra seus serviços auxiliares, representando diretamente ao Conselho Nacional de Justiça. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

### SEÇÃO III - DO SUPERIOR TRIBUNAL DE JUSTIÇA

<details open style="margin-left: 0px;">
<summary>**Art. 104**. O Superior Tribunal de Justiça compõe-se de, no mínimo, trinta e três Ministros.</summary>
<details open style="margin-left: 30px;">
<summary>**Parágrafo único**. Os Ministros do Superior Tribunal de Justiça serão nomeados pelo Presidente da República, dentre brasileiros com mais de trinta e cinco e menos de setenta anos de idade, de notável saber jurídico e reputação ilibada, depois de aprovada a escolha pela maioria absoluta do Senado Federal, sendo: (Redação dada pela Emenda Constitucional nº 122, de 2022)</summary>
<span style="display: block; margin-left: 60px;">**I - **um terço dentre juízes dos Tribunais Regionais Federais e um terço dentre desembargadores dos Tribunais de Justiça, indicados em lista tríplice elaborada pelo próprio Tribunal;</span>

<span style="display: block; margin-left: 60px;">**II - **um terço, em partes iguais, dentre advogados e membros do Ministério Público Federal, Estadual, do Distrito Federal e Territórios, alternadamente, indicados na forma do art. 94.</span>

</details>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 105**. Compete ao Superior Tribunal de Justiça:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **processar e julgar, originariamente:</summary>
<span style="display: block; margin-left: 60px;">**a)** nos crimes comuns, os Governadores dos Estados e do Distrito Federal, e, nestes e nos de responsabilidade, os desembargadores dos Tribunais de Justiça dos Estados e do Distrito Federal, os membros dos Tribunais de Contas dos Estados e do Distrito Federal, os dos Tribunais Regionais Federais, dos Tribunais Regionais Eleitorais e do Trabalho, os membros dos Conselhos ou Tribunais de Contas dos Municípios e os do Ministério Público da União que oficiem perante tribunais;</span>

<span style="display: block; margin-left: 60px;">**b)** os mandados de segurança e os habeas data contra ato de Ministro de Estado, dos Comandantes da Marinha, do Exército e da Aeronáutica ou do próprio Tribunal; (Redação dada pela Emenda Constitucional nº 23, de 1999)</span>

<span style="display: block; margin-left: 60px;">**c)** os habeas corpus, quando o coator ou paciente for qualquer das pessoas mencionadas na alínea a, ou quando o coator for tribunal sujeito à sua jurisdição, Ministro de Estado ou Comandante da Marinha, do Exército ou da Aeronáutica, ressalvada a competência da Justiça Eleitoral; (Redação dada pela Emenda Constitucional nº 23, de 1999)</span>

<span style="display: block; margin-left: 60px;">**d)** os conflitos de competência entre quaisquer tribunais, ressalvado o disposto no art. 102, I, "o", bem como entre tribunal e juízes a ele não vinculados e entre juízes vinculados a tribunais diversos;</span>

<span style="display: block; margin-left: 60px;">**e)** as revisões criminais e as ações rescisórias de seus julgados;</span>

<span style="display: block; margin-left: 60px;">**f)** a reclamação para a preservação de sua competência e garantia da autoridade de suas decisões;</span>

<span style="display: block; margin-left: 60px;">**g)** os conflitos de atribuições entre autoridades administrativas e judiciárias da União, ou entre autoridades judiciárias de um Estado e administrativas de outro ou do Distrito Federal, ou entre as deste e da União;</span>

<span style="display: block; margin-left: 60px;">**h)** o mandado de injunção, quando a elaboração da norma regulamentadora for atribuição de órgão, entidade ou autoridade federal, da administração direta ou indireta, excetuados os casos de competência do Supremo Tribunal Federal e dos órgãos da Justiça Militar, da Justiça Eleitoral, da Justiça do Trabalho e da Justiça Federal;</span>

<span style="display: block; margin-left: 60px;">**i)** a homologação de sentenças estrangeiras e a concessão de exequatur às cartas rogatórias; (Incluída pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**j)** os conflitos entre entes federativos, ou entre estes e o Comitê Gestor do Imposto sobre Bens e Serviços, relacionados aos tributos previstos nos arts. 156-A e 195, V; (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

</details>

<details open style="margin-left: 30px;">
<summary>**II - **julgar, em recurso ordinário:</summary>
<span style="display: block; margin-left: 60px;">**a)** os habeas corpus decididos em única ou última instância pelos Tribunais Regionais Federais ou pelos tribunais dos Estados, do Distrito Federal e Territórios, quando a decisão for denegatória;</span>

<span style="display: block; margin-left: 60px;">**b)** os mandados de segurança decididos em única instância pelos Tribunais Regionais Federais ou pelos tribunais dos Estados, do Distrito Federal e Territórios, quando denegatória a decisão;</span>

<span style="display: block; margin-left: 60px;">**c)** as causas em que forem partes Estado estrangeiro ou organismo internacional, de um lado, e, do outro, Município ou pessoa residente ou domiciliada no País;</span>

</details>

<details open style="margin-left: 30px;">
<summary>**III - **julgar, em recurso especial, as causas decididas, em única ou última instância, pelos Tribunais Regionais Federais ou pelos tribunais dos Estados, do Distrito Federal e Territórios, quando a decisão recorrida:</summary>
<span style="display: block; margin-left: 60px;">**a)** contrariar tratado ou lei federal, ou negar-lhes vigência;</span>

<span style="display: block; margin-left: 60px;">**b)** julgar válido ato de governo local contestado em face de lei federal; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**c)** der a lei federal interpretação divergente da que lhe haja atribuído outro tribunal.</span>

</details>

<details open style="margin-left: 30px;">
<summary>**§ 1**º Funcionarão junto ao Superior Tribunal de Justiça:</summary>
<span style="display: block; margin-left: 60px;">**I - **a Escola Nacional de Formação e Aperfeiçoamento de Magistrados, cabendo-lhe, dentre outras funções, regulamentar os cursos oficiais para o ingresso e promoção na carreira; (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 60px;">**II - **o Conselho da Justiça Federal, cabendo-lhe exercer, na forma da lei, a supervisão administrativa e orçamentária da Justiça Federal de primeiro e segundo graus, como órgão central do sistema e com poderes correicionais, cujas decisões terão caráter vinculante. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º No recurso especial, o recorrente deve demonstrar a relevância das questões de direito federal infraconstitucional discutidas no caso, nos termos da lei, a fim de que a admissão do recurso seja examinada pelo Tribunal, o qual somente pode dele não conhecer com base nesse motivo pela manifestação de 2/3 (dois terços) dos membros do órgão competente para o julgamento. (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

<details open style="margin-left: 30px;">
<summary>**§ 3**º Haverá a relevância de que trata o § 2º deste artigo nos seguintes casos: (Incluído pela Emenda Constitucional nº 125, de 2022)</summary>
<span style="display: block; margin-left: 60px;">**I - **ações penais; (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

<span style="display: block; margin-left: 60px;">**II - **ações de improbidade administrativa; (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

<span style="display: block; margin-left: 60px;">**III - **ações cujo valor da causa ultrapasse 500 (quinhentos) salários mínimos; (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

<span style="display: block; margin-left: 60px;">**IV - **ações que possam gerar inelegibilidade; (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

<span style="display: block; margin-left: 60px;">**V - **hipóteses em que o acórdão recorrido contrariar jurisprudência dominante do Superior Tribunal de Justiça; (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

<span style="display: block; margin-left: 60px;">**VI - **outras hipóteses previstas em lei. (Incluído pela Emenda Constitucional nº 125, de 2022)</span>

</details>

</details>

### SEÇÃO IV - DOS TRIBUNAIS REGIONAIS FEDERAIS E DOS JUÍZES FEDERAIS

<details open style="margin-left: 0px;">
<summary>**Art. 106**. São órgãos da Justiça Federal:</summary>
<span style="display: block; margin-left: 30px;">**I - **os Tribunais Regionais Federais;</span>

<span style="display: block; margin-left: 30px;">**II - **os Juízes Federais.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 107**. Os Tribunais Regionais Federais compõem-se de, no mínimo, sete juízes, recrutados, quando possível, na respectiva região e nomeados pelo Presidente da República dentre brasileiros com mais de trinta e menos de setenta anos de idade, sendo: (Redação dada pela Emenda Constitucional nº 122, de 2022)</summary>
<span style="display: block; margin-left: 30px;">**I - **um quinto dentre advogados com mais de dez anos de efetiva atividade profissional e membros do Ministério Público Federal com mais de dez anos de carreira;</span>

<span style="display: block; margin-left: 30px;">**II - **os demais, mediante promoção de juízes federais com mais de cinco anos de exercício, por antigüidade e merecimento, alternadamente.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º A lei disciplinará a remoção ou a permuta de juízes dos Tribunais Regionais Federais e determinará sua jurisdição e sede. (Renumerado do parágrafo único, pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Os Tribunais Regionais Federais instalarão a justiça itinerante, com a realização de audiências e demais funções da atividade jurisdicional, nos limites territoriais da respectiva jurisdição, servindo-se de equipamentos públicos e comunitários. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Os Tribunais Regionais Federais poderão funcionar descentralizadamente, constituindo Câmaras regionais, a fim de assegurar o pleno acesso do jurisdicionado à justiça em todas as fases do processo. (Incluído pela Emenda Constitucional nº 45, de 2004) )</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 108**. Compete aos Tribunais Regionais Federais:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **processar e julgar, originariamente:</summary>
<span style="display: block; margin-left: 60px;">**a)** os juízes federais da área de sua jurisdição, incluídos os da Justiça Militar e da Justiça do Trabalho, nos crimes comuns e de responsabilidade, e os membros do Ministério Público da União, ressalvada a competência da Justiça Eleitoral;</span>

<span style="display: block; margin-left: 60px;">**b)** as revisões criminais e as ações rescisórias de julgados seus ou dos juízes federais da região;</span>

<span style="display: block; margin-left: 60px;">**c)** os mandados de segurança e os habeas data contra ato do próprio Tribunal ou de juiz federal;</span>

<span style="display: block; margin-left: 60px;">**d)** os habeas corpus, quando a autoridade coatora for juiz federal;</span>

<span style="display: block; margin-left: 60px;">**e)** os conflitos de competência entre juízes federais vinculados ao Tribunal;</span>

</details>

<span style="display: block; margin-left: 30px;">**II - **julgar, em grau de recurso, as causas decididas pelos juízes federais e pelos juízes estaduais no exercício da competência federal da área de sua jurisdição.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 109**. Aos juízes federais compete processar e julgar:</summary>
<span style="display: block; margin-left: 30px;">**I - **as causas em que a União, entidade autárquica ou empresa pública federal forem interessadas na condição de autoras, rés, assistentes ou oponentes, exceto as de falência, as de acidentes de trabalho e as sujeitas à Justiça Eleitoral e à Justiça do Trabalho;</span>

<span style="display: block; margin-left: 30px;">**II - **as causas entre Estado estrangeiro ou organismo internacional e Município ou pessoa domiciliada ou residente no País;</span>

<span style="display: block; margin-left: 30px;">**III - **as causas fundadas em tratado ou contrato da União com Estado estrangeiro ou organismo internacional;</span>

<span style="display: block; margin-left: 30px;">**IV - **os crimes políticos e as infrações penais praticadas em detrimento de bens, serviços ou interesse da União ou de suas entidades autárquicas ou empresas públicas, excluídas as contravenções e ressalvada a competência da Justiça Militar e da Justiça Eleitoral;</span>

<span style="display: block; margin-left: 30px;">**V - **os crimes previstos em tratado ou convenção internacional, quando, iniciada a execução no País, o resultado tenha ou devesse ter ocorrido no estrangeiro, ou reciprocamente;</span>

<span style="display: block; margin-left: 30px;">**VI - **os crimes contra a organização do trabalho e, nos casos determinados por lei, contra o sistema financeiro e a ordem econômico-financeira;</span>

<span style="display: block; margin-left: 30px;">**VII - **os habeas corpus, em matéria criminal de sua competência ou quando o constrangimento provier de autoridade cujos atos não estejam diretamente sujeitos a outra jurisdição;</span>

<span style="display: block; margin-left: 30px;">**VIII - **os mandados de segurança e os habeas data contra ato de autoridade federal, excetuados os casos de competência dos tribunais federais;</span>

<span style="display: block; margin-left: 30px;">**IX - **os crimes cometidos a bordo de navios ou aeronaves, ressalvada a competência da Justiça Militar;</span>

<span style="display: block; margin-left: 30px;">**X - **os crimes de ingresso ou permanência irregular de estrangeiro, a execução de carta rogatória, após o "exequatur", e de sentença estrangeira, após a homologação, as causas referentes à nacionalidade, inclusive a respectiva opção, e à naturalização;</span>

<span style="display: block; margin-left: 30px;">**XI - **a disputa sobre direitos indígenas.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º As causas em que a União for autora serão aforadas na seção judiciária onde tiver domicílio a outra parte.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º As causas intentadas contra a União poderão ser aforadas na seção judiciária em que for domiciliado o autor, naquela onde houver ocorrido o ato ou fato que deu origem à demanda ou onde esteja situada a coisa, ou, ainda, no Distrito Federal.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Lei poderá autorizar que as causas de competência da Justiça Federal em que forem parte instituição de previdência social e segurado possam ser processadas e julgadas na justiça estadual quando a comarca do domicílio do segurado não for sede de vara federal. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Na hipótese do parágrafo anterior, o recurso cabível será sempre para o Tribunal Regional Federal na área de jurisdição do juiz de primeiro grau.</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Nas hipóteses de grave violação de direitos humanos, o Procurador-Geral da República, com a finalidade de assegurar o cumprimento de obrigações decorrentes de tratados internacionais de direitos humanos dos quais o Brasil seja parte, poderá suscitar, perante o Superior Tribunal de Justiça, em qualquer fase do inquérito ou processo, incidente de deslocamento de competência para a Justiça Federal. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 110**. Cada Estado, bem como o Distrito Federal, constituirá uma seção judiciária que terá por sede a respectiva Capital, e varas localizadas segundo o estabelecido em lei.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Nos Territórios Federais, a jurisdição e as atribuições cometidas aos juízes federais caberão aos juízes da justiça local, na forma da lei.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 111**. São órgãos da Justiça do Trabalho:</summary>
<span style="display: block; margin-left: 30px;">**I - **o Tribunal Superior do Trabalho;</span>

<span style="display: block; margin-left: 30px;">**II - **os Tribunais Regionais do Trabalho;</span>

<span style="display: block; margin-left: 30px;">**III - **Juizes do Trabalho. (Redação dada pela Emenda Constitucional nº 24, de 1999)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 111**-A. O Tribunal Superior do Trabalho compõe-se de vinte e sete Ministros, escolhidos dentre brasileiros com mais de trinta e cinco e menos de setenta anos de idade, de notável saber jurídico e reputação ilibada, nomeados pelo Presidente da República após aprovação pela maioria absoluta do Senado Federal, sendo: (Redação dada pela Emenda Constitucional nº 122, de 2022)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º A lei disporá sobre a competência do Tribunal Superior do Trabalho. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Funcionarão junto ao Tribunal Superior do Trabalho: (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Compete ao Tribunal Superior do Trabalho processar e julgar, originariamente, a reclamação para a preservação de sua competência e garantia da autoridade de suas decisões. (Incluído pela Emenda Constitucional nº 92, de 2016)</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 112**. A lei criará varas da Justiça do Trabalho, podendo, nas comarcas não abrangidas por sua jurisdição, atribuí-la aos juízes de direito, com recurso para o respectivo Tribunal Regional do T rabalho. (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 0px;">**Art. 113**. A lei disporá sobre a constituição, investidura, jurisdição, competência, garantias e condições de exercício dos órgãos da Justiça do Trabalho. (Redação dada pela Emenda Constitucional nº 24, de 1999)</span>

<details open style="margin-left: 0px;">
<summary>**Art. 114**. Compete à Justiça do Trabalho processar e julgar: (Redação dada pela Emenda Constitucional nº 45, de 2004) (Vide ADIN 3392) (Vide ADIN 3432)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Frustrada a negociação coletiva, as partes poderão eleger árbitros.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Recusando-se qualquer das partes à negociação coletiva ou à arbitragem, é facultado às mesmas, de comum acordo, ajuizar dissídio coletivo de natureza econômica, podendo a Justiça do Trabalho decidir o conflito, respeitadas as disposições mínimas legais de proteção ao trabalho, bem como as convencionadas anteriormente. (Redação dada pela Emenda Constitucional nº 45, de 2004) (Vide ADI nº 3423) (Vide ADI nº 3392) (Vide ADI nº 3431) (Vide ADI nº 3432) (Vide ADI nº 3520) (Vide ADIN 3432)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Em caso de greve em atividade essencial, com possibilidade de lesão do interesse público, o Ministério Público do Trabalho poderá ajuizar dissídio coletivo, competindo à Justiça do Trabalho decidir o conflito. (Redação dada pela Emenda Constitucional nº 45, de 2004) (Vide ADI nº 3423) (Vide ADI nº 3431) (Vide ADI nº 3520) (Vide ADIN 3392) (Vide ADIN 3432)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 115**. Os Tribunais Regionais do Trabalho compõem-se de, no mínimo, sete juízes, recrutados, quando possível, na respectiva região e nomeados pelo Presidente da República dentre brasileiros com mais de trinta e menos de setenta anos de idade, sendo: (Redação dada pela Emenda Constitucional nº 122, de 2022)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os Tribunais Regionais do Trabalho instalarão a justiça itinerante, com a realização de audiências e demais funções de atividade jurisdicional, nos limites territoriais da respectiva jurisdição, servindo-se de equipamentos públicos e comunitários. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Os Tribunais Regionais do Trabalho poderão funcionar descentralizadamente, constituindo Câmaras regionais, a fim de assegurar o pleno acesso do jurisdicionado à justiça em todas as fases do processo. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 116**. Nas Varas do Trabalho, a jurisdição será exercida por um juiz singular. (Redação dada pela Emenda Constitucional nº 24, de 1999)</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. (Revogado pela Emenda Constitucional nº 24, de 1999)</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 117**. e **Parágrafo único**. (Revogados pela Emenda Constitucional nº 24, de 1999)</span>

### SEÇÃO VI - DOS TRIBUNAIS E JUÍZES ELEITORAIS

<details open style="margin-left: 0px;">
<summary>**Art. 118**. São órgãos da Justiça Eleitoral:</summary>
<span style="display: block; margin-left: 30px;">**I - **o Tribunal Superior Eleitoral;</span>

<span style="display: block; margin-left: 30px;">**II - **os Tribunais Regionais Eleitorais;</span>

<span style="display: block; margin-left: 30px;">**III - **os Juízes Eleitorais;</span>

<span style="display: block; margin-left: 30px;">**IV - **as Juntas Eleitorais.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 119**. O Tribunal Superior Eleitoral compor-se-á, no mínimo, de sete membros, escolhidos:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **mediante eleição, pelo voto secreto:</summary>
<span style="display: block; margin-left: 60px;">**a)** três juízes dentre os Ministros do Supremo Tribunal Federal;</span>

<span style="display: block; margin-left: 60px;">**b)** dois juízes dentre os Ministros do Superior Tribunal de Justiça;</span>

</details>

<span style="display: block; margin-left: 30px;">**II - **por nomeação do Presidente da República, dois juízes dentre seis advogados de notável saber jurídico e idoneidade moral, indicados pelo Supremo Tribunal Federal.</span>

<span style="display: block; margin-left: 30px;">**Parágrafo único**. O Tribunal Superior Eleitoral elegerá seu Presidente e o Vice-Presidente dentre os Ministros do Supremo Tribunal Federal, e o Corregedor Eleitoral dentre os Ministros do Superior Tribunal de Justiça.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 120**. Haverá um Tribunal Regional Eleitoral na Capital de cada Estado e no Distrito Federal.</summary>
<details open style="margin-left: 30px;">
<summary>**§ 1**º - Os Tribunais Regionais Eleitorais compor-se-ão:</summary>
<details open style="margin-left: 60px;">
<summary>**I - **mediante eleição, pelo voto secreto:</summary>
<span style="display: block; margin-left: 90px;">**a)** de dois juízes dentre os desembargadores do Tribunal de Justiça;</span>

<span style="display: block; margin-left: 90px;">**b)** de dois juízes, dentre juízes de direito, escolhidos pelo Tribunal de Justiça;</span>

</details>

<span style="display: block; margin-left: 60px;">**II - **de um juiz do Tribunal Regional Federal com sede na Capital do Estado ou no Distrito Federal, ou, não havendo, de juiz federal, escolhido, em qualquer caso, pelo Tribunal Regional Federal respectivo;</span>

<span style="display: block; margin-left: 60px;">**III - **por nomeação, pelo Presidente da República, de dois juízes dentre seis advogados de notável saber jurídico e idoneidade moral, indicados pelo Tribunal de Justiça.</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 2**º - O Tribunal Regional Eleitoral elegerá seu Presidente e o Vice-Presidente- dentre os desembargadores.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 121**. Lei complementar disporá sobre a organização e competência dos tribunais, dos juízes de direito e das juntas eleitorais.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os membros dos tribunais, os juízes de direito e os integrantes das juntas eleitorais, no exercício de suas funções, e no que lhes for aplicável, gozarão de plenas garantias e serão inamovíveis.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Os juízes dos tribunais eleitorais, salvo motivo justificado, servirão por dois anos, no mínimo, e nunca por mais de dois biênios consecutivos, sendo os substitutos escolhidos na mesma ocasião e pelo mesmo processo, em número igual para cada categoria.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º São irrecorríveis as decisões do Tribunal Superior Eleitoral, salvo as que contrariarem esta Constituição e as denegatórias de habeas corpus ou mandado de segurança.</span>

<details open style="margin-left: 30px;">
<summary>**§ 4**º Das decisões dos Tribunais Regionais Eleitorais somente caberá recurso quando:</summary>
<span style="display: block; margin-left: 60px;">**I - **forem proferidas contra disposição expressa desta Constituição ou de lei;</span>

<span style="display: block; margin-left: 60px;">**II - **ocorrer divergência na interpretação de lei entre dois ou mais tribunais eleitorais;</span>

<span style="display: block; margin-left: 60px;">**III - **versarem sobre inelegibilidade ou expedição de diplomas nas eleições federais ou estaduais;</span>

<span style="display: block; margin-left: 60px;">**IV - **anularem diplomas ou decretarem a perda de mandatos eletivos federais ou estaduais;</span>

<span style="display: block; margin-left: 60px;">**V - **denegarem habeas corpus, mandado de segurança, habeas data ou mandado de injunção.</span>

</details>

</details>

### SEÇÃO VII - DOS TRIBUNAIS E JUÍZES MILITARES

<details open style="margin-left: 0px;">
<summary>**Art. 122**. São órgãos da Justiça Militar:</summary>
<span style="display: block; margin-left: 30px;">**I - **o Superior Tribunal Militar;</span>

<span style="display: block; margin-left: 30px;">**II - **os Tribunais e Juízes Militares instituídos por lei.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 123**. O Superior Tribunal Militar compor-se-á de quinze Ministros vitalícios, nomeados pelo Presidente da República, depois de aprovada a indicação pelo Senado Federal, sendo três dentre oficiais-generais da Marinha, quatro dentre oficiais-generais do Exército, três dentre oficiais-generais da Aeronáutica, todos da ativa e do posto mais elevado da carreira, e cinco dentre civis.</summary>
<details open style="margin-left: 30px;">
<summary>**Parágrafo único**. Os Ministros civis serão escolhidos pelo Presidente da República dentre brasileiros com mais de trinta e cinco e menos de setenta anos de idade, sendo: (Redação dada pela Emenda Constitucional nº 122, de 2022)</summary>
<span style="display: block; margin-left: 60px;">**I - **três dentre advogados de notório saber jurídico e conduta ilibada, com mais de dez anos de efetiva atividade profissional;</span>

<span style="display: block; margin-left: 60px;">**II - **dois, por escolha paritária, dentre juízes auditores e membros do Ministério Público da Justiça Militar.</span>

</details>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 124**. à Justiça Militar compete processar e julgar os crimes militares definidos em lei.</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. A lei disporá sobre a organização, o funcionamento e a competência da Justiça Militar.</span>

</details>

### SEÇÃO VIII - DOS TRIBUNAIS E JUÍZES DOS ESTADOS

<details open style="margin-left: 0px;">
<summary>**Art. 125**. Os Estados organizarão sua Justiça, observados os princípios estabelecidos nesta Constituição.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º A competência dos tribunais será definida na Constituição do Estado, sendo a lei de organização judiciária de iniciativa do Tribunal de Justiça.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Cabe aos Estados a instituição de representação de inconstitucionalidade de leis ou atos normativos estaduais ou municipais em face da Constituição Estadual, vedada a atribuição da legitimação para agir a um único órgão.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º A lei estadual poderá criar, mediante proposta do Tribunal de Justiça, a Justiça Militar estadual, constituída, em primeiro grau, pelos juízes de direito e pelos Conselhos de Justiça e, em segundo grau, pelo próprio Tribunal de Justiça, ou por Tribunal de Justiça Militar nos Estados em que o efetivo militar seja superior a vinte mil integrantes. (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Compete à Justiça Militar estadual processar e julgar os militares dos Estados, nos crimes militares definidos em lei e as ações judiciais contra atos disciplinares militares, ressalvada a competência do júri quando a vítima for civil, cabendo ao tribunal competente decidir sobre a perda do posto e da patente dos oficiais e da graduação das praças. (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Compete aos juízes de direito do juízo militar processar e julgar, singularmente, os crimes militares cometidos contra civis e as ações judiciais contra atos disciplinares militares, cabendo ao Conselho de Justiça, sob a presidência de juiz de direito, processar e julgar os demais crimes militares. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 6**º O Tribunal de Justiça poderá funcionar descentralizadamente, constituindo Câmaras regionais, a fim de assegurar o pleno acesso do jurisdicionado à justiça em todas as fases do processo. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 7**º O Tribunal de Justiça instalará a justiça itinerante, com a realização de audiências e demais funções da atividade jurisdicional, nos limites territoriais da respectiva jurisdição, servindo-se de equipamentos públicos e comunitários. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 126**. Para dirimir conflitos fundiários, o Tribunal de Justiça proporá a criação de varas especializadas, com competência exclusiva para questões agrárias. (Redação dada pela Emenda Constitucional nº 45, de 2004)</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Sempre que necessário à eficiente prestação jurisdicional, o juiz far-se-á presente no local do litígio.</span>

</details>

## CAPÍTULO IV - DAS FUNÇÕES ESSENCIAIS À JUSTIÇA

### SEÇÃO I - DO MINISTÉRIO PÚBLICO

<details open style="margin-left: 0px;">
<summary>**Art. 127**. O Ministério Público é instituição permanente, essencial à função jurisdicional do Estado, incumbindo-lhe a defesa da ordem jurídica, do regime democrático e dos interesses sociais e individuais indisponíveis.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º São princípios institucionais do Ministério Público a unidade, a indivisibilidade e a independência funcional.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Ao Ministério Público é assegurada autonomia funcional e administrativa, podendo, observado o disposto no art. 169, propor ao Poder Legislativo a criação e extinção de seus cargos e serviços auxiliares, provendo-os por concurso público de provas ou de provas e títulos, a política remuneratória e os planos de carreira; a lei disporá sobre sua organização e funcionamento. (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º O Ministério Público elaborará sua proposta orçamentária dentro dos limites estabelecidos na lei de diretrizes orçamentárias.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Se o Ministério Público não encaminhar a respectiva proposta orçamentária dentro do prazo estabelecido na lei de diretrizes orçamentárias, o Poder Executivo considerará, para fins de consolidação da proposta orçamentária anual, os valores aprovados na lei orçamentária vigente, ajustados de acordo com os limites estipulados na forma do § 3º. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Se a proposta orçamentária de que trata este artigo for encaminhada em desacordo com os limites estipulados na forma do § 3º, o Poder Executivo procederá aos ajustes necessários para fins de consolidação da proposta orçamentária anual. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 6**º Durante a execução orçamentária do exercício, não poderá haver a realização de despesas ou a assunção de obrigações que extrapolem os limites estabelecidos na lei de diretrizes orçamentárias, exceto se previamente autorizadas, mediante a abertura de créditos suplementares ou especiais. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 128**. O Ministério Público abrange:</summary>
<details open style="margin-left: 30px;">
<summary>**I - **o Ministério Público da União, que compreende:</summary>
<span style="display: block; margin-left: 60px;">**a)** o Ministério Público Federal;</span>

<span style="display: block; margin-left: 60px;">**b)** o Ministério Público do Trabalho;</span>

<span style="display: block; margin-left: 60px;">**c)** o Ministério Público Militar;</span>

<span style="display: block; margin-left: 60px;">**d)** o Ministério Público do Distrito Federal e Territórios;</span>

</details>

<span style="display: block; margin-left: 30px;">**II - **os Ministérios Públicos dos Estados.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º O Ministério Público da União tem por chefe o Procurador-Geral da República, nomeado pelo Presidente da República dentre integrantes da carreira, maiores de trinta e cinco anos, após a aprovação de seu nome pela maioria absoluta dos membros do Senado Federal, para mandato de dois anos, permitida a recondução.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º A destituição do Procurador-Geral da República, por iniciativa do Presidente da República, deverá ser precedida de autorização da maioria absoluta do Senado Federal.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Os Ministérios Públicos dos Estados e o do Distrito Federal e Territórios formarão lista tríplice dentre integrantes da carreira, na forma da lei respectiva, para escolha de seu Procurador-Geral, que será nomeado pelo Chefe do Poder Executivo, para mandato de dois anos, permitida uma recondução.</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Os Procuradores-Gerais nos Estados e no Distrito Federal e Territórios poderão ser destituídos por deliberação da maioria absoluta do Poder Legislativo, na forma da lei complementar respectiva.</span>

<details open style="margin-left: 30px;">
<summary>**§ 5**º Leis complementares da União e dos Estados, cuja iniciativa é facultada aos respectivos Procuradores-Gerais, estabelecerão a organização, as atribuições e o estatuto de cada Ministério Público, observadas, relativamente a seus membros:</summary>
<details open style="margin-left: 60px;">
<summary>**I - **as seguintes garantias:</summary>
<span style="display: block; margin-left: 90px;">**a)** vitaliciedade, após dois anos de exercício, não podendo perder o cargo senão por sentença judicial transitada em julgado;</span>

<span style="display: block; margin-left: 90px;">**b)** inamovibilidade, salvo por motivo de interesse público, mediante decisão do órgão colegiado competente do Ministério Público, pelo voto da maioria absoluta de seus membros, assegurada ampla defesa; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 90px;">**c)** irredutibilidade de subsídio, fixado na forma do art. 39, § 4º, e ressalvado o disposto nos arts. 37, X e XI, 150, II, 153, III, 153, § 2º, I; (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

</details>

<details open style="margin-left: 60px;">
<summary>**II - **as seguintes vedações:</summary>
<span style="display: block; margin-left: 90px;">**a)** receber, a qualquer título e sob qualquer pretexto, honorários, percentagens ou custas processuais;</span>

<span style="display: block; margin-left: 90px;">**b)** exercer a advocacia;</span>

<span style="display: block; margin-left: 90px;">**c)** participar de sociedade comercial, na forma da lei;</span>

<span style="display: block; margin-left: 90px;">**d)** exercer, ainda que em disponibilidade, qualquer outra função pública, salvo uma de magistério;</span>

<span style="display: block; margin-left: 90px;">**e)** exercer atividade político-partidária; (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 90px;">**f)** receber, a qualquer título ou pretexto, auxílios ou contribuições de pessoas físicas, entidades públicas ou privadas, ressalvadas as exceções previstas em lei. (Incluída pela Emenda Constitucional nº 45, de 2004)</span>

</details>

</details>

<span style="display: block; margin-left: 30px;">**§ 6**º Aplica-se aos membros do Ministério Público o disposto no art. 95, parágrafo único, V. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 129**. São funções institucionais do Ministério Público:</summary>
<span style="display: block; margin-left: 30px;">**I - **promover, privativamente, a ação penal pública, na forma da lei;</span>

<span style="display: block; margin-left: 30px;">**II - **zelar pelo efetivo respeito dos Poderes Públicos e dos serviços de relevância pública aos direitos assegurados nesta Constituição, promovendo as medidas necessárias a sua garantia;</span>

<span style="display: block; margin-left: 30px;">**III - **promover o inquérito civil e a ação civil pública, para a proteção do patrimônio público e social, do meio ambiente e de outros interesses difusos e coletivos;</span>

<span style="display: block; margin-left: 30px;">**IV - **promover a ação de inconstitucionalidade ou representação para fins de intervenção da União e dos Estados, nos casos previstos nesta Constituição;</span>

<span style="display: block; margin-left: 30px;">**V - **defender judicialmente os direitos e interesses das populações indígenas;</span>

<span style="display: block; margin-left: 30px;">**VI - **expedir notificações nos procedimentos administrativos de sua competência, requisitando informações e documentos para instruí-los, na forma da lei complementar respectiva;</span>

<span style="display: block; margin-left: 30px;">**VII - **exercer o controle externo da atividade policial, na forma da lei complementar mencionada no artigo anterior;</span>

<span style="display: block; margin-left: 30px;">**VIII - **requisitar diligências investigatórias e a instauração de inquérito policial, indicados os fundamentos jurídicos de suas manifestações processuais;</span>

<span style="display: block; margin-left: 30px;">**IX - **exercer outras funções que lhe forem conferidas, desde que compatíveis com sua finalidade, sendo-lhe vedada a representação judicial e a consultoria jurídica de entidades públicas.</span>

<span style="display: block; margin-left: 30px;">**§ 1**º A legitimação do Ministério Público para as ações civis previstas neste artigo não impede a de terceiros, nas mesmas hipóteses, segundo o disposto nesta Constituição e na lei.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º As funções do Ministério Público só podem ser exercidas por integrantes da carreira, que deverão residir na comarca da respectiva lotação, salvo autorização do chefe da instituição. (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º O ingresso na carreira do Ministério Público far-se-á mediante concurso público de provas e títulos, assegurada a participação da Ordem dos Advogados do Brasil em sua realização, exigindo-se do bacharel em direito, no mínimo, três anos de atividade jurídica e observando-se, nas nomeações, a ordem de classificação. (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º Aplica-se ao Ministério Público, no que couber, o disposto no art. 93. (Redação dada pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º A distribuição de processos no Ministério Público será imediata. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 130**. Aos membros do Ministério Público junto aos Tribunais de Contas aplicam-se as disposições desta seção pertinentes a direitos, vedações e forma de investidura.</span>

<details open style="margin-left: 0px;">
<summary>**Art. 130**-A. O Conselho Nacional do Ministério Público compõe-se de quatorze membros nomeados pelo Presidente da República, depois de aprovada a escolha pela maioria absoluta do Senado Federal, para um mandato de dois anos, admitida uma recondução, sendo: (Incluído pela Emenda Constitucional nº 45, de 2004)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Os membros do Conselho oriundos do Ministério Público serão indicados pelos respectivos Ministérios Públicos, na forma da lei. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<details open style="margin-left: 30px;">
<summary>**§ 2**º Compete ao Conselho Nacional do Ministério Público o controle da atuação administrativa e financeira do Ministério Público e do cumprimento dos deveres funcionais de seus membros, cabendo lhe: (Incluído pela Emenda Constitucional nº 45, de 2004)</summary>
<span style="display: block; margin-left: 60px;">**III - **receber e conhecer das reclamações contra membros ou órgãos do Ministério Público da União ou dos Estados, inclusive contra seus serviços auxiliares, sem prejuízo da competência disciplinar e correicional da instituição, podendo avocar processos disciplinares em curso, determinar a remoção ou a disponibilidade e aplicar outras sanções administrativas, assegurada ampla defesa; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

</details>

<span style="display: block; margin-left: 30px;">**§ 3**º O Conselho escolherá, em votação secreta, um Corregedor nacional, dentre os membros do Ministério Público que o integram, vedada a recondução, competindo-lhe, além das atribuições que lhe forem conferidas pela lei, as seguintes: (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º O Presidente do Conselho Federal da Ordem dos Advogados do Brasil oficiará junto ao Conselho. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 5**º Leis da União e dos Estados criarão ouvidorias do Ministério Público, competentes para receber reclamações e denúncias de qualquer interessado contra membros ou órgãos do Ministério Público, inclusive contra seus serviços auxiliares, representando diretamente ao Conselho Nacional do Ministério Público. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

</details>

### SEÇÃO II - DA ADVOCACIA PÚBLICA

<details open style="margin-left: 0px;">
<summary>**Art. 131**. A Advocacia-Geral da União é a instituição que, diretamente ou através de órgão vinculado, representa a União, judicial e extrajudicialmente, cabendo-lhe, nos termos da lei complementar que dispuser sobre sua organização e funcionamento, as atividades de consultoria e assessoramento jurídico do Poder Executivo.</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º A Advocacia-Geral da União tem por chefe o Advogado-Geral da União, de livre nomeação pelo Presidente da República dentre cidadãos maiores de trinta e cinco anos, de notável saber jurídico e reputação ilibada.</span>

<span style="display: block; margin-left: 30px;">**§ 2**º O ingresso nas classes iniciais das carreiras da instituição de que trata este artigo far-se-á mediante concurso público de provas e títulos.</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Na execução da dívida ativa de natureza tributária, a representação da União cabe à Procuradoria-Geral da Fazenda Nacional, observado o disposto em lei.</span>

</details>

<details open style="margin-left: 0px;">
<summary>**Art. 132**. Os Procuradores dos Estados e do Distrito Federal, organizados em carreira, na qual o ingresso dependerá de concurso público de provas e títulos, com a participação da Ordem dos Advogados do Brasil em todas as suas fases, exercerão a representação judicial e a consultoria jurídica das respectivas unidades federadas. (Redação dada pela Emenda Constitucional nº 19, de 1998)</summary>
<span style="display: block; margin-left: 30px;">**Parágrafo único**. Aos procuradores referidos neste artigo é assegurada estabilidade após três anos de efetivo exercício, mediante avaliação de desempenho perante os órgãos próprios, após relatório circunstanciado das corregedorias. (Incluído pela Emenda Constitucional nº 19, de 1998)</span>

</details>

### SEÇÃO III - Da Advocacia

<span style="display: block; margin-left: 0px;">**Art. 133**. O advogado é indispensável à administração da justiça, sendo inviolável por seus atos e manifestações no exercício da profissão, nos limites da lei.</span>

### SEÇÃO IV - Da Defensoria Pública

<details open style="margin-left: 0px;">
<summary>**Art. 134**. A Defensoria Pública é instituição permanente, essencial à função jurisdicional do Estado, incumbindo-lhe, como expressão e instrumento do regime democrático, fundamentalmente, a orientação jurídica, a promoção dos direitos humanos e a defesa, em todos os graus, judicial e extrajudicial, dos direitos individuais e coletivos, de forma integral e gratuita, aos necessitados, na forma do inciso LXXIV do art. 5º desta Constituição Federal. (Redação dada pela Emenda Constitucional nº 80, de 2014)</summary>
<span style="display: block; margin-left: 30px;">**§ 1**º Lei complementar organizará a Defensoria Pública da União e do Distrito Federal e dos Territórios e prescreverá normas gerais para sua organização nos Estados, em cargos de carreira, providos, na classe inicial, mediante concurso público de provas e títulos, assegurada a seus integrantes a garantia da inamovibilidade e vedado o exercício da advocacia fora das atribuições institucionais. (Renumerado do parágrafo único pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 2**º Às Defensorias Públicas Estaduais são asseguradas autonomia funcional e administrativa e a iniciativa de sua proposta orçamentária dentro dos limites estabelecidos na lei de diretrizes orçamentárias e subordinação ao disposto no art. 99, § 2º. (Incluído pela Emenda Constitucional nº 45, de 2004)</span>

<span style="display: block; margin-left: 30px;">**§ 3**º Aplica-se o disposto no § 2º às Defensorias Públicas da União e do Distrito Federal. (Incluído pela Emenda Constitucional nº 74, de 2013)</span>

<span style="display: block; margin-left: 30px;">**§ 4**º São princípios institucionais da Defensoria Pública a unidade, a indivisibilidade e a independência funcional, aplicando-se também, no que couber, o disposto no art. 93 e no inciso II do art. 96 desta Constituição Federal. (Incluído pela Emenda Constitucional nº 80, de 2014)</span>

</details>

<span style="display: block; margin-left: 0px;">**Art. 135**. Os servidores integrantes das carreiras disciplinadas nas Seções II e III deste Capítulo serão remunerados na forma do art. 39, § 4º. (Redação dada pela Emenda Constitucional nº 19, de 1998)</span>

