# TÍTULO VIII - Da Ordem Social

<span class="caret"></span><ul class="nested">
## CAPÍTULO I - DISPOSIÇÃO GERAL

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 193**. A ordem social tem como base o primado do trabalho, e como objetivo o bem-estar e a justiça sociais.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. O Estado exercerá a função de planejamento das políticas sociais, assegurada, na forma da lei, a participação da sociedade nos processos de formulação, de monitoramento, de controle e de avaliação dessas políticas. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
</ul>
## CAPÍTULO II - DA SEGURIDADE SOCIAL

<span class="caret"></span><ul class="nested">
### SEÇÃO I - DISPOSIÇÕES GERAIS

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 194**. A seguridade social compreende um conjunto integrado de ações de iniciativa dos Poderes Públicos e da sociedade, destinadas a assegurar os direitos relativos à saúde, à previdência e à assistência social.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. Compete ao Poder Público, nos termos da lei, organizar a seguridade social, com base nos seguintes objetivos:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **universalidade da cobertura e do atendimento;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **uniformidade e equivalência dos benefícios e serviços às populações urbanas e rurais;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **seletividade e distributividade na prestação dos benefícios e serviços;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **irredutibilidade do valor dos benefícios;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**V - **eqüidade na forma de participação no custeio;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VI - **diversidade da base de financiamento, identificando-se, em rubricas contábeis específicas para cada área, as receitas e as despesas vinculadas a ações de saúde, previdência e assistência social, preservado o caráter contributivo da previdência social; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VII - **caráter democrático e descentralizado da administração, mediante gestão quadripartite, com participação dos trabalhadores, dos empregadores, dos aposentados e do Governo nos órgãos colegiados. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

</ul>
</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 195**. A seguridade social será financiada por toda a sociedade, de forma direta e indireta, nos termos da lei, mediante recursos provenientes dos orçamentos da União, dos Estados, do Distrito Federal e dos Municípios, e das seguintes contribuições sociais: (Vide Emenda Constitucional nº 20, de 1998)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **do empregador, da empresa e da entidade a ela equiparada na forma da lei, incidentes sobre: (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-8">**a)** a folha de salários e demais rendimentos do trabalho pagos ou creditados, a qualquer título, à pessoa física que lhe preste serviço, mesmo sem vínculo empregatício; (Incluído pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**b)** a receita ou o faturamento; (Incluído pela Emenda Constitucional nº 20, de 1998) (Vide Emenda Constitucional nº 132, de 2023) Vigência</span>

<span style="display: block; margin-left: 60px;" class="level-8">**c)** o lucro; (Incluído pela Emenda Constitucional nº 20, de 1998)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-7">**II - **do trabalhador e dos demais segurados da previdência social, podendo ser adotadas alíquotas progressivas de acordo com o valor do salário de contribuição, não incidindo contribuição sobre aposentadoria e pensão concedidas pelo Regime Geral de Previdência Social; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **sobre a receita de concursos de prognósticos.</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **do importador de bens ou serviços do exterior, ou de quem a lei a ele equiparar. (Incluído pela Emenda Constitucional nº 42, de 19.12.2003) (Vide Emenda Constitucional nº 132, de 2023) Vigência</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **sobre bens e serviços, nos termos de lei complementar. (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º - As receitas dos Estados, do Distrito Federal e dos Municípios destinadas à seguridade social constarão dos respectivos orçamentos, não integrando o orçamento da União.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A proposta de orçamento da seguridade social será elaborada de forma integrada pelos órgãos responsáveis pela saúde, previdência social e assistência social, tendo em vista as metas e prioridades estabelecidas na lei de diretrizes orçamentárias, assegurada a cada área a gestão de seus recursos.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º A pessoa jurídica em débito com o sistema da seguridade social, como estabelecido em lei, não poderá contratar com o Poder Público nem dele receber benefícios ou incentivos fiscais ou creditícios. (Vide Medida Provisória nº 526, de 2011) (Vide Lei nº 12.453, de 2011) (Vide Emenda constitucional nº 106, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º A lei poderá instituir outras fontes destinadas a garantir a manutenção ou expansão da seguridade social, obedecido o disposto no art. 154, I.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Nenhum benefício ou serviço da seguridade social poderá ser criado, majorado ou estendido sem a correspondente fonte de custeio total.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º As contribuições sociais de que trata este artigo só poderão ser exigidas após decorridos noventa dias da data da publicação da lei que as houver instituído ou modificado, não se lhes aplicando o disposto no art. 150, III, "b".</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º São isentas de contribuição para a seguridade social as entidades beneficentes de assistência social que atendam às exigências estabelecidas em lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º O produtor, o parceiro, o meeiro e o arrendatário rurais e o pescador artesanal, bem como os respectivos cônjuges, que exerçam suas atividades em regime de economia familiar, sem empregados permanentes, contribuirão para a seguridade social mediante a aplicação de uma alíquota sobre o resultado da comercialização da produção e farão jus aos benefícios nos termos da lei. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 9**º As contribuições sociais previstas no inciso I do caput deste artigo poderão ter alíquotas diferenciadas em razão da atividade econômica, da utilização intensiva de mão de obra, do porte da empresa ou da condição estrutural do mercado de trabalho, sendo também autorizada a adoção de bases de cálculo diferenciadas apenas no caso das alíneas "b" e "c" do inciso I do caput. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 10**. A lei definirá os critérios de transferência de recursos para o sistema único de saúde e ações de assistência social da União para os Estados, o Distrito Federal e os Municípios, e dos Estados para os Municípios, observada a respectiva contrapartida de recursos. (Incluído pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 11**. São vedados a moratória e o parcelamento em prazo superior a 60 (sessenta) meses e, na forma de lei complementar, a remissão e a anistia das contribuições sociais de que tratam a alínea "a" do inciso I e o inciso II do caput. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 12**. A lei definirá os setores de atividade econômica para os quais as contribuições incidentes na forma dos incisos I, b; e IV do caput, serão não-cumulativas. (Incluído pela Emenda Constitucional nº 42, de 19.12.2003) (Vide Emenda Constitucional nº 132, de 2023) Vigência</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 13**. (Revogado). (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 14**. O segurado somente terá reconhecida como tempo de contribuição ao Regime Geral de Previdência Social a competência cuja contribuição seja igual ou superior à contribuição mínima mensal exigida para sua categoria, assegurado o agrupamento de contribuições. (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 15**. A contribuição prevista no inciso V do caput poderá ter sua alíquota fixada em lei ordinária. (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 16**. Aplica-se à contribuição prevista no inciso V do caput o disposto no art. 156-A, § 1º, I a VI, VIII, X a XIII, § 3º, § 5º, II a VI e IX, e §§ 6º a 11 e 13. (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 17**. A contribuição prevista no inciso V do caput não integrará sua própria base de cálculo nem a dos tributos previstos nos arts. 153, VIII, 156-A e 195, I, "b", e IV, e da contribuição para o Programa de Integração Social de que trata o art. 239. (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 18**. Lei estabelecerá as hipóteses de devolução da contribuição prevista no inciso V do caput a pessoas físicas, inclusive em relação a limites e beneficiários, com o objetivo de reduzir as desigualdades de renda. (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 19**. A devolução de que trata o § 18 não será computada na receita corrente líquida da União para os fins do disposto nos arts. 100, § 15, 166, §§ 9º, 12 e 17, e 198, § 2º. (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

</ul>
</ul>
### SEÇÃO II - DA SAÚDE

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 196**. A saúde é direito de todos e dever do Estado, garantido mediante políticas sociais e econômicas que visem à redução do risco de doença e de outros agravos e ao acesso universal e igualitário às ações e serviços para sua promoção, proteção e recuperação.</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 197**. São de relevância pública as ações e serviços de saúde, cabendo ao Poder Público dispor, nos termos da lei, sobre sua regulamentação, fiscalização e controle, devendo sua execução ser feita diretamente ou através de terceiros e, também, por pessoa física ou jurídica de direito privado.</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 198**. As ações e serviços públicos de saúde integram uma rede regionalizada e hierarquizada e constituem um sistema único, organizado de acordo com as seguintes diretrizes: (Vide ADPF 672)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **descentralização, com direção única em cada esfera de governo;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **atendimento integral, com prioridade para as atividades preventivas, sem prejuízo dos serviços assistenciais;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **participação da comunidade.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O sistema único de saúde será financiado, nos termos do art. 195, com recursos do orçamento da seguridade social, da União, dos Estados, do Distrito Federal e dos Municípios, além de outras fontes. (**Parágrafo único** renumerado para § 1º pela Emenda Constitucional nº 29, de 2000)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A União, os Estados, o Distrito Federal e os Municípios aplicarão, anualmente, em ações e serviços públicos de saúde recursos mínimos derivados da aplicação de percentuais calculados sobre: (Incluído pela Emenda Constitucional nº 29, de 2000)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **no caso da União, a receita corrente líquida do respectivo exercício financeiro, não podendo ser inferior a 15% (quinze por cento); (Redação dada pela Emenda Constitucional nº 86, de 2015)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **no caso dos Estados e do Distrito Federal, o produto da arrecadação dos impostos a que se referem os arts. 155 e 156-A e dos recursos de que tratam os arts. 157 e 159, I, "a", e II, deduzidas as parcelas que forem transferidas aos respectivos Municípios; (Redação dada pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **no caso dos Municípios e do Distrito Federal, o produto da arrecadação dos impostos a que se referem os arts. 156 e 156-A e dos recursos de que tratam os arts. 158 e 159, I, "b", e § 3º. (Redação dada pela Emenda Constitucional nº 132, de 2023)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Lei complementar, que será reavaliada pelo menos a cada cinco anos, estabelecerá: (Incluído pela Emenda Constitucional nº 29, de 2000) Regulamento</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **os percentuais de que tratam os incisos II e III do § 2º; (Redação dada pela Emenda Constitucional nº 86, de 2015)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **(revogado). (Redação dada pela Emenda Constitucional nº 86, de 2015)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Os gestores locais do sistema único de saúde poderão admitir agentes comunitários de saúde e agentes de combate às endemias por meio de processo seletivo público, de acordo com a natureza e complexidade de suas atribuições e requisitos específicos para sua atuação. (Incluído pela Emenda Constitucional nº 51, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Lei federal disporá sobre o regime jurídico, o piso salarial profissional nacional, as diretrizes para os Planos de Carreira e a regulamentação das atividades de agente comunitário de saúde e agente de combate às endemias, competindo à União, nos termos da lei, prestar assistência financeira complementar aos Estados, ao Distrito Federal e aos Municípios, para o cumprimento do referido piso salarial. (Redação dada pela Emenda Constitucional nº 63, de 2010) Regulamento</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º Além das hipóteses previstas no § 1º do art. 41 e no § 4º do art. 169 da Constituição Federal, o servidor que exerça funções equivalentes às de agente comunitário de saúde ou de agente de combate às endemias poderá perder o cargo em caso de descumprimento dos requisitos específicos, fixados em lei, para o seu exercício. (Incluído pela Emenda Constitucional nº 51, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º O vencimento dos agentes comunitários de saúde e dos agentes de combate às endemias fica sob responsabilidade da União, e cabe aos Estados, ao Distrito Federal e aos Municípios estabelecer, além de outros consectários e vantagens, incentivos, auxílios, gratificações e indenizações, a fim de valorizar o trabalho desses profissionais. (Incluído pela Emenda Constitucional nº 120, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º Os recursos destinados ao pagamento do vencimento dos agentes comunitários de saúde e dos agentes de combate às endemias serão consignados no orçamento geral da União com dotação própria e exclusiva. (Incluído pela Emenda Constitucional nº 120, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 9**º O vencimento dos agentes comunitários de saúde e dos agentes de combate às endemias não será inferior a 2 (dois) salários mínimos, repassados pela União aos Municípios, aos Estados e ao Distrito Federal. (Incluído pela Emenda Constitucional nº 120, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 10**. Os agentes comunitários de saúde e os agentes de combate às endemias terão também, em razão dos riscos inerentes às funções desempenhadas, aposentadoria especial e, somado aos seus vencimentos, adicional de insalubridade. (Incluído pela Emenda Constitucional nº 120, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 11**. Os recursos financeiros repassados pela União aos Estados, ao Distrito Federal e aos Municípios para pagamento do vencimento ou de qualquer outra vantagem dos agentes comunitários de saúde e dos agentes de combate às endemias não serão objeto de inclusão no cálculo para fins do limite de despesa com pessoal. (Incluído pela Emenda Constitucional nº 120, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 12**. Lei federal instituirá pisos salariais profissionais nacionais para o enfermeiro, o técnico de enfermagem, o auxiliar de enfermagem e a parteira, a serem observados por pessoas jurídicas de direito público e de direito privado. (Incluído pela Emenda Constitucional nº 124, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 13**. A União, os Estados, o Distrito Federal e os Municípios, até o final do exercício financeiro em que for publicada a lei de que trata o § 12 deste artigo, adequarão a remuneração dos cargos ou dos respectivos planos de carreiras, quando houver, de modo a atender aos pisos estabelecidos para cada categoria profissional. (Incluído pela Emenda Constitucional nº 124, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 14**. Compete à União, nos termos da lei, prestar assistência financeira complementar aos Estados, ao Distrito Federal e aos Municípios e às entidades filantrópicas, bem como aos prestadores de serviços contratualizados que atendam, no mínimo, 60% (sessenta por cento) de seus pacientes pelo sistema único de saúde, para o cumprimento dos pisos salariais de que trata o § 12 deste artigo. (Incluído pela Emenda Constitucional nº 127, de 2022)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 15**. Os recursos federais destinados aos pagamentos da assistência financeira complementar aos Estados, ao Distrito Federal e aos Municípios e às entidades filantrópicas, bem como aos prestadores de serviços contratualizados que atendam, no mínimo, 60% (sessenta por cento) de seus pacientes pelo sistema único de saúde, para o cumprimento dos pisos salariais de que trata o § 12 deste artigo serão consignados no orçamento geral da União com dotação própria e exclusiva. (Incluído pela Emenda Constitucional nº 127, de 2022)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 199**. A assistência à saúde é livre à iniciativa privada.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º As instituições privadas poderão participar de forma complementar do sistema único de saúde, segundo diretrizes deste, mediante contrato de direito público ou convênio, tendo preferência as entidades filantrópicas e as sem fins lucrativos.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º É vedada a destinação de recursos públicos para auxílios ou subvenções às instituições privadas com fins lucrativos.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º - É vedada a participação direta ou indireta de empresas ou capitais estrangeiros na assistência à saúde no País, salvo nos casos previstos em lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º A lei disporá sobre as condições e os requisitos que facilitem a remoção de órgãos, tecidos e substâncias humanas para fins de transplante, pesquisa e tratamento, bem como a coleta, processamento e transfusão de sangue e seus derivados, sendo vedado todo tipo de comercialização.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 200**. Ao sistema único de saúde compete, além de outras atribuições, nos termos da lei:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **controlar e fiscalizar procedimentos, produtos e substâncias de interesse para a saúde e participar da produção de medicamentos, equipamentos, imunobiológicos, hemoderivados e outros insumos;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **executar as ações de vigilância sanitária e epidemiológica, bem como as de saúde do trabalhador;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **ordenar a formação de recursos humanos na área de saúde;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **participar da formulação da política e da execução das ações de saneamento básico;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **incrementar, em sua área de atuação, o desenvolvimento científico e tecnológico e a inovação; (Redação dada pela Emenda Constitucional nº 85, de 2015)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **fiscalizar e inspecionar alimentos, compreendido o controle de seu teor nutricional, bem como bebidas e águas para consumo humano;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VII - **participar do controle e fiscalização da produção, transporte, guarda e utilização de substâncias e produtos psicoativos, tóxicos e radioativos;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VIII - **colaborar na proteção do meio ambiente, nele compreendido o do trabalho.</span>

</ul>
</ul>
### SEÇÃO III - DA PREVIDÊNCIA SOCIAL

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 201**. A previdência social será organizada sob a forma do Regime Geral de Previdência Social, de caráter contributivo e de filiação obrigatória, observados critérios que preservem o equilíbrio financeiro e atuarial, e atenderá, na forma da lei, a: (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **cobertura dos eventos de incapacidade temporária ou permanente para o trabalho e idade avançada; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **proteção à maternidade, especialmente à gestante; (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **proteção ao trabalhador em situação de desemprego involuntário; (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **salário-família e auxílio-reclusão para os dependentes dos segurados de baixa renda; (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **pensão por morte do segurado, homem ou mulher, ao cônjuge ou companheiro e dependentes, observado o disposto no § 2º. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º É vedada a adoção de requisitos ou critérios diferenciados para concessão de benefícios, ressalvada, nos termos de lei complementar, a possibilidade de previsão de idade e tempo de contribuição distintos da regra geral para concessão de aposentadoria exclusivamente em favor dos segurados: (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **com deficiência, previamente submetidos a avaliação biopsicossocial realizada por equipe multiprofissional e interdisciplinar; (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **cujas atividades sejam exercidas com efetiva exposição a agentes químicos, físicos e biológicos prejudiciais à saúde, ou associação desses agentes, vedada a caracterização por categoria profissional ou ocupação. (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Nenhum benefício que substitua o salário de contribuição ou o rendimento do trabalho do segurado terá valor mensal inferior ao salário mínimo. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Todos os salários de contribuição considerados para o cálculo de benefício serão devidamente atualizados, na forma da lei. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º É assegurado o reajustamento dos benefícios para preservar-lhes, em caráter permanente, o valor real, conforme critérios definidos em lei. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º É vedada a filiação ao regime geral de previdência social, na qualidade de segurado facultativo, de pessoa participante de regime próprio de previdência. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º A gratificação natalina dos aposentados e pensionistas terá por base o valor dos proventos do mês de dezembro de cada ano. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º É assegurada aposentadoria no regime geral de previdência social, nos termos da lei, obedecidas as seguintes condições: (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **65 (sessenta e cinco) anos de idade, se homem, e 62 (sessenta e dois) anos de idade, se mulher, observado tempo mínimo de contribuição; (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **60 (sessenta) anos de idade, se homem, e 55 (cinquenta e cinco) anos de idade, se mulher, para os trabalhadores rurais e para os que exerçam suas atividades em regime de economia familiar, nestes incluídos o produtor rural, o garimpeiro e o pescador artesanal. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º O requisito de idade a que se refere o inciso I do § 7º será reduzido em 5 (cinco) anos, para o professor que comprove tempo de efetivo exercício das funções de magistério na educação infantil e no ensino fundamental e médio fixado em lei complementar. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 9**º Para fins de aposentadoria, será assegurada a contagem recíproca do tempo de contribuição entre o Regime Geral de Previdência Social e os regimes próprios de previdência social, e destes entre si, observada a compensação financeira, de acordo com os critérios estabelecidos em lei. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 9**º-A. O tempo de serviço militar exercido nas atividades de que tratam os arts. 42, 142 e 143 e o tempo de contribuição ao Regime Geral de Previdência Social ou a regime próprio de previdência social terão contagem recíproca para fins de inativação militar ou aposentadoria, e a compensação financeira será devida entre as receitas de contribuição referentes aos militares e as receitas de contribuição aos demais regimes. (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 10**. Lei complementar poderá disciplinar a cobertura de benefícios não programados, inclusive os decorrentes de acidente do trabalho, a ser atendida concorrentemente pelo Regime Geral de Previdência Social e pelo setor privado. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 11**. Os ganhos habituais do empregado, a qualquer título, serão incorporados ao salário para efeito de contribuição previdenciária e conseqüente repercussão em benefícios, nos casos e na forma da lei. (Incluído dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 12**. Lei instituirá sistema especial de inclusão previdenciária, com alíquotas diferenciadas, para atender aos trabalhadores de baixa renda, inclusive os que se encontram em situação de informalidade, e àqueles sem renda própria que se dediquem exclusivamente ao trabalho doméstico no âmbito de sua residência, desde que pertencentes a famílias de baixa renda. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 13**. A aposentadoria concedida ao segurado de que trata o § 12 terá valor de 1 (um) salário-mínimo. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 14**. É vedada a contagem de tempo de contribuição fictício para efeito de concessão dos benefícios previdenciários e de contagem recíproca. (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 15**. Lei complementar estabelecerá vedações, regras e condições para a acumulação de benefícios previdenciários. (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 16**. Os empregados dos consórcios públicos, das empresas públicas, das sociedades de economia mista e das suas subsidiárias serão aposentados compulsoriamente, observado o cumprimento do tempo mínimo de contribuição, ao atingir a idade máxima de que trata o inciso II do § 1º do art. 40, na forma estabelecida em lei. (Incluído pela Emenda Constitucional nº 103, de 2019)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 202**. O regime de previdência privada, de caráter complementar e organizado de forma autônoma em relação ao regime geral de previdência social, será facultativo, baseado na constituição de reservas que garantam o benefício contratado, e regulado por lei complementar. (Redação dada pela Emenda Constitucional nº 20, de 1998) (Vide Emenda Constitucional nº 20, de 1998)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**° A lei complementar de que trata este artigo assegurará ao participante de planos de benefícios de entidades de previdência privada o pleno acesso às informações relativas à gestão de seus respectivos planos. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**° As contribuições do empregador, os benefícios e as condições contratuais previstas nos estatutos, regulamentos e planos de benefícios das entidades de previdência privada não integram o contrato de trabalho dos participantes, assim como, à exceção dos benefícios concedidos, não integram a remuneração dos participantes, nos termos da lei. (Redação dada pela Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º É vedado o aporte de recursos a entidade de previdência privada pela União, Estados, Distrito Federal e Municípios, suas autarquias, fundações, empresas públicas, sociedades de economia mista e outras entidades públicas, salvo na qualidade de patrocinador, situação na qual, em hipótese alguma, sua contribuição normal poderá exceder a do segurado. (Incluído pela Emenda Constitucional nº 20, de 1998) (Vide Emenda Constitucional nº 20, de 1998)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Lei complementar disciplinará a relação entre a União, Estados, Distrito Federal ou Municípios, inclusive suas autarquias, fundações, sociedades de economia mista e empresas controladas direta ou indiretamente, enquanto patrocinadores de planos de benefícios previdenciários, e as entidades de previdência complementar. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º A lei complementar de que trata o § 4º aplicar-se-á, no que couber, às empresas privadas permissionárias ou concessionárias de prestação de serviços públicos, quando patrocinadoras de planos de benefícios em entidades de previdência complementar. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º Lei complementar estabelecerá os requisitos para a designação dos membros das diretorias das entidades fechadas de previdência complementar instituídas pelos patrocinadores de que trata o § 4º e disciplinará a inserção dos participantes nos colegiados e instâncias de decisão em que seus interesses sejam objeto de discussão e deliberação. (Redação dada pela Emenda Constitucional nº 103, de 2019)</span>

</ul>
</ul>
### SEÇÃO IV - DA ASSISTÊNCIA SOCIAL

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 203**. A assistência social será prestada a quem dela necessitar, independentemente de contribuição à seguridade social, e tem por objetivos:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **a proteção à família, à maternidade, à infância, à adolescência e à velhice;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **o amparo às crianças e adolescentes carentes;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **a promoção da integração ao mercado de trabalho;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **a habilitação e reabilitação das pessoas portadoras de deficiência e a promoção de sua integração à vida comunitária;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **a garantia de um salário mínimo de benefício mensal à pessoa portadora de deficiência e ao idoso que comprovem não possuir meios de prover à própria manutenção ou de tê-la provida por sua família, conforme dispuser a lei.</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **a redução da vulnerabilidade socioeconômica de famílias em situação de pobreza ou de extrema pobreza. (Incluído pela Emenda Constitucional nº 114, de 2021)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 204**. As ações governamentais na área da assistência social serão realizadas com recursos do orçamento da seguridade social, previstos no art. 195, além de outras fontes, e organizadas com base nas seguintes diretrizes:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **descentralização político-administrativa, cabendo a coordenação e as normas gerais à esfera federal e a coordenação e a execução dos respectivos programas às esferas estadual e municipal, bem como a entidades beneficentes e de assistência social;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **participação da população, por meio de organizações representativas, na formulação das políticas e no controle das ações em todos os níveis.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. É facultado aos Estados e ao Distrito Federal vincular a programa de apoio à inclusão e promoção social até cinco décimos por cento de sua receita tributária líquida, vedada a aplicação desses recursos no pagamento de: (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **despesas com pessoal e encargos sociais; (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **serviço da dívida; (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **qualquer outra despesa corrente não vinculada diretamente aos investimentos ou ações apoiados. (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

</ul>
</ul>
</ul>
</ul>
## CAPÍTULO III - DA EDUCAÇÃO, DA CULTURA E DO DESPORTO

<span class="caret"></span><ul class="nested">
### SEÇÃO I - DA EDUCAÇÃO

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 205**. A educação, direito de todos e dever do Estado e da família, será promovida e incentivada com a colaboração da sociedade, visando ao pleno desenvolvimento da pessoa, seu preparo para o exercício da cidadania e sua qualificação para o trabalho.</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 206**. O ensino será ministrado com base nos seguintes princípios:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **igualdade de condições para o acesso e permanência na escola;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **liberdade de aprender, ensinar, pesquisar e divulgar o pensamento, a arte e o saber;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **pluralismo de idéias e de concepções pedagógicas, e coexistência de instituições públicas e privadas de ensino;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **gratuidade do ensino público em estabelecimentos oficiais;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **valorização dos profissionais da educação escolar, garantidos, na forma da lei, planos de carreira, com ingresso exclusivamente por concurso público de provas e títulos, aos das redes públicas; (Redação dada pela Emenda Constitucional nº 53, de 2006) (Vide Lei nº 14.817, de 2024)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **gestão democrática do ensino público, na forma da lei;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VII - **garantia de padrão de qualidade.</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VIII - **piso salarial profissional nacional para os profissionais da educação escolar pública, nos termos de lei federal. (Incluído pela Emenda Constitucional nº 53, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IX - **garantia do direito à educação e à aprendizagem ao longo da vida. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. A lei disporá sobre as categorias de trabalhadores considerados profissionais da educação básica e sobre a fixação de prazo para a elaboração ou adequação de seus planos de carreira, no âmbito da União, dos Estados, do Distrito Federal e dos Municípios. (Incluído pela Emenda Constitucional nº 53, de 2006)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 207**. As universidades gozam de autonomia didático-científica, administrativa e de gestão financeira e patrimonial, e obedecerão ao princípio de indissociabilidade entre ensino, pesquisa e extensão.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º É facultado às universidades admitir professores, técnicos e cientistas estrangeiros, na forma da lei. (Incluído pela Emenda Constitucional nº 11, de 1996)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º O disposto neste artigo aplica-se às instituições de pesquisa científica e tecnológica. (Incluído pela Emenda Constitucional nº 11, de 1996)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 208**. O dever do Estado com a educação será efetivado mediante a garantia de:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **educação básica obrigatória e gratuita dos 4 (quatro) aos 17 (dezessete) anos de idade, assegurada inclusive sua oferta gratuita para todos os que a ela não tiveram acesso na idade própria; (Redação dada pela Emenda Constitucional nº 59, de 2009) (Vide Emenda Constitucional nº 59, de 2009)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **progressiva universalização do ensino médio gratuito; (Redação dada pela Emenda Constitucional nº 14, de 1996)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **atendimento educacional especializado aos portadores de deficiência, preferencialmente na rede regular de ensino;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **educação infantil, em creche e pré-escola, às crianças até 5 (cinco) anos de idade; (Redação dada pela Emenda Constitucional nº 53, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **acesso aos níveis mais elevados do ensino, da pesquisa e da criação artística, segundo a capacidade de cada um;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **oferta de ensino noturno regular, adequado às condições do educando;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VII - **atendimento ao educando, em todas as etapas da educação básica, por meio de programas suplementares de material didáticoescolar, transporte, alimentação e assistência à saúde. (Redação dada pela Emenda Constitucional nº 59, de 2009)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O acesso ao ensino obrigatório e gratuito é direito público subjetivo.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º O não-oferecimento do ensino obrigatório pelo Poder Público, ou sua oferta irregular, importa responsabilidade da autoridade competente.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Compete ao Poder Público recensear os educandos no ensino fundamental, fazer-lhes a chamada e zelar, junto aos pais ou responsáveis, pela freqüência à escola.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 209**. O ensino é livre à iniciativa privada, atendidas as seguintes condições:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **cumprimento das normas gerais da educação nacional;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **autorização e avaliação de qualidade pelo Poder Público.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 210**. Serão fixados conteúdos mínimos para o ensino fundamental, de maneira a assegurar formação básica comum e respeito aos valores culturais e artísticos, nacionais e regionais.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O ensino religioso, de matrícula facultativa, constituirá disciplina dos horários normais das escolas públicas de ensino fundamental.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º O ensino fundamental regular será ministrado em língua portuguesa, assegurada às comunidades indígenas também a utilização de suas línguas maternas e processos próprios de aprendizagem.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 211**. A União, os Estados, o Distrito Federal e os Municípios organizarão em regime de colaboração seus sistemas de ensino.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º A União organizará o sistema federal de ensino e o dos Territórios, financiará as instituições de ensino públicas federais e exercerá, em matéria educacional, função redistributiva e supletiva, de forma a garantir equalização de oportunidades educacionais e padrão mínimo de qualidade do ensino mediante assistência técnica e financeira aos Estados, ao Distrito Federal e aos Municípios; (Redação dada pela Emenda Constitucional nº 14, de 1996)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Os Municípios atuarão prioritariamente no ensino fundamental e na educação infantil. (Redação dada pela Emenda Constitucional nº 14, de 1996)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Os Estados e o Distrito Federal atuarão prioritariamente no ensino fundamental e médio. (Incluído pela Emenda Constitucional nº 14, de 1996)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Na organização de seus sistemas de ensino, a União, os Estados, o Distrito Federal e os Municípios definirão formas de colaboração, de forma a assegurar a universalização, a qualidade e a equidade do ensino obrigatório. (Redação dada pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º A educação básica pública atenderá prioritariamente ao ensino regular. (Incluído pela Emenda Constitucional nº 53, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º A União, os Estados, o Distrito Federal e os Municípios exercerão ação redistributiva em relação a suas escolas. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º O padrão mínimo de qualidade de que trata o § 1º deste artigo considerará as condições adequadas de oferta e terá como referência o Custo Aluno Qualidade (CAQ), pactuados em regime de colaboração na forma disposta em lei complementar, conforme o parágrafo único do art. 23 desta Constituição. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 212**. A União aplicará, anualmente, nunca menos de dezoito, e os Estados, o Distrito Federal e os Municípios vinte e cinco por cento, no mínimo, da receita resultante de impostos, compreendida a proveniente de transferências, na manutenção e desenvolvimento do ensino.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º A parcela da arrecadação de impostos transferida pela União aos Estados, ao Distrito Federal e aos Municípios, ou pelos Estados aos respectivos Municípios, não é considerada, para efeito do cálculo previsto neste artigo, receita do governo que a transferir.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Para efeito do cumprimento do disposto no "caput" deste artigo, serão considerados os sistemas de ensino federal, estadual e municipal e os recursos aplicados na forma do art. 213.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º A distribuição dos recursos públicos assegurará prioridade ao atendimento das necessidades do ensino obrigatório, no que se refere a universalização, garantia de padrão de qualidade e equidade, nos termos do plano nacional de educação. (Redação dada pela Emenda Constitucional nº 59, de 2009)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Os programas suplementares de alimentação e assistência à saúde previstos no art. 208, VII, serão financiados com recursos provenientes de contribuições sociais e outros recursos orçamentários.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º A educação básica pública terá como fonte adicional de financiamento a contribuição social do salário-educação, recolhida pelas empresas na forma da lei. (Redação dada pela Emenda Constitucional nº 53, de 2006) (Vide Decreto nº 6.003, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º As cotas estaduais e municipais da arrecadação da contribuição social do salário-educação serão distribuídas proporcionalmente ao número de alunos matriculados na educação básica nas respectivas redes públicas de ensino. (Incluído pela Emenda Constitucional nº 53, de 2006)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º É vedado o uso dos recursos referidos no caput e nos §§ 5º e 6º deste artigo para pagamento de aposentadorias e de pensões. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º Na hipótese de extinção ou de substituição de impostos, serão redefinidos os percentuais referidos no caput deste artigo e no inciso II do caput do art. 212-A, de modo que resultem recursos vinculados à manutenção e ao desenvolvimento do ensino, bem como os recursos subvinculados aos fundos de que trata o art. 212-A desta Constituição, em aplicações equivalentes às anteriormente praticadas. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 9**º A lei disporá sobre normas de fiscalização, de avaliação e de controle das despesas com educação nas esferas estadual, distrital e municipal. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 212**-A. Os Estados, o Distrito Federal e os Municípios destinarão parte dos recursos a que se refere o caput do art. 212 desta Constituição à manutenção e ao desenvolvimento do ensino na educação básica e à remuneração condigna de seus profissionais, respeitadas as seguintes disposições: (Incluído pela Emenda Constitucional nº 108, de 2020) Regulamento</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **a distribuição dos recursos e de responsabilidades entre o Distrito Federal, os Estados e seus Municípios é assegurada mediante a instituição, no âmbito de cada Estado e do Distrito Federal, de um Fundo de Manutenção e Desenvolvimento da Educação Básica e de Valorização dos Profissionais da Educação (Fundeb), de natureza contábil; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **os fundos referidos no inciso I do caput deste artigo serão constituídos por 20% (vinte por cento): (Redação dada pela Emenda Constitucional nº 132, de 2023)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-8">**a)** das parcelas dos Estados no imposto de que trata o art. 156-A; (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**b)** da parcela do Distrito Federal no imposto de que trata o art. 156-A, relativa ao exercício de sua competência estadual, nos termos do art. 156-A, § 2º; e (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**c)** dos recursos a que se referem os incisos I, II e III do caput do art. 155, o inciso II do caput do art. 157, os incisos II, III e IV do caput do art. 158 e as alíneas "a" e "b" do inciso I e o inciso II do caput do art. 159 desta Constituição; (Incluído pela Emenda Constitucional nº 132, de 2023)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-7">**III - **os recursos referidos no inciso II do caput deste artigo serão distribuídos entre cada Estado e seus Municípios, proporcionalmente ao número de alunos das diversas etapas e modalidades da educação básica presencial matriculados nas respectivas redes, nos âmbitos de atuação prioritária, conforme estabelecido nos §§ 2º e 3º do art. 211 desta Constituição, observadas as ponderações referidas na alínea "a" do inciso X do caput e no § 2º deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **a União complementará os recursos dos fundos a que se refere o inciso II do caput deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **a complementação da União será equivalente a, no mínimo, 23% (vinte e três por cento) do total de recursos a que se refere o inciso II do caput deste artigo, distribuída da seguinte forma: (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-8">**a)** 10 (dez) pontos percentuais no âmbito de cada Estado e do Distrito Federal, sempre que o valor anual por aluno (VAAF), nos termos do inciso III do caput deste artigo, não alcançar o mínimo definido nacionalmente; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**b)** no mínimo, 10,5 (dez inteiros e cinco décimos) pontos percentuais em cada rede pública de ensino municipal, estadual ou distrital, sempre que o valor anual total por aluno (VAAT), referido no inciso VI do caput deste artigo, não alcançar o mínimo definido nacionalmente; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**c)** 2,5 (dois inteiros e cinco décimos) pontos percentuais nas redes públicas que, cumpridas condicionalidades de melhoria de gestão previstas em lei, alcançarem evolução de indicadores a serem definidos, de atendimento e melhoria da aprendizagem com redução das desigualdades, nos termos do sistema nacional de avaliação da educação básica; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-7">**VI - **o VAAT será calculado, na forma da lei de que trata o inciso X do caput deste artigo, com base nos recursos a que se refere o inciso II do caput deste artigo, acrescidos de outras receitas e de transferências vinculadas à educação, observado o disposto no § 1º e consideradas as matrículas nos termos do inciso III do caput deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VII - **os recursos de que tratam os incisos II e IV do caput deste artigo serão aplicados pelos Estados e pelos Municípios exclusivamente nos respectivos âmbitos de atuação prioritária, conforme estabelecido nos §§ 2º e 3º do art. 211 desta Constituição; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VIII - **a vinculação de recursos à manutenção e ao desenvolvimento do ensino estabelecida no art. 212 desta Constituição suportará, no máximo, 30% (trinta por cento) da complementação da União, considerados para os fins deste inciso os valores previstos no inciso V do caput deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IX - **o disposto no caput do art. 160 desta Constituição aplica-se aos recursos referidos nos incisos II e IV do caput deste artigo, e seu descumprimento pela autoridade competente importará em crime de responsabilidade; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**X - **a lei disporá, observadas as garantias estabelecidas nos incisos I, II, III e IV do caput e no § 1º do art. 208 e as metas pertinentes do plano nacional de educação, nos termos previstos no art. 214 desta Constituição, sobre: (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-8">**a)** a organização dos fundos referidos no inciso I do caput deste artigo e a distribuição proporcional de seus recursos, as diferenças e as ponderações quanto ao valor anual por aluno entre etapas, modalidades, duração da jornada e tipos de estabelecimento de ensino, observados as respectivas especificidades e os insumos necessários para a garantia de sua qualidade; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**b)** a forma de cálculo do VAAF decorrente do inciso III do caput deste artigo e do VAAT referido no inciso VI do caput deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**c)** a forma de cálculo para distribuição prevista na alínea "c" do inciso V do caput deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**d)** a transparência, o monitoramento, a fiscalização e o controle interno, externo e social dos fundos referidos no inciso I do caput deste artigo, assegurada a criação, a autonomia, a manutenção e a consolidação de conselhos de acompanhamento e controle social, admitida sua integração aos conselhos de educação; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-8">**e)** o conteúdo e a periodicidade da avaliação, por parte do órgão responsável, dos efeitos redistributivos, da melhoria dos indicadores educacionais e da ampliação do atendimento; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-7">**XI - **proporção não inferior a 70% (setenta por cento) de cada fundo referido no inciso I do caput deste artigo, excluídos os recursos de que trata a alínea "c" do inciso V do caput deste artigo, será destinada ao pagamento dos profissionais da educação básica em efetivo exercício, observado, em relação aos recursos previstos na alínea "b" do inciso V do caput deste artigo, o percentual mínimo de 15% (quinze por cento) para despesas de capital; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**XII - **lei específica disporá sobre o piso salarial profissional nacional para os profissionais do magistério da educação básica pública; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**XIII - **a utilização dos recursos a que se refere o § 5º do art. 212 desta Constituição para a complementação da União ao Fundeb, referida no inciso V do caput deste artigo, é vedada. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**XIV - **no exercício de 2025, da complementação de que trata o inciso V docaput, até 10% (dez por cento) dos valores de cada uma das modalidades referidas nesse dispositivo poderão ser repassados pela União para ações de fomento à criação de matrículas em tempo integral na educação básica pública, considerados indicadores de atendimento, melhoria da qualidade e redução de desigualdades, mantida a classificação orçamentária do repasse como Fundeb, não se aplicando, para fins deste inciso, os critérios de que tratam as alíneas "a", "b" e "c" do inciso V deste artigo; (Incluído pela Emenda Constitucional nº 135, de 2024)</span>

<span style="display: block; margin-left: 30px;" class="level-7">**XV - **a partir do exercício de 2026, no mínimo 4% (quatro por cento) dos recursos dos fundos referidos no inciso I docaputdeste artigo serão destinados pelos Estados, pelo Distrito Federal e pelos Municípios à criação de matrículas em tempo integral na educação básica, conforme diretrizes pactuadas entre a União e demais entes da Federação, até o atingimento das metas de educação em tempo integral estabelecidas pelo Plano Nacional de Educação. (Incluído pela Emenda Constitucional nº 135, de 2024)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O cálculo do VAAT, referido no inciso VI do caput deste artigo, deverá considerar, além dos recursos previstos no inciso II do caput deste artigo, pelo menos, as seguintes disponibilidades: (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **receitas de Estados, do Distrito Federal e de Municípios vinculadas à manutenção e ao desenvolvimento do ensino não integrantes dos fundos referidos no inciso I do caput deste artigo; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **cotas estaduais e municipais da arrecadação do salário-educação de que trata o § 6º do art. 212 desta Constituição; (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **complementação da União transferida a Estados, ao Distrito Federal e a Municípios nos termos da alínea "a" do inciso V do caput deste artigo. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Além das ponderações previstas na alínea "a" do inciso X do caput deste artigo, a lei definirá outras relativas ao nível socioeconômico dos educandos e aos indicadores de disponibilidade de recursos vinculados à educação e de potencial de arrecadação tributária de cada ente federado, bem como seus prazos de implementação. (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Será destinada à educação infantil a proporção de 50% (cinquenta por cento) dos recursos globais a que se refere a alínea "b" do inciso V do caput deste artigo, nos termos da lei." (Incluído pela Emenda Constitucional nº 108, de 2020)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 213**. Os recursos públicos serão destinados às escolas públicas, podendo ser dirigidos a escolas comunitárias, confessionais ou filantrópicas, definidas em lei, que:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **comprovem finalidade não-lucrativa e apliquem seus excedentes financeiros em educação;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **assegurem a destinação de seu patrimônio a outra escola comunitária, filantrópica ou confessional, ou ao Poder Público, no caso de encerramento de suas atividades.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º - Os recursos de que trata este artigo poderão ser destinados a bolsas de estudo para o ensino fundamental e médio, na forma da lei, para os que demonstrarem insuficiência de recursos, quando houver falta de vagas e cursos regulares da rede pública na localidade da residência do educando, ficando o Poder Público obrigado a investir prioritariamente na expansão de sua rede na localidade.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º As atividades de pesquisa, de extensão e de estímulo e fomento à inovação realizadas por universidades e/ou por instituições de educação profissional e tecnológica poderão receber apoio financeiro do Poder Público. (Redação dada pela Emenda Constitucional nº 85, de 2015)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 214**. A lei estabelecerá o plano nacional de educação, de duração decenal, com o objetivo de articular o sistema nacional de educação em regime de colaboração e definir diretrizes, objetivos, metas e estratégias de implementação para assegurar a manutenção e desenvolvimento do ensino em seus diversos níveis, etapas e modalidades por meio de ações integradas dos poderes públicos das diferentes esferas federativas que conduzam a: (Redação dada pela Emenda Constitucional nº 59, de 2009)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **erradicação do analfabetismo;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **universalização do atendimento escolar;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **melhoria da qualidade do ensino;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **formação para o trabalho;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **promoção humanística, científica e tecnológica do País.</span>

<span style="display: block; margin-left: 30px;" class="level-7">**VI - **estabelecimento de meta de aplicação de recursos públicos em educação como proporção do produto interno bruto. (Incluído pela Emenda Constitucional nº 59, de 2009)</span>

</ul>
</ul>
### SEÇÃO II - DA CULTURA

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 215**. O Estado garantirá a todos o pleno exercício dos direitos culturais e acesso às fontes da cultura nacional, e apoiará e incentivará a valorização e a difusão das manifestações culturais.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O Estado protegerá as manifestações das culturas populares, indígenas e afro-brasileiras, e das de outros grupos participantes do processo civilizatório nacional. Regulamento</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 216**. Constituem patrimônio cultural brasileiro os bens de natureza material e imaterial, tomados individualmente ou em conjunto, portadores de referência à identidade, à ação, à memória dos diferentes grupos formadores da sociedade brasileira, nos quais se incluem:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **as formas de expressão;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **os modos de criar, fazer e viver;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **as criações científicas, artísticas e tecnológicas;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **as obras, objetos, documentos, edificações e demais espaços destinados às manifestações artístico-culturais;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**V - **os conjuntos urbanos e sítios de valor histórico, paisagístico, artístico, arqueológico, paleontológico, ecológico e científico.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O Poder Público, com a colaboração da comunidade, promoverá e protegerá o patrimônio cultural brasileiro, por meio de inventários, registros, vigilância, tombamento e desapropriação, e de outras formas de acautelamento e preservação.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Cabem à administração pública, na forma da lei, a gestão da documentação governamental e as providências para franquear sua consulta a quantos dela necessitem. (Vide Lei nº 12.527, de 2011)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º A lei estabelecerá incentivos para a produção e o conhecimento de bens e valores culturais.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Os danos e ameaças ao patrimônio cultural serão punidos, na forma da lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Ficam tombados todos os documentos e os sítios detentores de reminiscências históricas dos antigos quilombos.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º É facultado aos Estados e ao Distrito Federal vincular a fundo estadual de fomento à cultura até cinco décimos por cento de sua receita tributária líquida, para o financiamento de programas e projetos culturais, vedada a aplicação desses recursos no pagamento de: (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **despesas com pessoal e encargos sociais; (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **serviço da dívida; (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **qualquer outra despesa corrente não vinculada diretamente aos investimentos ou ações apoiados. (Incluído pela Emenda Constitucional nº 42, de 19.12.2003)</span>

</ul>
</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 216**-A. O Sistema Nacional de Cultura, organizado em regime de colaboração, de forma descentralizada e participativa, institui um processo de gestão e promoção conjunta de políticas públicas de cultura, democráticas e permanentes, pactuadas entre os entes da Federação e a sociedade, tendo por objetivo promover o desenvolvimento humano, social e econômico com pleno exercício dos direitos culturais. (Incluído pela Emenda Constitucional nº 71, de 2012)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O Sistema Nacional de Cultura fundamenta-se na política nacional de cultura e nas suas diretrizes, estabelecidas no Plano Nacional de Cultura, e rege-se pelos seguintes princípios: Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **diversidade das expressões culturais; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **universalização do acesso aos bens e serviços culturais; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **fomento à produção, difusão e circulação de conhecimento e bens culturais; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **cooperação entre os entes federados, os agentes públicos e privados atuantes na área cultural; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**V - **integração e interação na execução das políticas, programas, projetos e ações desenvolvidas; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VI - **complementaridade nos papéis dos agentes culturais; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VII - **transversalidade das políticas culturais; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VIII - **autonomia dos entes federados e das instituições da sociedade civil; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IX - **transparência e compartilhamento das informações; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**X - **democratização dos processos decisórios com participação e controle social; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**XI - **descentralização articulada e pactuada da gestão, dos recursos e das ações; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**XII - **ampliação progressiva dos recursos contidos nos orçamentos públicos para a cultura. Incluído pela Emenda Constitucional nº 71, de 2012</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Constitui a estrutura do Sistema Nacional de Cultura, nas respectivas esferas da Federação: Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **órgãos gestores da cultura; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **conselhos de política cultural; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **conferências de cultura; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **comissões intergestores; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**V - **planos de cultura; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VI - **sistemas de financiamento à cultura; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VII - **sistemas de informações e indicadores culturais; Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VIII - **programas de formação na área da cultura; e Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IX - **sistemas setoriais de cultura. Incluído pela Emenda Constitucional nº 71, de 2012</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Lei federal disporá sobre a regulamentação do Sistema Nacional de Cultura, bem como de sua articulação com os demais sistemas nacionais ou políticas setoriais de governo. Incluído pela Emenda Constitucional nº 71, de 2012</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Os Estados, o Distrito Federal e os Municípios organizarão seus respectivos sistemas de cultura em leis próprias. Incluído pela Emenda Constitucional nº 71, de 2012</span>

</ul>
</ul>
### SEÇÃO III - DO DESPORTO

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 217**. É dever do Estado fomentar práticas desportivas formais e não-formais, como direito de cada um, observados:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **a autonomia das entidades desportivas dirigentes e associações, quanto a sua organização e funcionamento;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **a destinação de recursos públicos para a promoção prioritária do desporto educacional e, em casos específicos, para a do desporto de alto rendimento;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **o tratamento diferenciado para o desporto profissional e o não- profissional;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **a proteção e o incentivo às manifestações desportivas de criação nacional.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O Poder Judiciário só admitirá ações relativas à disciplina e às competições desportivas após esgotarem-se as instâncias da justiça desportiva, regulada em lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A justiça desportiva terá o prazo máximo de sessenta dias, contados da instauração do processo, para proferir decisão final.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º O Poder Público incentivará o lazer, como forma de promoção social.</span>

</ul>
</ul>
</ul>
## CAPÍTULO IV - DA CIÊNCIA, 
TECNOLOGIA E INOVAÇÃO

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 218**. O Estado promoverá e incentivará o desenvolvimento científico, a pesquisa, a capacitação científica e tecnológica e a inovação. (Redação dada pela Emenda Constitucional nº 85, de 2015)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º A pesquisa científica básica e tecnológica receberá tratamento prioritário do Estado, tendo em vista o bem público e o progresso da ciência, tecnologia e inovação. (Redação dada pela Emenda Constitucional nº 85, de 2015)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A pesquisa tecnológica voltar-se-á preponderantemente para a solução dos problemas brasileiros e para o desenvolvimento do sistema produtivo nacional e regional.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º O Estado apoiará a formação de recursos humanos nas áreas de ciência, pesquisa, tecnologia e inovação, inclusive por meio do apoio às atividades de extensão tecnológica, e concederá aos que delas se ocupem meios e condições especiais de trabalho. (Redação dada pela Emenda Constitucional nº 85, de 2015)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º A lei apoiará e estimulará as empresas que invistam em pesquisa, criação de tecnologia adequada ao País, formação e aperfeiçoamento de seus recursos humanos e que pratiquem sistemas de remuneração que assegurem ao empregado, desvinculada do salário, participação nos ganhos econômicos resultantes da produtividade de seu trabalho.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º É facultado aos Estados e ao Distrito Federal vincular parcela de sua receita orçamentária a entidades públicas de fomento ao ensino e à pesquisa científica e tecnológica.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º O Estado, na execução das atividades previstas no caput , estimulará a articulação entre entes, tanto públicos quanto privados, nas diversas esferas de governo. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º O Estado promoverá e incentivará a atuação no exterior das instituições públicas de ciência, tecnologia e inovação, com vistas à execução das atividades previstas no caput. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 219**. O mercado interno integra o patrimônio nacional e será incentivado de modo a viabilizar o desenvolvimento cultural e sócio-econômico, o bem-estar da população e a autonomia tecnológica do País, nos termos de lei federal.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**Parágrafo único**. O Estado estimulará a formação e o fortalecimento da inovação nas empresas, bem como nos demais entes, públicos ou privados, a constituição e a manutenção de parques e polos tecnológicos e de demais ambientes promotores da inovação, a atuação dos inventores independentes e a criação, absorção, difusão e transferência de tecnologia. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 219**-A. A União, os Estados, o Distrito Federal e os Municípios poderão firmar instrumentos de cooperação com órgãos e entidades públicos e com entidades privadas, inclusive para o compartilhamento de recursos humanos especializados e capacidade instalada, para a execução de projetos de pesquisa, de desenvolvimento científico e tecnológico e de inovação, mediante contrapartida financeira ou não financeira assumida pelo ente beneficiário, na forma da lei. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 219**-B. O Sistema Nacional de Ciência, Tecnologia e Inovação (SNCTI) será organizado em regime de colaboração entre entes, tanto públicos quanto privados, com vistas a promover o desenvolvimento científico e tecnológico e a inovação. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Lei federal disporá sobre as normas gerais do SNCTI. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Os Estados, o Distrito Federal e os Municípios legislarão concorrentemente sobre suas peculiaridades. (Incluído pela Emenda Constitucional nº 85, de 2015)</span>

</ul>
</ul>
## CAPÍTULO V - DA COMUNICAÇÃO SOCIAL

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 220**. A manifestação do pensamento, a criação, a expressão e a informação, sob qualquer forma, processo ou veículo não sofrerão qualquer restrição, observado o disposto nesta Constituição.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Nenhuma lei conterá dispositivo que possa constituir embaraço à plena liberdade de informação jornalística em qualquer veículo de comunicação social, observado o disposto no art. 5º, IV, V, X, XIII e XIV.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º É vedada toda e qualquer censura de natureza política, ideológica e artística.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Compete à lei federal:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **regular as diversões e espetáculos públicos, cabendo ao Poder Público informar sobre a natureza deles, as faixas etárias a que não se recomendem, locais e horários em que sua apresentação se mostre inadequada;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **estabelecer os meios legais que garantam à pessoa e à família a possibilidade de se defenderem de programas ou programações de rádio e televisão que contrariem o disposto no art. 221, bem como da propaganda de produtos, práticas e serviços que possam ser nocivos à saúde e ao meio ambiente.</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º A propaganda comercial de tabaco, bebidas alcoólicas, agrotóxicos, medicamentos e terapias estará sujeita a restrições legais, nos termos do inciso II do parágrafo anterior, e conterá, sempre que necessário, advertência sobre os malefícios decorrentes de seu uso.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Os meios de comunicação social não podem, direta ou indiretamente, ser objeto de monopólio ou oligopólio.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º A publicação de veículo impresso de comunicação independe de licença de autoridade.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 221**. A produção e a programação das emissoras de rádio e televisão atenderão aos seguintes princípios:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-7">**I - **preferência a finalidades educativas, artísticas, culturais e informativas;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**II - **promoção da cultura nacional e regional e estímulo à produção independente que objetive sua divulgação;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**III - **regionalização da produção cultural, artística e jornalística, conforme percentuais estabelecidos em lei;</span>

<span style="display: block; margin-left: 30px;" class="level-7">**IV - **respeito aos valores éticos e sociais da pessoa e da família.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 222**. A propriedade de empresa jornalística e de radiodifusão sonora e de sons e imagens é privativa de brasileiros natos ou naturalizados há mais de dez anos, ou de pessoas jurídicas constituídas sob as leis brasileiras e que tenham sede no País. (Redação dada pela Emenda Constitucional nº 36, de 2002)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Em qualquer caso, pelo menos setenta por cento do capital total e do capital votante das empresas jornalísticas e de radiodifusão sonora e de sons e imagens deverá pertencer, direta ou indiretamente, a brasileiros natos ou naturalizados há mais de dez anos, que exercerão obrigatoriamente a gestão das atividades e estabelecerão o conteúdo da programação. (Redação dada pela Emenda Constitucional nº 36, de 2002)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A responsabilidade editorial e as atividades de seleção e direção da programação veiculada são privativas de brasileiros natos ou naturalizados há mais de dez anos, em qualquer meio de comunicação social. (Redação dada pela Emenda Constitucional nº 36, de 2002)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Os meios de comunicação social eletrônica, independentemente da tecnologia utilizada para a prestação do serviço, deverão observar os princípios enunciados no art. 221, na forma de lei específica, que também garantirá a prioridade de profissionais brasileiros na execução de produções nacionais. (Incluído pela Emenda Constitucional nº 36, de 2002)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Lei disciplinará a participação de capital estrangeiro nas empresas de que trata o § 1º. (Incluído pela Emenda Constitucional nº 36, de 2002)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º As alterações de controle societário das empresas de que trata o § 1º serão comunicadas ao Congresso Nacional. (Incluído pela Emenda Constitucional nº 36, de 2002)</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 223**. Compete ao Poder Executivo outorgar e renovar concessão, permissão e autorização para o serviço de radiodifusão sonora e de sons e imagens, observado o princípio da complementaridade dos sistemas privado, público e estatal.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O Congresso Nacional apreciará o ato no prazo do art. 64, § 2º e § 4º, a contar do recebimento da mensagem.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A não renovação da concessão ou permissão dependerá de aprovação de, no mínimo, dois quintos do Congresso Nacional, em votação nominal.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º O ato de outorga ou renovação somente produzirá efeitos legais após deliberação do Congresso Nacional, na forma dos parágrafos anteriores.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º O cancelamento da concessão ou permissão, antes de vencido o prazo, depende de decisão judicial.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º O prazo da concessão ou permissão será de dez anos para as emissoras de rádio e de quinze para as de televisão.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 224**. Para os efeitos do disposto neste capítulo, o Congresso Nacional instituirá, como seu órgão auxiliar, o Conselho de Comunicação Social, na forma da lei.</span>

</ul>
## CAPÍTULO VI - DO MEIO AMBIENTE

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 225**. Todos têm direito ao meio ambiente ecologicamente equilibrado, bem de uso comum do povo e essencial à sadia qualidade de vida, impondo-se ao Poder Público e à coletividade o dever de defendê-lo e preservá- lo para as presentes e futuras gerações.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Para assegurar a efetividade desse direito, incumbe ao Poder Público:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **preservar e restaurar os processos ecológicos essenciais e prover o manejo ecológico das espécies e ecossistemas; (Regulamento)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **preservar a diversidade e a integridade do patrimônio genético do País e fiscalizar as entidades dedicadas à pesquisa e manipulação de material genético; (Regulamento) (Regulamento) (Regulamento) (Regulamento)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **definir, em todas as unidades da Federação, espaços territoriais e seus componentes a serem especialmente protegidos, sendo a alteração e a supressão permitidas somente através de lei, vedada qualquer utilização que comprometa a integridade dos atributos que justifiquem sua proteção; (Regulamento)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **exigir, na forma da lei, para instalação de obra ou atividade potencialmente causadora de significativa degradação do meio ambiente, estudo prévio de impacto ambiental, a que se dará publicidade; (Regulamento)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**V - **controlar a produção, a comercialização e o emprego de técnicas, métodos e substâncias que comportem risco para a vida, a qualidade de vida e o meio ambiente; (Regulamento)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VI - **promover a educação ambiental em todos os níveis de ensino e a conscientização pública para a preservação do meio ambiente;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VII - **proteger a fauna e a flora, vedadas, na forma da lei, as práticas que coloquem em risco sua função ecológica, provoquem a extinção de espécies ou submetam os animais a crueldade. (Regulamento)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VIII - **manter regime fiscal favorecido para os biocombustíveis e para o hidrogênio de baixa emissão de carbono, na forma de lei complementar, a fim de assegurar-lhes tributação inferior à incidente sobre os combustíveis fósseis, capaz de garantir diferencial competitivo em relação a estes, especialmente em relação às contribuições de que tratam o art. 195, I, "b", IV e V, e o art. 239 e aos impostos a que se referem os arts. 155, II, e 156-A. (Redação dada pela Emenda Constitucional nº 132, de 2023)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Aquele que explorar recursos minerais fica obrigado a recuperar o meio ambiente degradado, de acordo com solução técnica exigida pelo órgão público competente, na forma da lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º As condutas e atividades consideradas lesivas ao meio ambiente sujeitarão os infratores, pessoas físicas ou jurídicas, a sanções penais e administrativas, independentemente da obrigação de reparar os danos causados.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º A Floresta Amazônica brasileira, a Mata Atlântica, a Serra do Mar, o Pantanal Mato-Grossense e a Zona Costeira são patrimônio nacional, e sua utilização far-se-á, na forma da lei, dentro de condições que assegurem a preservação do meio ambiente, inclusive quanto ao uso dos recursos naturais. (Regulamento) (Regulamento)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º São indisponíveis as terras devolutas ou arrecadadas pelos Estados, por ações discriminatórias, necessárias à proteção dos ecossistemas naturais.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º As usinas que operem com reator nuclear deverão ter sua localização definida em lei federal, sem o que não poderão ser instaladas.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º Para fins do disposto na parte final do inciso VII do § 1º deste artigo, não se consideram cruéis as práticas desportivas que utilizem animais, desde que sejam manifestações culturais, conforme o § 1º do art. 215 desta Constituição Federal, registradas como bem de natureza imaterial integrante do patrimônio cultural brasileiro, devendo ser regulamentadas por lei específica que assegure o bem-estar dos animais envolvidos. (Incluído pela Emenda Constitucional nº 96, de 2017)</span>

</ul>
</ul>
## CAPÍTULO VII - Da Família, da 
Criança, do Adolescente, do Jovem e do Idoso

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 226**. A família, base da sociedade, tem especial proteção do Estado.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O casamento é civil e gratuita a celebração.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º O casamento religioso tem efeito civil, nos termos da lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º Para efeito da proteção do Estado, é reconhecida a união estável entre o homem e a mulher como entidade familiar, devendo a lei facilitar sua conversão em casamento. (Regulamento)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º Entende-se, também, como entidade familiar a comunidade formada por qualquer dos pais e seus descendentes.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º Os direitos e deveres referentes à sociedade conjugal são exercidos igualmente pelo homem e pela mulher.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º O casamento civil pode ser dissolvido pelo divórcio. (Redação dada Pela Emenda Constitucional nº 66, de 2010)</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º Fundado nos princípios da dignidade da pessoa humana e da paternidade responsável, o planejamento familiar é livre decisão do casal, competindo ao Estado propiciar recursos educacionais e científicos para o exercício desse direito, vedada qualquer forma coercitiva por parte de instituições oficiais ou privadas. Regulamento</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º O Estado assegurará a assistência à família na pessoa de cada um dos que a integram, criando mecanismos para coibir a violência no âmbito de suas relações.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 227**. É dever da família, da sociedade e do Estado assegurar à criança, ao adolescente e ao jovem, com absoluta prioridade, o direito à vida, à saúde, à alimentação, à educação, ao lazer, à profissionalização, à cultura, à dignidade, ao respeito, à liberdade e à convivência familiar e comunitária, além de colocá-los a salvo de toda forma de negligência, discriminação, exploração, violência, crueldade e opressão. (Redação dada Pela Emenda Constitucional nº 65, de 2010)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º O Estado promoverá programas de assistência integral à saúde da criança, do adolescente e do jovem, admitida a participação de entidades não governamentais, mediante políticas específicas e obedecendo aos seguintes preceitos: (Redação dada Pela Emenda Constitucional nº 65, de 2010)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **aplicação de percentual dos recursos públicos destinados à saúde na assistência materno-infantil;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **criação de programas de prevenção e atendimento especializado para as pessoas portadoras de deficiência física, sensorial ou mental, bem como de integração social do adolescente e do jovem portador de deficiência, mediante o treinamento para o trabalho e a convivência, e a facilitação do acesso aos bens e serviços coletivos, com a eliminação de obstáculos arquitetônicos e de todas as formas de discriminação. (Redação dada Pela Emenda Constitucional nº 65, de 2010)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º A lei disporá sobre normas de construção dos logradouros e dos edifícios de uso público e de fabricação de veículos de transporte coletivo, a fim de garantir acesso adequado às pessoas portadoras de deficiência.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º O direito a proteção especial abrangerá os seguintes aspectos:</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **idade mínima de quatorze anos para admissão ao trabalho, observado o disposto no art. 7º, XXXIII;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **garantia de direitos previdenciários e trabalhistas;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**III - **garantia de acesso do trabalhador adolescente e jovem à escola; (Redação dada Pela Emenda Constitucional nº 65, de 2010)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**IV - **garantia de pleno e formal conhecimento da atribuição de ato infracional, igualdade na relação processual e defesa técnica por profissional habilitado, segundo dispuser a legislação tutelar específica;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**V - **obediência aos princípios de brevidade, excepcionalidade e respeito à condição peculiar de pessoa em desenvolvimento, quando da aplicação de qualquer medida privativa da liberdade;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VI - **estímulo do Poder Público, através de assistência jurídica, incentivos fiscais e subsídios, nos termos da lei, ao acolhimento, sob a forma de guarda, de criança ou adolescente órfão ou abandonado;</span>

<span style="display: block; margin-left: 60px;" class="level-7">**VII - **programas de prevenção e atendimento especializado à criança, ao adolescente e ao jovem dependente de entorpecentes e drogas afins. (Redação dada Pela Emenda Constitucional nº 65, de 2010)</span>

</ul>
<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º A lei punirá severamente o abuso, a violência e a exploração sexual da criança e do adolescente.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º A adoção será assistida pelo Poder Público, na forma da lei, que estabelecerá casos e condições de sua efetivação por parte de estrangeiros.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º Os filhos, havidos ou não da relação do casamento, ou por adoção, terão os mesmos direitos e qualificações, proibidas quaisquer designações discriminatórias relativas à filiação.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º No atendimento dos direitos da criança e do adolescente levar-se- á em consideração o disposto no art. 204.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 8**º A lei estabelecerá: (Incluído Pela Emenda Constitucional nº 65, de 2010)</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 60px;" class="level-7">**I - **o estatuto da juventude, destinado a regular os direitos dos jovens; (Incluído Pela Emenda Constitucional nº 65, de 2010)</span>

<span style="display: block; margin-left: 60px;" class="level-7">**II - **o plano nacional de juventude, de duração decenal, visando à articulação das várias esferas do poder público para a execução de políticas públicas. (Incluído Pela Emenda Constitucional nº 65, de 2010)</span>

</ul>
</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 228**. São penalmente inimputáveis os menores de dezoito anos, sujeitos às normas da legislação especial.</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 229**. Os pais têm o dever de assistir, criar e educar os filhos menores, e os filhos maiores têm o dever de ajudar e amparar os pais na velhice, carência ou enfermidade.</span>

<span style="display: block; margin-left: 0px;" class="level-5">**Art. 230**. A família, a sociedade e o Estado têm o dever de amparar as pessoas idosas, assegurando sua participação na comunidade, defendendo sua dignidade e bem-estar e garantindo-lhes o direito à vida.</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º Os programas de amparo aos idosos serão executados preferencialmente em seus lares.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º Aos maiores de sessenta e cinco anos é garantida a gratuidade dos transportes coletivos urbanos.</span>

</ul>
</ul>
## CAPÍTULO VIII - DOS ÍNDIOS

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 231**. São reconhecidos aos índios sua organização social, costumes, línguas, crenças e tradições, e os direitos originários sobre as terras que tradicionalmente ocupam, competindo à União demarcá-las, proteger e fazer respeitar todos os seus bens. Regulamento</span>

<span class="caret"></span><ul class="nested">
<span style="display: block; margin-left: 30px;" class="level-6">**§ 1**º São terras tradicionalmente ocupadas pelos índios as por eles habitadas em caráter permanente, as utilizadas para suas atividades produtivas, as imprescindíveis à preservação dos recursos ambientais necessários a seu bem-estar e as necessárias a sua reprodução física e cultural, segundo seus usos, costumes e tradições.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 2**º As terras tradicionalmente ocupadas pelos índios destinam-se a sua posse permanente, cabendo-lhes o usufruto exclusivo das riquezas do solo, dos rios e dos lagos nelas existentes.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 3**º O aproveitamento dos recursos hídricos, incluídos os potenciais energéticos, a pesquisa e a lavra das riquezas minerais em terras indígenas só podem ser efetivados com autorização do Congresso Nacional, ouvidas as comunidades afetadas, ficando-lhes assegurada participação nos resultados da lavra, na forma da lei.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 4**º As terras de que trata este artigo são inalienáveis e indisponíveis, e os direitos sobre elas, imprescritíveis.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 5**º É vedada a remoção dos grupos indígenas de suas terras, salvo, "ad referendum" do Congresso Nacional, em caso de catástrofe ou epidemia que ponha em risco sua população, ou no interesse da soberania do País, após deliberação do Congresso Nacional, garantido, em qualquer hipótese, o retorno imediato logo que cesse o risco.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 6**º São nulos e extintos, não produzindo efeitos jurídicos, os atos que tenham por objeto a ocupação, o domínio e a posse das terras a que se refere este artigo, ou a exploração das riquezas naturais do solo, dos rios e dos lagos nelas existentes, ressalvado relevante interesse público da União, segundo o que dispuser lei complementar, não gerando a nulidade e a extinção direito a indenização ou a ações contra a União, salvo, na forma da lei, quanto às benfeitorias derivadas da ocupação de boa fé.</span>

<span style="display: block; margin-left: 30px;" class="level-6">**§ 7**º Não se aplica às terras indígenas o disposto no art. 174, § 3º e § 4º.</span>

</ul>
<span style="display: block; margin-left: 0px;" class="level-5">**Art. 232**. Os índios, suas comunidades e organizações são partes legítimas para ingressar em juízo em defesa de seus direitos e interesses, intervindo o Ministério Público em todos os atos do processo.</span>

</ul>
</ul>
